import type { Word } from "./types";

/** Shown once the word has been answered: an example (often a well-known saying) and an optional remark. */
export interface Note {
  /** Latin example sentence or phrase. */
  ex: string;
  /** Czech translation of the example. */
  tr: string;
  /** Derived words, a false friend, a bit of history… */
  remark?: string;
}

// Keyed by `${pos}:${la}`, see noteKey().
type Row = [key: string, ex: string, tr: string, remark?: string];

const ROWS: Row[] = [
  // Podstatná jména
  ["n:aqua", "Aqua vitae est.", "Voda je život.", "Odtud akvárium, akvadukt."],
  ["n:puella", "Puella rosam amat.", "Dívka miluje růži."],
  ["n:terra", "Terra rotunda est.", "Země je kulatá.", "Odtud teritorium, terasa."],
  ["n:silva", "In silva multae arbores sunt.", "V lese je mnoho stromů.", "Odtud jméno Silvestr."],
  ["n:via", "Omnes viae Romam ducunt.", "Všechny cesty vedou do Říma.", "Odtud viadukt."],
  ["n:vita", "Vita brevis, ars longa.", "Život je krátký, umění dlouhé.", "Odtud vitamín, vitální."],
  ["n:insula", "Sicilia est insula.", "Sicílie je ostrov.", "Odtud izolace (odloučení jako na ostrově)."],
  ["n:patria", "Patria nostra pulchra est.", "Naše vlast je krásná.", "Odtud patriot."],
  ["n:porta", "Porta aperta est.", "Brána je otevřená.", "Odtud portál, vrátný = portýr."],
  ["n:stella", "Stellae in caelo lucent.", "Hvězdy svítí na nebi.", "Odtud konstelace."],
  ["n:luna", "Luna nocte lucet.", "Měsíc svítí v noci.", "Odtud lunární."],
  ["n:rosa", "Rosa pulchra est.", "Růže je krásná.", "Odtud rosarium – růžová zahrada i růženec."],
  ["n:nauta", "Nauta navigat.", "Námořník pluje.", "Pozor: nauta je mužského rodu, i když končí na -a. Odtud astronaut."],
  ["n:agricola", "Agricola agrum arat.", "Rolník orá pole.", "Složeno z ager (pole) + colere (obdělávat). Mužský rod."],
  ["n:poeta", "Poeta carmina scribit.", "Básník píše básně.", "Mužský rod, i když končí na -a. Odtud poezie."],
  ["n:familia", "Familia mea magna est.", "Moje rodina je velká.", "Římská familia zahrnovala celou domácnost včetně otroků."],
  ["n:schola", "Discipuli in schola sunt.", "Žáci jsou ve škole.", "Z řeckého scholé = volný čas."],
  ["n:epistula", "Amico epistulam scribo.", "Píšu příteli dopis.", "Odtud epištola."],
  ["n:pecunia", "Pecunia non olet.", "Peníze nesmrdí.", "Výrok připisovaný císaři Vespasianovi, který zdanil veřejné záchody."],
  ["n:ira", "Ira furor brevis est.", "Hněv je krátké šílenství.", "Horatius."],
  ["n:victoria", "Victoria nostra est!", "Vítězství je naše!", "Odtud jméno Viktorie."],
  ["n:sapientia", "Initium sapientiae timor Domini.", "Počátkem moudrosti je bázeň Hospodinova.", "Příbuzné: Homo sapiens."],
  ["n:fortuna", "Audaces fortuna iuvat.", "Odvážným štěstí přeje.", "Fortuna byla i římská bohyně štěstěny."],
  ["n:filia", "Filia matrem amat.", "Dcera miluje matku."],
  ["n:dominus", "Dominus servum vocat.", "Pán volá otroka.", "Odtud dominovat, dominance."],
  ["n:servus", "Servus in agro laborat.", "Otrok pracuje na poli.", "Pozdrav „servus“ znamená původně „(tvůj) služebník“."],
  ["n:amicus", "Amicus certus in re incerta cernitur.", "Pravý přítel se pozná v nouzi.", "Ennius, citováno Ciceronem."],
  ["n:filius", "Filius patri similis est.", "Syn je podobný otci.", "Odtud filiálka – „dceřiná“ pobočka."],
  ["n:animus", "Animus meus laetus est.", "Moje mysl je radostná.", "Odtud animace (vdechnutí duše)."],
  ["n:equus", "Equus in prato est.", "Kůň je na louce.", "Pozor na equus (kůň) a aequus (rovný)."],
  ["n:populus", "Senatus Populusque Romanus", "Senát a lid římský", "Zkratka SPQR. Odtud populární."],
  ["n:ager", "Agricola in agro laborat.", "Rolník pracuje na poli.", "Odtud agrární. Genitiv agrī – e mizí."],
  ["n:puer", "Puer in horto ludit.", "Chlapec si hraje na zahradě.", "Odtud puberta. Genitiv puerī – e zůstává."],
  ["n:liber", "Librum lego.", "Čtu knihu.", "Neplést s liber, lībera, līberum = svobodný."],
  ["n:magister", "Magister discipulos docet.", "Učitel učí žáky.", "Odtud magistr i mistr."],
  ["n:vir", "Vir fortis est.", "Muž je statečný.", "Odtud virtus – mužnost, ctnost."],
  ["n:deus", "Deus caritas est.", "Bůh je láska.", "Odtud deismus."],
  ["n:oculus", "Oculos claudo.", "Zavírám oči.", "Odtud okulár, binokulár."],
  ["n:bellum", "Si vis pacem, para bellum.", "Chceš-li mír, připravuj válku.", "Pozor: bellum (válka) × bellus (hezký)."],
  ["n:donum", "Donum Dei", "Dar Boží", "Odtud donor, donátor."],
  ["n:verbum", "Verba volant, scripta manent.", "Slova odlétají, psané zůstává.", "Odtud verbální."],
  ["n:oppidum", "Oppidum parvum est.", "Městečko je malé.", "Oppida stavěli i Keltové u nás – např. Závist nebo Stradonice."],
  ["n:templum", "Templum deae Minervae", "Chrám bohyně Minervy"],
  ["n:caelum", "Caelum serenum est.", "Nebe je jasné."],
  ["n:periculum", "Periculum in mora.", "Nebezpečí z prodlení.", "Právnické úsloví: kdo otálí, riskuje."],
  ["n:consilium", "Consilium bonum dedit.", "Dal dobrou radu.", "Neplést s concilium = shromáždění, koncil."],
  ["n:auxilium", "Ab amico auxilium peto.", "Žádám přítele o pomoc.", "Odtud auxiliární (pomocný)."],
  ["n:gaudium", "Gaudium magnum nuntio vobis.", "Zvěstuji vám velikou radost.", "Příbuzné: Gaudeamus igitur – radujme se tedy."],
  ["n:rex", "Rex regnat.", "Král vládne.", "Odtud Tyrannosaurus rex – „král tyranských ještěrů“."],
  ["n:lex", "Dura lex, sed lex.", "Tvrdý zákon, ale zákon.", "Odtud legální."],
  ["n:pax", "Pax vobiscum.", "Pokoj s vámi.", "Odtud pacifista."],
  ["n:lux", "Fiat lux.", "Budiž světlo.", "Lux je i jednotka osvětlení."],
  ["n:homo", "Homo homini lupus.", "Člověk člověku vlkem.", "Plautus. Odtud Homo sapiens."],
  ["n:pater", "Pater noster, qui es in caelis", "Otče náš, jenž jsi na nebesích"],
  ["n:mater", "Alma mater", "Živitelka matka", "Tak se říká škole, kterou člověk vystudoval."],
  ["n:frater", "Frater meus maior est.", "Můj bratr je starší.", "Odtud fráter – řeholní bratr."],
  ["n:soror", "Soror mea parva est.", "Moje sestra je malá."],
  ["n:urbs", "Urbi et orbi", "Městu a světu", "Urbs bez dalšího určení znamenalo Řím."],
  ["n:mons", "Mons altus est.", "Hora je vysoká.", "Odtud Montenegro – Černá Hora."],
  ["n:mare", "Mare nostrum", "Naše moře", "Tak Římané říkali Středozemnímu moři. Odtud marina."],
  ["n:corpus", "Mens sana in corpore sano.", "Zdravý duch ve zdravém těle.", "Juvenalis. Odtud korpus."],
  ["n:tempus", "Tempus fugit.", "Čas letí.", "Odtud tempo."],
  ["n:nomen", "Nomen omen.", "Jméno je znamením.", "Odtud nominativ."],
  ["n:caput", "Roma caput mundi.", "Řím, hlava světa.", "Odtud kapitola, kapitán."],
  ["n:civis", "Civis Romanus sum.", "Jsem římský občan.", "Odtud civilní."],
  ["n:miles", "Miles gladio pugnat.", "Voják bojuje mečem.", "Odtud militantní."],
  ["n:dux", "Dux exercitum ducit.", "Vůdce vede vojsko.", "Ze slovesa ducere (vést)."],
  ["n:nox", "Nox longa est.", "Noc je dlouhá.", "Odtud ekvinokcium – rovnodennost (stejně dlouhá noc)."],
  ["n:mors", "Mors certa, hora incerta.", "Smrt je jistá, hodina nejistá."],
  ["n:amor", "Amor vincit omnia.", "Láska vše přemáhá.", "Vergilius."],
  ["n:labor", "Labor omnia vincit.", "Práce vše přemůže.", "Vergilius. Odtud laboratoř."],
  ["n:virtus", "In medio stat virtus.", "Ctnost je uprostřed.", "Od vir (muž) – původně „mužnost“."],
  ["n:flumen", "Flumen latum est.", "Řeka je široká."],
  ["n:hostis", "Hostes urbem oppugnant.", "Nepřátelé útočí na město.", "Odtud hostilní (nepřátelský)."],
  ["n:ignis", "Ignis ardet.", "Oheň hoří.", "Odtud anglické ignition – zapalování."],
  ["n:panis", "Panem et circenses", "Chléb a hry", "Juvenalis o tom, čím se dá uspokojit lid."],
  ["n:canis", "Cave canem!", "Pozor na psa!", "Nápis na mozaice z Pompejí."],
  ["n:leo", "Leo rex animalium est.", "Lev je král zvířat."],
  ["n:arbor", "Arbor alta est.", "Strom je vysoký.", "Ženský rod, i když končí na -or. Odtud arboretum."],
  ["n:manus", "Manus manum lavat.", "Ruka ruku myje.", "Ženský rod. Odtud manuální, manikúra."],
  ["n:domus", "Domus nostra parva est.", "Náš dům je malý.", "Ženský rod. Odtud dóm. Domī = doma."],
  ["n:exercitus", "Exercitus Romanus magnus erat.", "Římské vojsko bylo velké.", "Od exercere (cvičit) – odtud exercírovat."],
  ["n:senatus", "Senatus in curia convenit.", "Senát se schází v kurii.", "Od senex (stařec) – rada starších."],
  ["n:res", "Res publica", "Věc veřejná, stát", "Odtud republika."],
  ["n:dies", "Carpe diem.", "Užívej dne.", "Horatius."],
  ["n:spes", "Spes ultima moritur.", "Naděje umírá poslední."],
  ["n:fides", "Fides, spes, caritas", "Víra, naděje, láska"],

  // Slovesa
  ["v:amo", "Te amo.", "Miluji tě.", "Odtud amatér – ten, kdo něco dělá z lásky."],
  ["v:laudo", "Magistra discipulam laudat.", "Učitelka chválí žačku.", "Laudes = chvály, ranní modlitba církve."],
  ["v:voco", "Mater filium vocat.", "Matka volá syna.", "Odtud vokál, vokativ (5. pád = volací)."],
  ["v:porto", "Omnia mea mecum porto.", "Vše své nosím s sebou.", "Odtud transport, portfolio."],
  ["v:habito", "In urbe habito.", "Bydlím ve městě.", "Odtud habitat."],
  ["v:laboro", "Agricolae in agris laborant.", "Rolníci pracují na polích."],
  ["v:pugno", "Milites fortiter pugnant.", "Vojáci statečně bojují.", "Od pugnus (pěst)."],
  ["v:navigo", "Navigare necesse est.", "Plout je nutné.", "Pompeius. Odtud navigace."],
  ["v:specto", "Spectatores ludos spectant.", "Diváci se dívají na hry.", "Odtud spektákl, spektrum."],
  ["v:do", "Do ut des.", "Dávám, abys dával.", "Zásada vzájemnosti. Pozor: krátké a – dare, datum."],
  ["v:sto", "Puella ante portam stat.", "Dívka stojí před branou.", "Odtud status, stabilní."],
  ["v:video", "Veni, vidi, vici.", "Přišel jsem, viděl jsem, zvítězil jsem.", "Caesar po bitvě u Zely. Odtud video = vidím."],
  ["v:habeo", "Habemus papam.", "Máme papeže.", "Ohlašuje se po zvolení nového papeže."],
  ["v:moneo", "Magister discipulos monet.", "Učitel napomíná žáky.", "Odtud monitor, admonice."],
  ["v:teneo", "Puer librum tenet.", "Chlapec drží knihu.", "Odtud tenor – hlas, který „drží“ melodii."],
  ["v:timeo", "Timeo Danaos et dona ferentes.", "Bojím se Danaů, i když nesou dary.", "Vergilius o trojském koni."],
  ["v:doceo", "Docendo discimus.", "Učením se učíme.", "Seneca. Odtud docent, doktor."],
  ["v:maneo", "Domi maneo.", "Zůstávám doma."],
  ["v:sedeo", "Magister in sella sedet.", "Učitel sedí na židli.", "Odtud sedimentace – usazování."],
  ["v:rideo", "Puellae rident.", "Dívky se smějí.", "Odtud ridikulózní (směšný)."],
  ["v:dico", "Dixi.", "Řekl jsem.", "Tak se zakončovala řeč. Odtud diktát, diktátor."],
  ["v:duco", "Dux milites ducit.", "Vůdce vede vojáky.", "Odtud produkce, redukce, dukát."],
  ["v:scribo", "Epistulam scribo.", "Píšu dopis.", "Odtud skripta, manuskript."],
  ["v:lego", "Discipuli libros legunt.", "Žáci čtou knihy.", "Odtud legenda – „co má být čteno“."],
  ["v:mitto", "Epistulam amico mitto.", "Posílám příteli dopis.", "Odtud mise, misionář, emise."],
  ["v:vinco", "In hoc signo vinces.", "V tomto znamení zvítězíš.", "Vidění Konstantina Velikého před bitvou."],
  ["v:curro", "Equi currunt.", "Koně běží.", "Odtud kurýr, kurz, kurzor."],
  ["v:bibo", "Nunc est bibendum.", "Teď je třeba pít.", "Horatius po vítězství u Actia."],
  ["v:capio", "Milites oppidum capiunt.", "Vojáci dobývají městečko.", "Capere znamená i dobýt. Odtud kapacita."],
  ["v:facio", "Feci, quod potui.", "Udělal jsem, co jsem mohl.", "Odtud fakt, faktura, fakulta."],
  ["v:fugio", "Fugit irreparabile tempus.", "Prchá nenávratný čas.", "Vergilius. Odtud fuga (hudební forma)."],
  ["v:venio", "Veni, Creator Spiritus.", "Přijď, Duchu Stvořiteli.", "Odtud advent – příchod (ad-venire)."],
  ["v:audio", "Audi, vide, tace.", "Slyš, viz, mlč.", "Odtud audio, auditorium."],
  ["v:dormio", "Infans dormit.", "Dítě spí.", "Odtud dormitář – společná ložnice v klášteře."],
  ["v:scio", "Scio me nihil scire.", "Vím, že nic nevím.", "Latinský překlad Sókrata. Odtud scientia = věda."],
  ["v:sum", "Cogito, ergo sum.", "Myslím, tedy jsem.", "Descartes. Nepravidelné: sum, es, est, sumus, estis, sunt."],
  ["v:possum", "Possum, sed nolo.", "Mohu, ale nechci.", "Složeno z potis + sum: pos-sum, pot-es, pot-est…"],
  ["v:eo", "In scholam eo.", "Jdu do školy.", "Nepravidelné: eo, is, it, imus, itis, eunt."],
  ["v:volo", "Volens nolens", "Chtě nechtě", "Nolle = nechtít (ne + velle)."],
  ["v:edo", "Edimus, ut vivamus, non vivimus, ut edamus.", "Jíme, abychom žili, nežijeme, abychom jedli."],
  ["v:quaero", "Quaerite et invenietis.", "Hledejte a naleznete.", "Odtud kvestor – římský úředník, původně vyšetřovatel."],
  ["v:ago", "Quidquid agis, prudenter agas.", "Ať děláš cokoli, dělej to rozvážně.", "Odtud agent, akce, aktivní."],
  ["v:credo", "Credo in unum Deum.", "Věřím v jednoho Boha.", "Odtud krédo, kredit."],
  ["v:vivo", "Dum vivimus, vivamus.", "Dokud žijeme, žijme.", "Vivat! = Ať žije!"],

  // Přídavná jména
  ["a:bonus", "Bonus pastor", "Dobrý pastýř", "Odtud bonus – „něco dobrého“ navíc."],
  ["a:malus", "Mala herba cito crescit.", "Plevel rychle roste.", "Neplést s mālum = jablko."],
  ["a:magnus", "Alexander Magnus", "Alexandr Veliký", "Odtud magnát."],
  ["a:parvus", "Parva domus, magna quies.", "Malý dům, velký klid."],
  ["a:longus", "Via longa est.", "Cesta je dlouhá.", "Odtud longituda – zeměpisná délka."],
  ["a:altus", "Citius, altius, fortius.", "Rychleji, výše, silněji.", "Olympijské heslo. Altus = vysoký i hluboký."],
  ["a:novus", "Nihil novi sub sole.", "Nic nového pod sluncem.", "Kazatel. Odtud novic, inovace."],
  ["a:antiquus", "Roma antiqua", "Starověký Řím", "Odtud antika, antikvariát."],
  ["a:pulcher", "Puella pulchra est.", "Dívka je krásná.", "E v dalších tvarech mizí: pulcher, pulchra, pulchrum (jako ager, agrī)."],
  ["a:liber", "Liber sum.", "Jsem svobodný.", "Neplést s liber, librī = kniha. Odtud liberální."],
  ["a:miser", "Miser servus", "Ubohý otrok", "Odtud mizerný, mizérie."],
  ["a:laetus", "Puer laetus est.", "Chlapec je radostný.", "Odtud jméno Laetitia (Letícia)."],
  ["a:clarus", "Vir clarus", "Slavný muž", "Odtud jméno Klára, klarinet."],
  ["a:multus", "Multi sunt vocati, pauci vero electi.", "Mnoho je povolaných, ale málo vyvolených.", "Odtud multi- (multimédia)."],
  ["a:plenus", "Ave Maria, gratia plena", "Zdrávas Maria, milosti plná", "Odtud plénum."],
  ["a:iustus", "Iustus ut palma florebit.", "Spravedlivý pokvete jako palma.", "Žalm 92. Odtud justice."],
  ["a:fortis", "Fortes fortuna adiuvat.", "Statečným štěstí pomáhá.", "Terentius. Odtud forte (silně, v hudbě)."],
  ["a:brevis", "Brevis esse laboro, obscurus fio.", "Snažím se být stručný, a stávám se nejasným.", "Horatius. Odtud brevíř."],
  ["a:omnis", "Unus pro omnibus, omnes pro uno.", "Jeden za všechny, všichni za jednoho.", "Odtud omnibus – „pro všechny“."],
  ["a:facilis", "Facilis descensus Averno.", "Snadný je sestup do podsvětí.", "Vergilius."],
  ["a:difficilis", "Lingua Latina non difficilis est.", "Latina není těžká.", "Dif-ficilis = ne-snadný."],
  ["a:celer", "Celer ut ventus", "Rychlý jako vítr", "Odtud akcelerace."],
  ["a:acer", "Acer hostis", "Prudký nepřítel", "Neplést s acer, aceris = javor."],
  ["a:felix", "Felix culpa", "Šťastná vina", "Odtud jméno Felix."],
  ["a:ingens", "Elephantus ingens est.", "Slon je obrovský."],
  ["a:sapiens", "Sapiens omnia sua secum portat.", "Moudrý nosí vše své s sebou.", "Odtud Homo sapiens."],
  ["a:dulcis", "Dulce et decorum est pro patria mori.", "Sladké a čestné je zemřít za vlast.", "Horatius. Odtud dolce (v hudbě)."],
  ["a:gravis", "Morbus gravis", "Těžká nemoc", "Odtud gravitace."],
  ["a:tristis", "Puella tristis est.", "Dívka je smutná.", "Odtud tristní."],
  ["a:vetus", "Vetus Testamentum", "Starý zákon", "Odtud veterán."],

  // Ostatní
  ["o:semper", "Semper fidelis.", "Vždy věrný.", "Heslo amerických mariňáků."],
  ["o:numquam", "Nunc aut numquam.", "Teď nebo nikdy.", "Ne + umquam (někdy)."],
  ["o:saepe", "Gutta cavat lapidem non vi, sed saepe cadendo.", "Kapka vyhloubí kámen ne silou, ale častým padáním."],
  ["o:hodie", "Hodie mihi, cras tibi.", "Dnes mně, zítra tobě.", "Nápis na náhrobcích. Hodie = hoc die (tohoto dne)."],
  ["o:cras", "Cras, cras, semper cras.", "Zítra, zítra, pořád zítra.", "Odtud prokrastinace (pro-crastinus)."],
  ["o:heri", "Heri in schola fui.", "Včera jsem byl ve škole."],
  ["o:nunc", "Nunc est bibendum.", "Teď je třeba pít.", "Horatius."],
  ["o:iam", "Iam ver venit.", "Už přichází jaro."],
  ["o:bene", "Bene vixit, qui bene latuit.", "Dobře žil, kdo se dobře skrýval.", "Ovidius. Odtud benefice."],
  ["o:male", "Male parta male dilabuntur.", "Co se zle nabude, zle se rozplyne."],
  ["o:non", "Non scholae, sed vitae discimus.", "Neučíme se pro školu, ale pro život.", "Seneca to původně napsal obráceně – jako výtku."],
  ["o:et", "Et tu, Brute?", "I ty, Brute?", "Et znamená a i také."],
  ["o:sed", "Dura lex, sed lex.", "Tvrdý zákon, ale zákon."],
  ["o:quod", "Gaudeo, quod venisti.", "Raduji se, že jsi přišel.", "Quod znamená protože i že."],
  ["o:aut", "Aut Caesar, aut nihil.", "Buď Caesar, nebo nic.", "Aut… aut = buď… nebo."],
  ["o:cum", "Dominus vobiscum.", "Pán s vámi.", "Za osobní zájmena se cum připojuje: mecum, tecum, vobiscum."],
  ["o:sine", "Sine ira et studio.", "Bez hněvu a zaujatosti.", "Tacitus. Odtud sinekura (beneficium sine cura)."],
  ["o:ad", "Per aspera ad astra.", "Přes překážky ke hvězdám."],
  ["o:in", "In vino veritas.", "Ve víně je pravda.", "In + akuz. = kam (do), in + abl. = kde (v)."],
  ["o:ex", "Ex oriente lux.", "Světlo z východu.", "Před souhláskou často e: e pluribus unum."],
  ["o:ubi", "Ubi bene, ibi patria.", "Kde je dobře, tam je vlast."],
  ["o:cur", "Cur non venis?", "Proč nepřicházíš?"],
  ["o:quis", "Quis custodiet ipsos custodes?", "Kdo bude hlídat samotné hlídače?", "Juvenalis."],
  ["o:ego", "Ego te absolvo.", "Já tě rozhřešuji.", "Odtud ego, egoista."],
  ["o:tu", "Tu es Petrus.", "Ty jsi Petr."],
  ["o:nos", "Ora pro nobis.", "Oroduj za nás.", "Nobis je dativ/ablativ od nos."],
  ["o:unus", "E pluribus unum", "Z mnohých jeden", "Heslo na americké pečeti. Odtud unie."],
  ["o:duo", "Duo cum faciunt idem, non est idem.", "Když dva dělají totéž, není to totéž.", "Odtud duo, duel."],
  ["o:tres", "Tres faciunt collegium.", "Tři tvoří kolegium.", "Odtud trio."],
  ["o:decem", "Decem praecepta", "Deset přikázání", "December byl původně 10. měsíc (rok začínal březnem)."],
  ["o:mille", "Mille passus", "Tisíc kroků", "Tolik měřila římská míle. Odtud milimetr, milion."],
];

export const noteKey = (w: Pick<Word, "pos" | "la">) => `${w.pos}:${w.la}`;

export const NOTES: ReadonlyMap<string, Note> = new Map(
  ROWS.map(([key, ex, tr, remark]) => [key, remark ? { ex, tr, remark } : { ex, tr }]),
);

export const noteFor = (w: Word): Note | undefined => NOTES.get(noteKey(w));
