import type { Word } from "./types";

// Starter vocabulary. Each entry: Latin headword, grammar note (genitive + gender,
// principal parts, or word class), Czech meaning.
type Row = [la: string, info: string, cz: string];

// Podstatná jména
const NOUNS: Row[] = [
  ["aqua", "aquae f.", "voda"],
  ["puella", "puellae f.", "dívka"],
  ["terra", "terrae f.", "země"],
  ["silva", "silvae f.", "les"],
  ["via", "viae f.", "cesta"],
  ["vita", "vitae f.", "život"],
  ["insula", "insulae f.", "ostrov"],
  ["patria", "patriae f.", "vlast"],
  ["porta", "portae f.", "brána"],
  ["stella", "stellae f.", "hvězda"],
  ["luna", "lunae f.", "měsíc"],
  ["rosa", "rosae f.", "růže"],
  ["nauta", "nautae m.", "námořník"],
  ["agricola", "agricolae m.", "rolník"],
  ["poeta", "poetae m.", "básník"],
  ["familia", "familiae f.", "rodina"],
  ["schola", "scholae f.", "škola"],
  ["epistula", "epistulae f.", "dopis"],
  ["pecunia", "pecuniae f.", "peníze"],
  ["ira", "irae f.", "hněv"],
  ["victoria", "victoriae f.", "vítězství"],
  ["sapientia", "sapientiae f.", "moudrost"],
  ["fortuna", "fortunae f.", "štěstí, osud"],
  ["filia", "filiae f.", "dcera"],
  ["dominus", "dominī m.", "pán"],
  ["servus", "servī m.", "otrok"],
  ["amicus", "amīcī m.", "přítel"],
  ["filius", "fīliī m.", "syn"],
  ["animus", "animī m.", "duch, mysl"],
  ["equus", "equī m.", "kůň"],
  ["populus", "populī m.", "lid"],
  ["ager", "agrī m.", "pole"],
  ["puer", "puerī m.", "chlapec"],
  ["liber", "librī m.", "kniha"],
  ["magister", "magistrī m.", "učitel"],
  ["vir", "virī m.", "muž"],
  ["deus", "deī m.", "bůh"],
  ["oculus", "oculī m.", "oko"],
  ["bellum", "bellī n.", "válka"],
  ["donum", "dōnī n.", "dar"],
  ["verbum", "verbī n.", "slovo"],
  ["oppidum", "oppidī n.", "městečko"],
  ["templum", "templī n.", "chrám"],
  ["caelum", "caelī n.", "nebe"],
  ["periculum", "perīculī n.", "nebezpečí"],
  ["consilium", "cōnsiliī n.", "rada"],
  ["auxilium", "auxiliī n.", "pomoc"],
  ["gaudium", "gaudiī n.", "radost"],
  ["rex", "rēgis m.", "král"],
  ["lex", "lēgis f.", "zákon"],
  ["pax", "pācis f.", "mír"],
  ["lux", "lūcis f.", "světlo"],
  ["homo", "hominis m.", "člověk"],
  ["pater", "patris m.", "otec"],
  ["mater", "mātris f.", "matka"],
  ["frater", "frātris m.", "bratr"],
  ["soror", "sorōris f.", "sestra"],
  ["urbs", "urbis f.", "město"],
  ["mons", "montis m.", "hora"],
  ["mare", "maris n.", "moře"],
  ["corpus", "corporis n.", "tělo"],
  ["tempus", "temporis n.", "čas"],
  ["nomen", "nōminis n.", "jméno"],
  ["caput", "capitis n.", "hlava"],
  ["civis", "cīvis m.", "občan"],
  ["miles", "mīlitis m.", "voják"],
  ["dux", "ducis m.", "vůdce"],
  ["nox", "noctis f.", "noc"],
  ["mors", "mortis f.", "smrt"],
  ["amor", "amōris m.", "láska"],
  ["labor", "labōris m.", "práce, námaha"],
  ["virtus", "virtūtis f.", "statečnost, ctnost"],
  ["flumen", "flūminis n.", "řeka"],
  ["hostis", "hostis m.", "nepřítel"],
  ["ignis", "ignis m.", "oheň"],
  ["panis", "pānis m.", "chléb"],
  ["canis", "canis m.", "pes"],
  ["leo", "leōnis m.", "lev"],
  ["arbor", "arboris f.", "strom"],
  ["manus", "manūs f.", "ruka"],
  ["domus", "domūs f.", "dům"],
  ["exercitus", "exercitūs m.", "vojsko"],
  ["senatus", "senātūs m.", "senát"],
  ["res", "reī f.", "věc"],
  ["dies", "diēī m.", "den"],
  ["spes", "speī f.", "naděje"],
  ["fides", "fideī f.", "víra, věrnost"],
];

// Slovesa
const VERBS: Row[] = [
  ["amo", "amāre, amāvī, amātum", "milovat"],
  ["laudo", "laudāre, laudāvī, laudātum", "chválit"],
  ["voco", "vocāre, vocāvī, vocātum", "volat"],
  ["porto", "portāre, portāvī, portātum", "nosit"],
  ["habito", "habitāre, habitāvī, habitātum", "bydlet"],
  ["laboro", "labōrāre, labōrāvī, labōrātum", "pracovat"],
  ["pugno", "pugnāre, pugnāvī, pugnātum", "bojovat"],
  ["navigo", "nāvigāre, nāvigāvī, nāvigātum", "plout"],
  ["specto", "spectāre, spectāvī, spectātum", "dívat se"],
  ["do", "dare, dedī, datum", "dát"],
  ["sto", "stāre, stetī, statum", "stát"],
  ["video", "vidēre, vīdī, vīsum", "vidět"],
  ["habeo", "habēre, habuī, habitum", "mít"],
  ["moneo", "monēre, monuī, monitum", "napomínat"],
  ["teneo", "tenēre, tenuī, tentum", "držet"],
  ["timeo", "timēre, timuī", "bát se"],
  ["doceo", "docēre, docuī, doctum", "učit"],
  ["maneo", "manēre, mānsī, mānsum", "zůstávat"],
  ["sedeo", "sedēre, sēdī, sessum", "sedět"],
  ["rideo", "rīdēre, rīsī, rīsum", "smát se"],
  ["dico", "dīcere, dīxī, dictum", "říkat"],
  ["duco", "dūcere, dūxī, ductum", "vést"],
  ["scribo", "scrībere, scrīpsī, scrīptum", "psát"],
  ["lego", "legere, lēgī, lēctum", "číst"],
  ["mitto", "mittere, mīsī, missum", "posílat"],
  ["vinco", "vincere, vīcī, victum", "vítězit"],
  ["curro", "currere, cucurrī, cursum", "běžet"],
  ["bibo", "bibere, bibī", "pít"],
  ["capio", "capere, cēpī, captum", "brát, chytit"],
  ["facio", "facere, fēcī, factum", "dělat"],
  ["fugio", "fugere, fūgī", "utíkat"],
  ["venio", "venīre, vēnī, ventum", "přijít"],
  ["audio", "audīre, audīvī, audītum", "slyšet"],
  ["dormio", "dormīre, dormīvī, dormītum", "spát"],
  ["scio", "scīre, scīvī, scītum", "vědět"],
  ["sum", "esse, fuī", "být"],
  ["possum", "posse, potuī", "moci"],
  ["eo", "īre, iī, itum", "jít"],
  ["volo", "velle, voluī", "chtít"],
  ["edo", "edere, ēdī, ēsum", "jíst"],
  ["quaero", "quaerere, quaesīvī, quaesītum", "hledat, ptát se"],
  ["ago", "agere, ēgī, āctum", "jednat, konat"],
  ["credo", "crēdere, crēdidī, crēditum", "věřit"],
  ["vivo", "vīvere, vīxī, vīctum", "žít"],
];

// Přídavná jména
const ADJECTIVES: Row[] = [
  ["bonus", "bona, bonum", "dobrý"],
  ["malus", "mala, malum", "špatný"],
  ["magnus", "magna, magnum", "velký"],
  ["parvus", "parva, parvum", "malý"],
  ["longus", "longa, longum", "dlouhý"],
  ["altus", "alta, altum", "vysoký, hluboký"],
  ["novus", "nova, novum", "nový"],
  ["antiquus", "antīqua, antīquum", "starobylý"],
  ["pulcher", "pulchra, pulchrum", "krásný"],
  ["liber", "lībera, līberum", "svobodný"],
  ["miser", "misera, miserum", "ubohý"],
  ["laetus", "laeta, laetum", "radostný"],
  ["clarus", "clāra, clārum", "slavný, jasný"],
  ["multus", "multa, multum", "mnohý"],
  ["plenus", "plēna, plēnum", "plný"],
  ["iustus", "iūsta, iūstum", "spravedlivý"],
  ["fortis", "forte", "statečný, silný"],
  ["brevis", "breve", "krátký"],
  ["omnis", "omne", "všechen, každý"],
  ["facilis", "facile", "snadný"],
  ["difficilis", "difficile", "obtížný"],
  ["celer", "celeris, celere", "rychlý"],
  ["acer", "ācris, ācre", "ostrý, prudký"],
  ["felix", "gen. fēlīcis", "šťastný"],
  ["ingens", "gen. ingentis", "obrovský"],
  ["sapiens", "gen. sapientis", "moudrý"],
  ["dulcis", "dulce", "sladký"],
  ["gravis", "grave", "těžký, vážný"],
  ["tristis", "triste", "smutný"],
  ["vetus", "gen. veteris", "starý"],
];

// Ostatní
const OTHER: Row[] = [
  ["semper", "příslovce", "vždy"],
  ["numquam", "příslovce", "nikdy"],
  ["saepe", "příslovce", "často"],
  ["hodie", "příslovce", "dnes"],
  ["cras", "příslovce", "zítra"],
  ["heri", "příslovce", "včera"],
  ["nunc", "příslovce", "nyní"],
  ["iam", "příslovce", "již"],
  ["bene", "příslovce", "dobře"],
  ["male", "příslovce", "špatně"],
  ["non", "záporka", "ne"],
  ["et", "spojka", "a"],
  ["sed", "spojka", "ale"],
  ["quod", "spojka", "protože"],
  ["aut", "spojka", "nebo"],
  ["cum", "předložka + abl.", "s"],
  ["sine", "předložka + abl.", "bez"],
  ["ad", "předložka + akuz.", "k, do"],
  ["in", "předložka + akuz. / abl.", "do, v"],
  ["ex", "předložka + abl.", "z"],
  ["ubi", "tázací příslovce", "kde"],
  ["cur", "tázací příslovce", "proč"],
  ["quis", "tázací zájmeno", "kdo"],
  ["ego", "osobní zájmeno", "já"],
  ["tu", "osobní zájmeno", "ty"],
  ["nos", "osobní zájmeno", "my"],
  ["unus", "číslovka", "jeden"],
  ["duo", "číslovka", "dva"],
  ["tres", "číslovka", "tři"],
  ["decem", "číslovka", "deset"],
  ["mille", "číslovka", "tisíc"],
];

const tag = (rows: Row[], pos: Word["pos"]): Word[] => rows.map(([la, info, cz]) => ({ la, info, cz, pos }));

export const WORDS: Word[] = [
  ...tag(NOUNS, "n"),
  ...tag(VERBS, "v"),
  ...tag(ADJECTIVES, "a"),
  ...tag(OTHER, "o"),
];
