import { lesson, n, v, a, o } from "./define";

export default lesson("Základní slovíčka", [
  // Podstatná jména
  n("aqua", "aquae f.", "voda", ["Aqua vitae est.", "Voda je život.", "Odtud akvárium, akvadukt."]),
  n("puella", "puellae f.", "dívka", ["Puella rosam amat.", "Dívka miluje růži."]),
  n("terra", "terrae f.", "země", ["Terra rotunda est.", "Země je kulatá.", "Odtud teritorium, terasa."]),
  n("silva", "silvae f.", "les", ["In silva multae arbores sunt.", "V lese je mnoho stromů.", "Odtud jméno Silvestr."]),
  n("via", "viae f.", "cesta", ["Omnes viae Romam ducunt.", "Všechny cesty vedou do Říma.", "Odtud viadukt."]),
  n("vita", "vitae f.", "život", ["Vita brevis, ars longa.", "Život je krátký, umění dlouhé.", "Odtud vitamín, vitální."]),
  n("insula", "insulae f.", "ostrov", ["Sicilia est insula.", "Sicílie je ostrov.", "Odtud izolace (odloučení jako na ostrově)."]),
  n("patria", "patriae f.", "vlast", ["Patria nostra pulchra est.", "Naše vlast je krásná.", "Odtud patriot."]),
  n("porta", "portae f.", "brána", ["Porta aperta est.", "Brána je otevřená.", "Odtud portál, vrátný = portýr."]),
  n("stella", "stellae f.", "hvězda", ["Stellae in caelo lucent.", "Hvězdy svítí na nebi.", "Odtud konstelace."]),
  n("luna", "lunae f.", "měsíc", ["Luna nocte lucet.", "Měsíc svítí v noci.", "Odtud lunární."]),
  n("rosa", "rosae f.", "růže", ["Rosa pulchra est.", "Růže je krásná.", "Odtud rosarium – růžová zahrada i růženec."]),
  n("nauta", "nautae m.", "námořník", ["Nauta navigat.", "Námořník pluje.", "Pozor: nauta je mužského rodu, i když končí na -a. Odtud astronaut."]),
  n("agricola", "agricolae m.", "rolník", ["Agricola agrum arat.", "Rolník orá pole.", "Složeno z ager (pole) + colere (obdělávat). Mužský rod."]),
  n("poeta", "poetae m.", "básník", ["Poeta carmina scribit.", "Básník píše básně.", "Mužský rod, i když končí na -a. Odtud poezie."]),
  n("familia", "familiae f.", "rodina", ["Familia mea magna est.", "Moje rodina je velká.", "Římská familia zahrnovala celou domácnost včetně otroků."]),
  n("schola", "scholae f.", "škola", ["Discipuli in schola sunt.", "Žáci jsou ve škole.", "Z řeckého scholé = volný čas."]),
  n("epistula", "epistulae f.", "dopis", ["Amico epistulam scribo.", "Píšu příteli dopis.", "Odtud epištola."]),
  n("pecunia", "pecuniae f.", "peníze", ["Pecunia non olet.", "Peníze nesmrdí.", "Výrok připisovaný císaři Vespasianovi, který zdanil veřejné záchody."]),
  n("ira", "irae f.", "hněv", ["Ira furor brevis est.", "Hněv je krátké šílenství.", "Horatius."]),
  n("victoria", "victoriae f.", "vítězství", ["Victoria nostra est!", "Vítězství je naše!", "Odtud jméno Viktorie."]),
  n("sapientia", "sapientiae f.", "moudrost", ["Initium sapientiae timor Domini.", "Počátkem moudrosti je bázeň Hospodinova.", "Příbuzné: Homo sapiens."]),
  n("fortuna", "fortunae f.", "štěstí, osud", ["Audaces fortuna iuvat.", "Odvážným štěstí přeje.", "Fortuna byla i římská bohyně štěstěny."]),
  n("filia", "filiae f.", "dcera", ["Filia matrem amat.", "Dcera miluje matku."]),
  n("dominus", "dominī m.", "pán", ["Dominus servum vocat.", "Pán volá otroka.", "Odtud dominovat, dominance."]),
  n("servus", "servī m.", "otrok", ["Servus in agro laborat.", "Otrok pracuje na poli.", "Pozdrav „servus“ znamená původně „(tvůj) služebník“."]),
  n("amicus", "amīcī m.", "přítel", ["Amicus certus in re incerta cernitur.", "Pravý přítel se pozná v nouzi.", "Ennius, citováno Ciceronem."]),
  n("filius", "fīliī m.", "syn", ["Filius patri similis est.", "Syn je podobný otci.", "Odtud filiálka – „dceřiná“ pobočka."]),
  n("animus", "animī m.", "duch, mysl", ["Animus meus laetus est.", "Moje mysl je radostná.", "Odtud animace (vdechnutí duše)."]),
  n("equus", "equī m.", "kůň", ["Equus in prato est.", "Kůň je na louce.", "Pozor na equus (kůň) a aequus (rovný)."]),
  n("populus", "populī m.", "lid", ["Senatus Populusque Romanus", "Senát a lid římský", "Zkratka SPQR. Odtud populární."]),
  n("ager", "agrī m.", "pole", ["Agricola in agro laborat.", "Rolník pracuje na poli.", "Odtud agrární. Genitiv agrī – e mizí."]),
  n("puer", "puerī m.", "chlapec", ["Puer in horto ludit.", "Chlapec si hraje na zahradě.", "Odtud puberta. Genitiv puerī – e zůstává."]),
  n("liber", "librī m.", "kniha", ["Librum lego.", "Čtu knihu.", "Neplést s liber, lībera, līberum = svobodný."]),
  n("magister", "magistrī m.", "učitel", ["Magister discipulos docet.", "Učitel učí žáky.", "Odtud magistr i mistr."]),
  n("vir", "virī m.", "muž", ["Vir fortis est.", "Muž je statečný.", "Odtud virtus – mužnost, ctnost."]),
  n("deus", "deī m.", "bůh", ["Deus caritas est.", "Bůh je láska.", "Odtud deismus."]),
  n("oculus", "oculī m.", "oko", ["Oculos claudo.", "Zavírám oči.", "Odtud okulár, binokulár."]),
  n("bellum", "bellī n.", "válka", ["Si vis pacem, para bellum.", "Chceš-li mír, připravuj válku.", "Pozor: bellum (válka) × bellus (hezký)."]),
  n("donum", "dōnī n.", "dar", ["Donum Dei", "Dar Boží", "Odtud donor, donátor."]),
  n("verbum", "verbī n.", "slovo", ["Verba volant, scripta manent.", "Slova odlétají, psané zůstává.", "Odtud verbální."]),
  n("oppidum", "oppidī n.", "městečko", ["Oppidum parvum est.", "Městečko je malé.", "Oppida stavěli i Keltové u nás – např. Závist nebo Stradonice."]),
  n("templum", "templī n.", "chrám", ["Templum deae Minervae", "Chrám bohyně Minervy"]),
  n("caelum", "caelī n.", "nebe", ["Caelum serenum est.", "Nebe je jasné."]),
  n("periculum", "perīculī n.", "nebezpečí", ["Periculum in mora.", "Nebezpečí z prodlení.", "Právnické úsloví: kdo otálí, riskuje."]),
  n("consilium", "cōnsiliī n.", "rada", ["Consilium bonum dedit.", "Dal dobrou radu.", "Neplést s concilium = shromáždění, koncil."]),
  n("auxilium", "auxiliī n.", "pomoc", ["Ab amico auxilium peto.", "Žádám přítele o pomoc.", "Odtud auxiliární (pomocný)."]),
  n("gaudium", "gaudiī n.", "radost", ["Gaudium magnum nuntio vobis.", "Zvěstuji vám velikou radost.", "Příbuzné: Gaudeamus igitur – radujme se tedy."]),
  n("rex", "rēgis m.", "král", ["Rex regnat.", "Král vládne.", "Odtud Tyrannosaurus rex – „král tyranských ještěrů“."]),
  n("lex", "lēgis f.", "zákon", ["Dura lex, sed lex.", "Tvrdý zákon, ale zákon.", "Odtud legální."]),
  n("pax", "pācis f.", "mír", ["Pax vobiscum.", "Pokoj s vámi.", "Odtud pacifista."]),
  n("lux", "lūcis f.", "světlo", ["Fiat lux.", "Budiž světlo.", "Lux je i jednotka osvětlení."]),
  n("homo", "hominis m.", "člověk", ["Homo homini lupus.", "Člověk člověku vlkem.", "Plautus. Odtud Homo sapiens."]),
  n("pater", "patris m.", "otec", ["Pater noster, qui es in caelis", "Otče náš, jenž jsi na nebesích"]),
  n("mater", "mātris f.", "matka", ["Alma mater", "Živitelka matka", "Tak se říká škole, kterou člověk vystudoval."]),
  n("frater", "frātris m.", "bratr", ["Frater meus maior est.", "Můj bratr je starší.", "Odtud fráter – řeholní bratr."]),
  n("soror", "sorōris f.", "sestra", ["Soror mea parva est.", "Moje sestra je malá."]),
  n("urbs", "urbis f.", "město", ["Urbi et orbi", "Městu a světu", "Urbs bez dalšího určení znamenalo Řím."]),
  n("mons", "montis m.", "hora", ["Mons altus est.", "Hora je vysoká.", "Odtud Montenegro – Černá Hora."]),
  n("mare", "maris n.", "moře", ["Mare nostrum", "Naše moře", "Tak Římané říkali Středozemnímu moři. Odtud marina."]),
  n("corpus", "corporis n.", "tělo", ["Mens sana in corpore sano.", "Zdravý duch ve zdravém těle.", "Juvenalis. Odtud korpus."]),
  n("tempus", "temporis n.", "čas", ["Tempus fugit.", "Čas letí.", "Odtud tempo."]),
  n("nomen", "nōminis n.", "jméno", ["Nomen omen.", "Jméno je znamením.", "Odtud nominativ."]),
  n("caput", "capitis n.", "hlava", ["Roma caput mundi.", "Řím, hlava světa.", "Odtud kapitola, kapitán."]),
  n("civis", "cīvis m.", "občan", ["Civis Romanus sum.", "Jsem římský občan.", "Odtud civilní."]),
  n("miles", "mīlitis m.", "voják", ["Miles gladio pugnat.", "Voják bojuje mečem.", "Odtud militantní."]),
  n("dux", "ducis m.", "vůdce", ["Dux exercitum ducit.", "Vůdce vede vojsko.", "Ze slovesa ducere (vést)."]),
  n("nox", "noctis f.", "noc", ["Nox longa est.", "Noc je dlouhá.", "Odtud ekvinokcium – rovnodennost (stejně dlouhá noc)."]),
  n("mors", "mortis f.", "smrt", ["Mors certa, hora incerta.", "Smrt je jistá, hodina nejistá."]),
  n("amor", "amōris m.", "láska", ["Amor vincit omnia.", "Láska vše přemáhá.", "Vergilius."]),
  n("labor", "labōris m.", "práce, námaha", ["Labor omnia vincit.", "Práce vše přemůže.", "Vergilius. Odtud laboratoř."]),
  n("virtus", "virtūtis f.", "statečnost, ctnost", ["In medio stat virtus.", "Ctnost je uprostřed.", "Od vir (muž) – původně „mužnost“."]),
  n("flumen", "flūminis n.", "řeka", ["Flumen latum est.", "Řeka je široká."]),
  n("hostis", "hostis m.", "nepřítel", ["Hostes urbem oppugnant.", "Nepřátelé útočí na město.", "Odtud hostilní (nepřátelský)."]),
  n("ignis", "ignis m.", "oheň", ["Ignis ardet.", "Oheň hoří.", "Odtud anglické ignition – zapalování."]),
  n("panis", "pānis m.", "chléb", ["Panem et circenses", "Chléb a hry", "Juvenalis o tom, čím se dá uspokojit lid."]),
  n("canis", "canis m.", "pes", ["Cave canem!", "Pozor na psa!", "Nápis na mozaice z Pompejí."]),
  n("leo", "leōnis m.", "lev", ["Leo rex animalium est.", "Lev je král zvířat."]),
  n("arbor", "arboris f.", "strom", ["Arbor alta est.", "Strom je vysoký.", "Ženský rod, i když končí na -or. Odtud arboretum."]),
  n("manus", "manūs f.", "ruka", ["Manus manum lavat.", "Ruka ruku myje.", "Ženský rod. Odtud manuální, manikúra."]),
  n("domus", "domūs f.", "dům", ["Domus nostra parva est.", "Náš dům je malý.", "Ženský rod. Odtud dóm. Domī = doma."]),
  n("exercitus", "exercitūs m.", "vojsko", ["Exercitus Romanus magnus erat.", "Římské vojsko bylo velké.", "Od exercere (cvičit) – odtud exercírovat."]),
  n("senatus", "senātūs m.", "senát", ["Senatus in curia convenit.", "Senát se schází v kurii.", "Od senex (stařec) – rada starších."]),
  n("res", "reī f.", "věc", ["Res publica", "Věc veřejná, stát", "Odtud republika."]),
  n("dies", "diēī m.", "den", ["Carpe diem.", "Užívej dne.", "Horatius."]),
  n("spes", "speī f.", "naděje", ["Spes ultima moritur.", "Naděje umírá poslední."]),
  n("fides", "fideī f.", "víra, věrnost", ["Fides, spes, caritas", "Víra, naděje, láska"]),
  // Slovesa
  v("amo", "amāre, amāvī, amātum", "milovat", ["Te amo.", "Miluji tě.", "Odtud amatér – ten, kdo něco dělá z lásky."]),
  v("laudo", "laudāre, laudāvī, laudātum", "chválit", ["Magistra discipulam laudat.", "Učitelka chválí žačku.", "Laudes = chvály, ranní modlitba církve."]),
  v("voco", "vocāre, vocāvī, vocātum", "volat", ["Mater filium vocat.", "Matka volá syna.", "Odtud vokál, vokativ (5. pád = volací)."]),
  v("porto", "portāre, portāvī, portātum", "nosit", ["Omnia mea mecum porto.", "Vše své nosím s sebou.", "Odtud transport, portfolio."]),
  v("habito", "habitāre, habitāvī, habitātum", "bydlet", ["In urbe habito.", "Bydlím ve městě.", "Odtud habitat."]),
  v("laboro", "labōrāre, labōrāvī, labōrātum", "pracovat", ["Agricolae in agris laborant.", "Rolníci pracují na polích."]),
  v("pugno", "pugnāre, pugnāvī, pugnātum", "bojovat", ["Milites fortiter pugnant.", "Vojáci statečně bojují.", "Od pugnus (pěst)."]),
  v("navigo", "nāvigāre, nāvigāvī, nāvigātum", "plout", ["Navigare necesse est.", "Plout je nutné.", "Pompeius. Odtud navigace."]),
  v("specto", "spectāre, spectāvī, spectātum", "dívat se", ["Spectatores ludos spectant.", "Diváci se dívají na hry.", "Odtud spektákl, spektrum."]),
  v("do", "dare, dedī, datum", "dát", ["Do ut des.", "Dávám, abys dával.", "Zásada vzájemnosti. Pozor: krátké a – dare, datum."]),
  v("sto", "stāre, stetī, statum", "stát", ["Puella ante portam stat.", "Dívka stojí před branou.", "Odtud status, stabilní."]),
  v("video", "vidēre, vīdī, vīsum", "vidět", ["Veni, vidi, vici.", "Přišel jsem, viděl jsem, zvítězil jsem.", "Caesar po bitvě u Zely. Odtud video = vidím."]),
  v("habeo", "habēre, habuī, habitum", "mít", ["Habemus papam.", "Máme papeže.", "Ohlašuje se po zvolení nového papeže."]),
  v("moneo", "monēre, monuī, monitum", "napomínat", ["Magister discipulos monet.", "Učitel napomíná žáky.", "Odtud monitor, admonice."]),
  v("teneo", "tenēre, tenuī, tentum", "držet", ["Puer librum tenet.", "Chlapec drží knihu.", "Odtud tenor – hlas, který „drží“ melodii."]),
  v("timeo", "timēre, timuī", "bát se", ["Timeo Danaos et dona ferentes.", "Bojím se Danaů, i když nesou dary.", "Vergilius o trojském koni."]),
  v("doceo", "docēre, docuī, doctum", "učit", ["Docendo discimus.", "Učením se učíme.", "Seneca. Odtud docent, doktor."]),
  v("maneo", "manēre, mānsī, mānsum", "zůstávat", ["Domi maneo.", "Zůstávám doma."]),
  v("sedeo", "sedēre, sēdī, sessum", "sedět", ["Magister in sella sedet.", "Učitel sedí na židli.", "Odtud sedimentace – usazování."]),
  v("rideo", "rīdēre, rīsī, rīsum", "smát se", ["Puellae rident.", "Dívky se smějí.", "Odtud ridikulózní (směšný)."]),
  v("dico", "dīcere, dīxī, dictum", "říkat", ["Dixi.", "Řekl jsem.", "Tak se zakončovala řeč. Odtud diktát, diktátor."]),
  v("duco", "dūcere, dūxī, ductum", "vést", ["Dux milites ducit.", "Vůdce vede vojáky.", "Odtud produkce, redukce, dukát."]),
  v("scribo", "scrībere, scrīpsī, scrīptum", "psát", ["Epistulam scribo.", "Píšu dopis.", "Odtud skripta, manuskript."]),
  v("lego", "legere, lēgī, lēctum", "číst", ["Discipuli libros legunt.", "Žáci čtou knihy.", "Odtud legenda – „co má být čteno“."]),
  v("mitto", "mittere, mīsī, missum", "posílat", ["Epistulam amico mitto.", "Posílám příteli dopis.", "Odtud mise, misionář, emise."]),
  v("vinco", "vincere, vīcī, victum", "vítězit", ["In hoc signo vinces.", "V tomto znamení zvítězíš.", "Vidění Konstantina Velikého před bitvou."]),
  v("curro", "currere, cucurrī, cursum", "běžet", ["Equi currunt.", "Koně běží.", "Odtud kurýr, kurz, kurzor."]),
  v("bibo", "bibere, bibī", "pít", ["Nunc est bibendum.", "Teď je třeba pít.", "Horatius po vítězství u Actia."]),
  v("capio", "capere, cēpī, captum", "brát, chytit", ["Milites oppidum capiunt.", "Vojáci dobývají městečko.", "Capere znamená i dobýt. Odtud kapacita."]),
  v("facio", "facere, fēcī, factum", "dělat", ["Feci, quod potui.", "Udělal jsem, co jsem mohl.", "Odtud fakt, faktura, fakulta."]),
  v("fugio", "fugere, fūgī", "utíkat", ["Fugit irreparabile tempus.", "Prchá nenávratný čas.", "Vergilius. Odtud fuga (hudební forma)."]),
  v("venio", "venīre, vēnī, ventum", "přijít", ["Veni, Creator Spiritus.", "Přijď, Duchu Stvořiteli.", "Odtud advent – příchod (ad-venire)."]),
  v("audio", "audīre, audīvī, audītum", "slyšet", ["Audi, vide, tace.", "Slyš, viz, mlč.", "Odtud audio, auditorium."]),
  v("dormio", "dormīre, dormīvī, dormītum", "spát", ["Infans dormit.", "Dítě spí.", "Odtud dormitář – společná ložnice v klášteře."]),
  v("scio", "scīre, scīvī, scītum", "vědět", ["Scio me nihil scire.", "Vím, že nic nevím.", "Latinský překlad Sókrata. Odtud scientia = věda."]),
  v("sum", "esse, fuī", "být", ["Cogito, ergo sum.", "Myslím, tedy jsem.", "Descartes. Nepravidelné: sum, es, est, sumus, estis, sunt."]),
  v("possum", "posse, potuī", "moci", ["Possum, sed nolo.", "Mohu, ale nechci.", "Složeno z potis + sum: pos-sum, pot-es, pot-est…"]),
  v("eo", "īre, iī, itum", "jít", ["In scholam eo.", "Jdu do školy.", "Nepravidelné: eo, is, it, imus, itis, eunt."]),
  v("volo", "velle, voluī", "chtít", ["Volens nolens", "Chtě nechtě", "Nolle = nechtít (ne + velle)."]),
  v("edo", "edere, ēdī, ēsum", "jíst", ["Edimus, ut vivamus, non vivimus, ut edamus.", "Jíme, abychom žili, nežijeme, abychom jedli."]),
  v("quaero", "quaerere, quaesīvī, quaesītum", "hledat, ptát se", ["Quaerite et invenietis.", "Hledejte a naleznete.", "Odtud kvestor – římský úředník, původně vyšetřovatel."]),
  v("ago", "agere, ēgī, āctum", "jednat, konat", ["Quidquid agis, prudenter agas.", "Ať děláš cokoli, dělej to rozvážně.", "Odtud agent, akce, aktivní."]),
  v("credo", "crēdere, crēdidī, crēditum", "věřit", ["Credo in unum Deum.", "Věřím v jednoho Boha.", "Odtud krédo, kredit."]),
  v("vivo", "vīvere, vīxī, vīctum", "žít", ["Dum vivimus, vivamus.", "Dokud žijeme, žijme.", "Vivat! = Ať žije!"]),
  // Přídavná jména
  a("bonus", "bona, bonum", "dobrý", ["Bonus pastor", "Dobrý pastýř", "Odtud bonus – „něco dobrého“ navíc."]),
  a("malus", "mala, malum", "špatný", ["Mala herba cito crescit.", "Plevel rychle roste.", "Neplést s mālum = jablko."]),
  a("magnus", "magna, magnum", "velký", ["Alexander Magnus", "Alexandr Veliký", "Odtud magnát."]),
  a("parvus", "parva, parvum", "malý", ["Parva domus, magna quies.", "Malý dům, velký klid."]),
  a("longus", "longa, longum", "dlouhý", ["Via longa est.", "Cesta je dlouhá.", "Odtud longituda – zeměpisná délka."]),
  a("altus", "alta, altum", "vysoký, hluboký", ["Citius, altius, fortius.", "Rychleji, výše, silněji.", "Olympijské heslo. Altus = vysoký i hluboký."]),
  a("novus", "nova, novum", "nový", ["Nihil novi sub sole.", "Nic nového pod sluncem.", "Kazatel. Odtud novic, inovace."]),
  a("antiquus", "antīqua, antīquum", "starobylý", ["Roma antiqua", "Starověký Řím", "Odtud antika, antikvariát."]),
  a("pulcher", "pulchra, pulchrum", "krásný", ["Puella pulchra est.", "Dívka je krásná.", "E v dalších tvarech mizí: pulcher, pulchra, pulchrum (jako ager, agrī)."]),
  a("liber", "lībera, līberum", "svobodný", ["Liber sum.", "Jsem svobodný.", "Neplést s liber, librī = kniha. Odtud liberální."]),
  a("miser", "misera, miserum", "ubohý", ["Miser servus", "Ubohý otrok", "Odtud mizerný, mizérie."]),
  a("laetus", "laeta, laetum", "radostný", ["Puer laetus est.", "Chlapec je radostný.", "Odtud jméno Laetitia (Letícia)."]),
  a("clarus", "clāra, clārum", "slavný, jasný", ["Vir clarus", "Slavný muž", "Odtud jméno Klára, klarinet."]),
  a("multus", "multa, multum", "mnohý", ["Multi sunt vocati, pauci vero electi.", "Mnoho je povolaných, ale málo vyvolených.", "Odtud multi- (multimédia)."]),
  a("plenus", "plēna, plēnum", "plný", ["Ave Maria, gratia plena", "Zdrávas Maria, milosti plná", "Odtud plénum."]),
  a("iustus", "iūsta, iūstum", "spravedlivý", ["Iustus ut palma florebit.", "Spravedlivý pokvete jako palma.", "Žalm 92. Odtud justice."]),
  a("fortis", "forte", "statečný, silný", ["Fortes fortuna adiuvat.", "Statečným štěstí pomáhá.", "Terentius. Odtud forte (silně, v hudbě)."]),
  a("brevis", "breve", "krátký", ["Brevis esse laboro, obscurus fio.", "Snažím se být stručný, a stávám se nejasným.", "Horatius. Odtud brevíř."]),
  a("omnis", "omne", "všechen, každý", ["Unus pro omnibus, omnes pro uno.", "Jeden za všechny, všichni za jednoho.", "Odtud omnibus – „pro všechny“."]),
  a("facilis", "facile", "snadný", ["Facilis descensus Averno.", "Snadný je sestup do podsvětí.", "Vergilius."]),
  a("difficilis", "difficile", "obtížný", ["Lingua Latina non difficilis est.", "Latina není těžká.", "Dif-ficilis = ne-snadný."]),
  a("celer", "celeris, celere", "rychlý", ["Celer ut ventus", "Rychlý jako vítr", "Odtud akcelerace."]),
  a("acer", "ācris, ācre", "ostrý, prudký", ["Acer hostis", "Prudký nepřítel", "Neplést s acer, aceris = javor."]),
  a("felix", "gen. fēlīcis", "šťastný", ["Felix culpa", "Šťastná vina", "Odtud jméno Felix."]),
  a("ingens", "gen. ingentis", "obrovský", ["Elephantus ingens est.", "Slon je obrovský."]),
  a("sapiens", "gen. sapientis", "moudrý", ["Sapiens omnia sua secum portat.", "Moudrý nosí vše své s sebou.", "Odtud Homo sapiens."]),
  a("dulcis", "dulce", "sladký", ["Dulce et decorum est pro patria mori.", "Sladké a čestné je zemřít za vlast.", "Horatius. Odtud dolce (v hudbě)."]),
  a("gravis", "grave", "těžký, vážný", ["Morbus gravis", "Těžká nemoc", "Odtud gravitace."]),
  a("tristis", "triste", "smutný", ["Puella tristis est.", "Dívka je smutná.", "Odtud tristní."]),
  a("vetus", "gen. veteris", "starý", ["Vetus Testamentum", "Starý zákon", "Odtud veterán."]),
  // Ostatní
  o("semper", "příslovce", "vždy", ["Semper fidelis.", "Vždy věrný.", "Heslo amerických mariňáků."]),
  o("numquam", "příslovce", "nikdy", ["Nunc aut numquam.", "Teď nebo nikdy.", "Ne + umquam (někdy)."]),
  o("saepe", "příslovce", "často", ["Gutta cavat lapidem non vi, sed saepe cadendo.", "Kapka vyhloubí kámen ne silou, ale častým padáním."]),
  o("hodie", "příslovce", "dnes", ["Hodie mihi, cras tibi.", "Dnes mně, zítra tobě.", "Nápis na náhrobcích. Hodie = hoc die (tohoto dne)."]),
  o("cras", "příslovce", "zítra", ["Cras, cras, semper cras.", "Zítra, zítra, pořád zítra.", "Odtud prokrastinace (pro-crastinus)."]),
  o("heri", "příslovce", "včera", ["Heri in schola fui.", "Včera jsem byl ve škole."]),
  o("nunc", "příslovce", "nyní", ["Nunc est bibendum.", "Teď je třeba pít.", "Horatius."]),
  o("iam", "příslovce", "již", ["Iam ver venit.", "Už přichází jaro."]),
  o("bene", "příslovce", "dobře", ["Bene vixit, qui bene latuit.", "Dobře žil, kdo se dobře skrýval.", "Ovidius. Odtud benefice."]),
  o("male", "příslovce", "špatně", ["Male parta male dilabuntur.", "Co se zle nabude, zle se rozplyne."]),
  o("non", "záporka", "ne", ["Non scholae, sed vitae discimus.", "Neučíme se pro školu, ale pro život.", "Seneca to původně napsal obráceně – jako výtku."]),
  o("et", "spojka", "a", ["Et tu, Brute?", "I ty, Brute?", "Et znamená a i také."]),
  o("sed", "spojka", "ale", ["Dura lex, sed lex.", "Tvrdý zákon, ale zákon."]),
  o("quod", "spojka", "protože", ["Gaudeo, quod venisti.", "Raduji se, že jsi přišel.", "Quod znamená protože i že."]),
  o("aut", "spojka", "nebo", ["Aut Caesar, aut nihil.", "Buď Caesar, nebo nic.", "Aut… aut = buď… nebo."]),
  o("cum", "předložka + abl.", "s", ["Dominus vobiscum.", "Pán s vámi.", "Za osobní zájmena se cum připojuje: mecum, tecum, vobiscum."]),
  o("sine", "předložka + abl.", "bez", ["Sine ira et studio.", "Bez hněvu a zaujatosti.", "Tacitus. Odtud sinekura (beneficium sine cura)."]),
  o("ad", "předložka + akuz.", "k, do", ["Per aspera ad astra.", "Přes překážky ke hvězdám."]),
  o("in", "předložka + akuz. / abl.", "do, v", ["In vino veritas.", "Ve víně je pravda.", "In + akuz. = kam (do), in + abl. = kde (v)."]),
  o("ex", "předložka + abl.", "z", ["Ex oriente lux.", "Světlo z východu.", "Před souhláskou často e: e pluribus unum."]),
  o("ubi", "tázací příslovce", "kde", ["Ubi bene, ibi patria.", "Kde je dobře, tam je vlast."]),
  o("cur", "tázací příslovce", "proč", ["Cur non venis?", "Proč nepřicházíš?"]),
  o("quis", "tázací zájmeno", "kdo", ["Quis custodiet ipsos custodes?", "Kdo bude hlídat samotné hlídače?", "Juvenalis."]),
  o("ego", "osobní zájmeno", "já", ["Ego te absolvo.", "Já tě rozhřešuji.", "Odtud ego, egoista."]),
  o("tu", "osobní zájmeno", "ty", ["Tu es Petrus.", "Ty jsi Petr."]),
  o("nos", "osobní zájmeno", "my", ["Ora pro nobis.", "Oroduj za nás.", "Nobis je dativ/ablativ od nos."]),
  o("unus", "číslovka", "jeden", ["E pluribus unum", "Z mnohých jeden", "Heslo na americké pečeti. Odtud unie."]),
  o("duo", "číslovka", "dva", ["Duo cum faciunt idem, non est idem.", "Když dva dělají totéž, není to totéž.", "Odtud duo, duel."]),
  o("tres", "číslovka", "tři", ["Tres faciunt collegium.", "Tři tvoří kolegium.", "Odtud trio."]),
  o("decem", "číslovka", "deset", ["Decem praecepta", "Deset přikázání", "December byl původně 10. měsíc (rok začínal březnem)."]),
  o("mille", "číslovka", "tisíc", ["Mille passus", "Tisíc kroků", "Tolik měřila římská míle. Odtud milimetr, milion."]),
]);
