import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 2", [
  o("ab", "předložka + abl. (ā, ab, abs)", "od, z", ["A Domino factum est istud.", "Od Hospodina se to stalo.", "Ž 118,23. Před souhláskou ā, před samohláskou ab."]),
  v("accipio", "accipere, accēpī, acceptum", "přijímám, beru, dostávám", ["Accipite et manducate.", "Vezměte a jezte.", "Slova proměňování při mši. Odtud akceptovat."]),
  o("amen", "citoslovce (hebr.)", "opravdu, staň se, amen", ["Amen dico vobis.", "Amen, pravím vám.", "Hebrejské slovo, které Ježíš často používá na začátku výroku."]),
  o("ave", "rozkaz. způsob (avēte)", "buď zdráv, vítej", ["Ave, Caesar!", "Buď zdráv, Caesare!", "Stejně začíná Zdrávas Maria: Ave Maria."]),
  a("benedictus", "benedicta, benedictum", "požehnaný, blahořečený", ["Benedictus qui venit in nomine Domini.", "Požehnaný, který přichází ve jménu Páně.", "Ž 118,26; zpívá se při mši po Sanctus."]),
  a("caecus", "caeca, caecum", "slepý", ["Caecus caecum ducit.", "Slepý vede slepého.", "Podle Mt 15,14. Odtud caecum – slepé střevo."]),
  n("colloquium", "colloquiī n.", "rozmluva, rozhovor", ["Colloquium amicorum longum erat.", "Rozhovor přátel byl dlouhý.", "Odtud kolokvium – rozprava, zkouška formou rozhovoru."]),
  a("cotidianus", "cotīdiāna, cotīdiānum", "každodenní, denní, všední", ["Panem nostrum cotidianum da nobis hodie.", "Chléb náš vezdejší dej nám dnes.", "Z modlitby Otče náš."]),
  n("cultus", "cultūs m.", "péče, uctívání, bohoslužba", ["Cultus Dei", "Uctívání Boha", "Od colere (pěstovat, ctít). Odtud kult, kultura."]),
  n("debitor", "dēbitōris m.", "dlužník; viník, hříšník", ["Debitor pecuniam non reddit.", "Dlužník nevrací peníze.", "Odtud debitor v účetnictví."]),
  n("debitum", "dēbitī n.", "dluh, závazek, vina", ["Debitum solvere debeo.", "Musím splatit dluh.", "Odtud debet."]),
  v("dimitto", "dīmittere, dīmīsī, dīmissum", "propouštím, odpouštím", ["Dimitte nobis debita nostra.", "Odpusť nám naše dluhy.", "Doslova: propusť. Od mitto (posílám)."]),
  n("exemplum", "exemplī n.", "příklad, vzor, ukázka", ["Exempla trahunt.", "Příklady táhnou.", "Odtud exemplář, exemplární."]),
  n("facultas", "facultātis f.", "možnost, schopnost; fakulta", ["Facultas theologica", "Teologická fakulta", "Odtud fakulta – původně schopnost, obor."]),
  a("falsus", "falsa, falsum", "klamný, nepravdivý, falešný", ["Testimonium falsum non dices.", "Nevydáš křivé svědectví.", "Podle Desatera. Odtud falešný, falzifikát."]),
  n("femina", "fēminae f.", "žena", ["Femina in horto laborat.", "Žena pracuje na zahradě.", "Odtud feminismus, femininum."]),
  v("fio", "fierī, factus sum", "stávám se, vznikám", ["Fit via vi.", "Cesta se prorazí silou.", "Nepravidelné sloveso; slouží i jako trpný rod k facio."]),
  n("gratia", "grātiae f.", "vděk, dík, půvab; milost", ["Ave, gratia plena.", "Zdrávas, milosti plná.", "Gratias ago = děkuji. Odtud gratulace, gratis."]),
  v("induco", "indūcere, indūxī, inductum", "uvádím, přivádím", ["Et ne nos inducas in tentationem.", "A neuveď nás v pokušení.", "Z modlitby Otče náš. Odtud indukce."]),
  a("iniustus", "iniūsta, iniūstum", "nespravedlivý", ["Iudex iniustus pecuniam amat.", "Nespravedlivý soudce miluje peníze.", "In- = ne-, iustus = spravedlivý."]),
  o("intra", "předložka + akuz.", "uvnitř, dovnitř; během", ["Intra muros urbis", "Uvnitř městských hradeb", "Odtud intravenózní (do žíly), intranet."]),
  n("littera", "litterae f.", "písmeno; písmo", ["Littera occidit, spiritus autem vivificat.", "Litera zabíjí, ale duch oživuje.", "2 Kor 3,6. V pl. litterae i dopis. Odtud literatura."]),
  n("malum", "malī n.", "zlo, špatnost, neřest", ["Noli vinci a malo.", "Nedej se přemoci zlem.", "Neplést s mālum = jablko."]),
  v("misereor", "miserērī, miseritus sum (+ gen.)", "smilovávám se nad někým", ["Misereor super turbam.", "Je mi líto zástupu.", "Mk 8,2. Odtud Miserere – smiluj se."]),
  o("ne", "záporka (u rozk. a konj.)", "ne, ať ne, kéž ne", ["Ne timueritis!", "Nebojte se!", "Zákaz se tvoří ne + konjunktiv perfekta."]),
  n("ordo", "ōrdinis m.", "řada, řád, pořádek; stav", ["Ordo Missae", "Mešní řád", "Odtud ordinace, řeholní řád = ordo."]),
  n("passus", "passūs m.", "krok; dvojkrok (míra)", ["Passus magnos facit.", "Dělá velké kroky.", "Dvojkrok měřil asi 1,48 m. Neplést s příčestím passus (trpěvší)."]),
  n("peccator", "peccātōris m.", "hříšník", ["Ora pro nobis peccatoribus.", "Pros za nás hříšné.", "Ze Zdrávas Maria."]),
  n("philosophus", "philosophī m.", "filozof", ["Socrates philosophus erat.", "Sókratés byl filozof.", "Z řečtiny: milovník moudrosti."]),
  a("proprius", "propria, proprium", "vlastní", ["Nomen proprium", "Vlastní jméno", "Odtud anglické property – vlastnictví."]),
  o("qui", "zájmeno vztažné (quae, quod)", "který, jenž, kdo", ["Qui tacet, consentire videtur.", "Kdo mlčí, zdá se, že souhlasí."]),
  n("repetitio", "repetītiōnis f.", "opakování", ["Repetitio est mater studiorum.", "Opakování je matkou učení.", "Odtud repetice, repetent."]),
  a("sacer", "sacra, sacrum", "posvátný, svatý", ["Sacra Scriptura", "Písmo svaté", "Odtud sakrální, sakristie."]),
  v("sanctifico", "sānctificāre, sānctificāvī, sānctificātum", "posvěcuji", ["Sanctificetur nomen tuum.", "Posvěť se jméno tvé.", "Z modlitby Otče náš."]),
  a("sanctus", "sāncta, sānctum", "svatý, posvěcený", ["Sanctus, sanctus, sanctus Dominus Deus.", "Svatý, svatý, svatý Pán Bůh.", "Iz 6,3. Odtud sanktuarium."]),
  o("sicut", "spojka", "tak jako, stejně jako", ["Sicut erat in principio.", "Jako bylo na počátku.", "Ze Sláva Otci."]),
  n("spiritus", "spīritūs m.", "duch; dech, vánek", ["Spiritus ubi vult spirat.", "Duch vane, kam chce.", "Jan 3,8. Odtud spiritismus, spirituál."]),
  a("suus", "sua, suum", "svůj", ["Suum cuique.", "Každému, co mu patří.", "Zásada římského práva."]),
  n("tentatio", "tentātiōnis f. (i temptātiō)", "pokušení, zkouška", ["Ut non intretis in tentationem.", "Abyste nepřišli do pokušení.", "Mt 26,41."]),
  a("totus", "tōta, tōtum (gen. tōtīus)", "celý, všechen", ["Totus tuus", "Celý tvůj", "Heslo papeže Jana Pavla II. Odtud totální."]),
  n("venter", "ventris m.", "břicho; mateřský život", ["Benedictus fructus ventris tui.", "Požehnaný plod života tvého.", "Ze Zdrávas Maria. Odtud ventrikulus – komora."]),
  n("voluntas", "voluntātis f.", "vůle, přání, úmysl", ["Hominibus bonae voluntatis", "Lidem dobré vůle", "Z Gloria (Lk 2,14). Od volo (chci)."]),
  n("acies", "aciēī f.", "ostří, bystrost; šik", ["Acies militum stat.", "Šik vojáků stojí.", "Pátá deklinace, ženský rod."]),
  n("amica", "amīcae f.", "přítelkyně", ["Amica mea venit.", "Moje přítelkyně přichází."]),
  v("appello", "appellāre, appellāvī, appellātum", "nazývám, oslovuji", ["Caesarem appello.", "Odvolávám se k Caesarovi.", "Sk 25,11. Odtud apel, apelace."]),
  v("benedico", "benedīcere, benedīxī, benedictum", "dobrořečím, žehnám", ["Benedicat vos omnipotens Deus.", "Ať vás žehná všemohoucí Bůh.", "Bene + dico = dobře mluvím. Odtud benedikce."]),
  n("benedictio", "benedictiōnis f.", "dobrořečení; požehnání", ["Benedictio Dei super vos.", "Boží požehnání nad vámi.", "Odtud benedikce."]),
  n("caro", "carnis f.", "maso, tělo", ["Et Verbum caro factum est.", "A Slovo se stalo tělem.", "Jan 1,14. Odtud karneval, inkarnace."]),
  v("concipio", "concipere, concēpī, conceptum", "chápu; počínám", ["Ecce virgo concipiet.", "Hle, panna počne.", "Iz 7,14. Odtud koncept, koncepce."]),
  n("cornu", "cornūs n.", "roh; křídlo šiku", ["Taurus cornua habet.", "Býk má rohy.", "Unicornis = jednorožec."]),
  n("crux", "crucis f.", "kříž; trápení", ["O crux, ave, spes unica.", "Zdrávas, kříži, jediná naděje.", "Z hymnu Vexilla regis. Odtud krucifix."]),
  n("currus", "currūs m.", "vůz, povoz", ["Currus celeriter currit.", "Vůz rychle jede.", "Příbuzné s curro (běžím)."]),
  v("deleo", "dēlēre, dēlēvī, dēlētum", "ničím, hubím, vyhlazuji", ["Carthago delenda est.", "Kartágo musí být zničeno.", "Výrok Catona st. Odtud anglické delete."]),
  a("dignus", "digna, dignum", "důstojný, hodný", ["Domine, non sum dignus.", "Pane, nejsem hoden.", "Mt 8,8; říká se před přijímáním. Odtud důstojnost = dignitas."]),
  n("ecclesia", "ecclēsiae f.", "církev; shromáždění; kostel", ["Credo in unam sanctam ecclesiam.", "Věřím v jednu svatou církev.", "Z Kréda. Z řečtiny: shromáždění."]),
  v("educo", "ēducāre, ēducāvī, ēducātum", "vychovávám, pěstuji", ["Mater filios bene educat.", "Matka dobře vychovává děti.", "Neplést s ēdūcō = vyvádím. Odtud edukace."]),
  v("efficio", "efficere, effēcī, effectum", "způsobuji, vytvářím", ["Labor magna efficit.", "Práce dokáže velké věci.", "Odtud efekt, efektivní."]),
  v("exsulto", "exsultāre, exsultāvī, exsultātum", "jásám, plesám", ["Exsultet iam angelica turba caelorum.", "Ať již jásá andělský sbor nebes.", "Začátek velikonočního chvalozpěvu Exsultet."]),
  n("forma", "fōrmae f.", "tvar, vzhled, podoba", ["Forma servi", "Podoba služebníka", "Flp 2,7. Odtud forma, formulář."]),
  n("fortunae", "fortūnārum f. (pl.)", "statky, majetek", ["Fortunas suas pauperibus dedit.", "Svůj majetek dal chudým.", "V jednotném čísle fortuna = štěstí, osud."]),
  n("genus", "generis n.", "rod, původ, pokolení", ["Genus humanum", "Lidský rod", "Odtud generace, gen."]),
  n("historia", "historiae f.", "dějiny, historie", ["Historia magistra vitae.", "Dějiny jsou učitelkou života.", "Cicero."]),
  n("honor", "honōris m. (i honōs)", "čest, úcta, úřad", ["Honor et gloria", "Čest a sláva", "Odtud honorář, honorace."]),
  v("impero", "imperāre, imperāvī, imperātum", "rozkazuji, velím, vládnu", ["Imperat ventis et mari.", "Poroučí větrům i moři.", "Podle Mt 8,26. Odtud imperátor, imperativ."]),
  n("incarnatio", "incarnātiōnis f.", "vtělení", ["Mysterium incarnationis", "Tajemství vtělení", "Od caro, carnis (tělo)."]),
  n("iustitia", "iūstitiae f.", "spravedlnost", ["Fiat iustitia, pereat mundus.", "Ať se stane spravedlnost, i kdyby zahynul svět.", "Heslo císaře Ferdinanda I. Odtud justice."]),
  n("laetitia", "laetitiae f.", "radost, veselí", ["Laetitia magna in domo erat.", "V domě panovala velká radost.", "Odtud jméno Letícia."]),
  n("magistra", "magistrae f.", "učitelka; představená", ["Magistra pueros docet.", "Učitelka učí děti."]),
  n("mens", "mentis f.", "mysl, rozum, úmysl", ["Mens agitat molem.", "Duch pohání hmotu.", "Vergilius. Odtud mentalita, mentální."]),
  n("modus", "modī m.", "míra, způsob; nápěv", ["Modus vivendi", "Způsob soužití", "Odtud móda, modální."]),
  a("mysticus", "mystica, mysticum", "tajemný, mystický", ["Corpus Christi mysticum", "Tajemné tělo Kristovo", "Odtud mystika."]),
  o("nisi", "spojka", "jestliže ne; leda, než", ["Nisi Dominus aedificaverit domum…", "Jestliže Hospodin nestaví dům…", "Žalm 127,1."]),
  v("nomino", "nōmināre, nōmināvī, nōminātum", "jmenuji, nazývám", ["Puerum Petrum nominant.", "Chlapce jmenují Petr.", "Odtud nominace, nominativ."]),
  v("nuntio", "nūntiāre, nūntiāvī, nūntiātum", "oznamuji, zvěstuji", ["Angelus Domini nuntiavit Mariae.", "Anděl Páně zvěstoval Panně Marii.", "Začátek modlitby Anděl Páně. Odtud nuncius."]),
  v("orno", "ōrnāre, ōrnāvī, ōrnātum", "zdobím, strojím", ["Templum floribus ornant.", "Zdobí chrám květinami.", "Odtud ornament."]),
  n("paenitentia", "paenitentiae f.", "lítost, pokání", ["Agite paenitentiam!", "Čiňte pokání!", "Mt 3,2. Odtud penitence."]),
  n("patriarcha", "patriarchae m.", "praotec, patriarcha", ["Abraham patriarcha", "Praotec Abrahám", "Mužský rod, i když končí na -a."]),
  n("persona", "persōnae f.", "osoba; maska", ["Tres personae, unus Deus", "Tři osoby, jeden Bůh", "Původně divadelní maska. Odtud personál."]),
  a("pius", "pia, pium", "zbožný, oddaný, laskavý", ["Pie Iesu, dona eis requiem.", "Dobrotivý Ježíši, dej jim odpočinutí.", "Ze sekvence Dies irae. Odtud pieta."]),
  n("principium", "prīncipiī n.", "počátek, základ, princip", ["In principio erat Verbum.", "Na počátku bylo Slovo.", "Jan 1,1. Odtud princip."]),
  n("promissio", "prōmissiōnis f.", "slib, zaslíbení", ["Terra promissionis", "Země zaslíbená", "Odtud anglické promise."]),
  n("propheta", "prophētae m.", "prorok", ["Nemo propheta in patria.", "Nikdo není prorokem ve své vlasti.", "Podle Lk 4,24. Mužský rod."]),
  n("prudentia", "prūdentiae f.", "prozíravost, moudrost", ["Prudentia est mater virtutum.", "Rozvážnost je matkou ctností.", "Jedna ze čtyř základních ctností."]),
  n("regina", "rēgīnae f.", "královna", ["Regina caeli, laetare!", "Královno nebes, raduj se!", "Velikonoční mariánská antifona."]),
  n("resurrectio", "resurrēctiōnis f.", "zmrtvýchvstání, vzkříšení", ["Exspecto resurrectionem mortuorum.", "Očekávám vzkříšení mrtvých.", "Z Kréda."]),
  a("sacratus", "sacrāta, sacrātum", "posvěcený, svatý", ["Locus sacratus", "Posvěcené místo", "Příčestí od sacro (posvěcuji)."]),
  n("saeculum", "saeculī n.", "věk, století; svět", ["In saecula saeculorum.", "Na věky věků.", "Odtud sekulární – světský."]),
  o("satis", "příslovce (i sat)", "dost, dostatečně", ["Satis est.", "Stačí.", "Odtud satisfakce (satis + facere)."]),
  o("secundum", "předložka + akuz.", "podle, vedle, hned po", ["Secundum verbum tuum.", "Podle tvého slova.", "Lk 1,38."]),
  a("secundus", "secunda, secundum", "druhý; příznivý", ["Secunda pars", "Druhá část", "Odtud sekunda – druhé dělení hodiny."]),
  v("spero", "spērāre, spērāvī, spērātum", "doufám, očekávám", ["Dum spiro, spero.", "Dokud dýchám, doufám.", "Odtud esperanto."]),
  o("super", "předložka + akuz.", "nad, na, přes, kromě", ["Pax super Israel.", "Pokoj nad Izraelem.", "Ž 125,5. Odtud super-."]),
  n("tenebrae", "tenebrārum f. (pl.)", "tma, temnota", ["Lux in tenebris lucet.", "Světlo ve tmě svítí.", "Jan 1,5. Jen v pl."]),
  n("trinitas", "trīnitātis f.", "trojice", ["Sancta Trinitas, unus Deus", "Svatá Trojice, jeden Bůh", "Od trinus (trojí)."]),
  n("triumphus", "triumphī m.", "triumf, vítězný průvod", ["Triumphus imperatoris", "Vojevůdcův triumf", "Odtud triumf."]),
  n("victor", "victōris m.", "vítěz", ["Christus victor", "Kristus vítěz", "Od vinco (vítězím). Odtud jméno Viktor."]),
  v("vigilo", "vigilāre, vigilāvī, vigilātum", "bdím", ["Vigilate et orate.", "Bděte a modlete se.", "Mt 26,41. Odtud vigilie."]),
  n("virgo", "virginis f.", "panna, dívka", ["Virgo Maria", "Panna Maria", "Odtud souhvězdí Panna = Virgo."]),
  a("aeternus", "aeterna, aeternum", "věčný, nesmrtelný", ["Requiem aeternam dona eis, Domine.", "Odpočinutí věčné dej jim, Pane.", "Odtud eternita."]),
  v("agnosco", "agnōscere, agnōvī, agnitum", "poznávám, uznávám", ["Agnosce, christiane, dignitatem tuam.", "Poznej, křesťane, svou důstojnost.", "Lev Veliký. Odtud agnostik (z řečtiny)."]),
  n("agnus", "agnī m.", "jehně, beránek", ["Ecce Agnus Dei.", "Hle, Beránek Boží.", "Jan 1,29."]),
  a("alienus", "aliēna, aliēnum", "cizí, jiný", ["Nihil humani a me alienum puto.", "Nic lidského mi není cizí.", "Terentius. Odtud alienace."]),
  a("aptus", "apta, aptum", "vhodný, připravený", ["Aptus ad laborem", "Schopný práce", "Odtud adaptace."]),
  n("argumentum", "argūmentī n.", "důkaz, důvod, obsah", ["Argumentum validum", "Pádný důkaz", "Odtud argument."]),
  a("aridus", "ārida, āridum", "suchý, vyprahlý", ["Terra arida est.", "Země je vyprahlá.", "Odtud aridní (suché) podnebí."]),
  n("arma", "armōrum n. pl.", "zbraně, zbroj", ["Arma virumque cano.", "Zpívám o zbraních a muži.", "Začátek Vergiliovy Aeneidy. Jen v pl."]),
  o("atque", "spojka (zkr. ac)", "a, i, a také", ["Semel atque iterum", "Jednou i podruhé", "Před souhláskou často zkráceno na ac."]),
  a("beatus", "beāta, beātum", "blažený, šťastný", ["Beati pauperes spiritu.", "Blahoslavení chudí v duchu.", "Mt 5,3. Odtud beatifikace."]),
  n("canticum", "canticī n.", "píseň, zpěv", ["Canticum canticorum", "Píseň písní", "Starozákonní kniha. Od cano (zpívám)."]),
  n("castra", "castrōrum n. pl.", "tábor, ležení", ["Milites in castris manent.", "Vojáci zůstávají v táboře.", "Jen v pl. Odtud anglické -chester."]),
  o("circa", "předložka + akuz.; příslovce", "kolem, okolo", ["Circa urbem", "Kolem města", "Odtud cirka – přibližně."]),
  a("clemens", "gen. clēmentis", "mírný, laskavý", ["O clemens, o pia!", "Ó milostivá, ó dobrotivá!", "Ze Zdrávas Královno. Odtud jméno Klement."]),
  n("cogitatio", "cōgitātiōnis f.", "myšlení, myšlenka", ["Peccavi cogitatione, verbo et opere.", "Zhřešil jsem myšlením, slovem i skutkem.", "Z Confiteor."]),
  v("committo", "committere, commīsī, commissum", "spojuji, páchám, svěřuji", ["Crimen committit.", "Páchá zločin.", "Odtud komise, komisař."]),
  v("confiteor", "cōnfitērī, cōnfessus sum", "vyznávám, přiznávám", ["Confiteor Deo omnipotenti.", "Vyznávám se Bohu všemohoucímu.", "Začátek vyznání hříchů. Odtud konfese."]),
  o("coram", "předložka + abl.; příslovce", "před, v přítomnosti", ["Coram Deo", "Před Bohem", "Užívá se i coram publico – veřejně."]),
  n("decalogus", "decalogī m.", "desatero", ["Decalogus decem praecepta continet.", "Desatero obsahuje deset přikázání.", "Z řečtiny: deset slov."]),
  n("desertum", "dēsertī n.", "poušť, pustina", ["Vox clamantis in deserto.", "Hlas volajícího na poušti.", "Iz 40,3. Odtud dezertér."]),
  n("dextera", "dexterae f.", "pravice", ["Sedet ad dexteram Patris.", "Sedí po pravici Otce.", "Z Kréda. Odtud anglické dexterity."]),
  n("discipulus", "discipulī m.", "žák, učedník", ["Discipulus magistrum audit.", "Žák poslouchá učitele.", "Od disco (učím se). Odtud disciplína."]),
  n("dominica", "dominicae f.", "den Páně, neděle", ["Dominica est dies Domini.", "Neděle je den Páně.", "Odtud italské domenica."]),
  v("fleo", "flēre, flēvī, flētum", "pláču, naříkám", ["Puer flet.", "Chlapec pláče."]),
  v("gemo", "gemere, gemuī, gemitum", "lkám, sténám", ["Ad te suspiramus, gementes et flentes.", "K tobě vzdycháme, lkajíce a plačíce.", "Ze Zdrávas Královno."]),
  n("humus", "humī f.", "země, půda", ["Humus fertilis", "Úrodná půda", "Ženský rod, i když končí na -us. Odtud humus."]),
  o("ideo", "příslovce", "proto", ["Ideo precor beatam Mariam.", "Proto prosím blahoslavenou Marii.", "Z Confiteor."]),
  o("ille", "illa, illud (zájmeno)", "onen, on", ["Ille venit.", "On přichází.", "Odtud členy v románských jazycích (il, le, el)."]),
  n("imperium", "imperiī n.", "rozkaz, vláda, moc", ["Imperium Romanum", "Římská říše", "Odtud impérium, imperialismus."]),
  v("interpello", "interpellāre, interpellāvī, interpellātum", "přerušuji, zastávám se", ["Semper vivit ad interpellandum pro nobis.", "Stále žije, aby se za nás přimlouval.", "Podle Žd 7,25. Odtud interpelace."]),
  v("interrogo", "interrogāre, interrogāvī, interrogātum", "ptám se, vyslýchám", ["Magister discipulum interrogat.", "Učitel zkouší žáka.", "Odtud interogativní (tázací)."]),
  n("lacrima", "lacrimae f.", "slza", ["In hac lacrimarum valle", "V tomto slzavém údolí", "Ze Zdrávas Královno."]),
  n("mandatum", "mandātī n.", "přikázání, příkaz", ["Mandatum novum do vobis.", "Nové přikázání vám dávám.", "Jan 13,34. Odtud mandát."]),
  a("minimus", "minima, minimum", "nejmenší", ["Uni ex his fratribus meis minimis", "Jednomu z těchto mých nejmenších bratří", "Mt 25,40. Superlativ k parvus. Odtud minimum."]),
  n("misericordia", "misericordiae f.", "milosrdenství", ["Misericordia Domini in aeternum.", "Milosrdenství Páně navěky.", "Od miser + cor = srdce pro ubohé."]),
  v("morior", "morī, mortuus sum", "umírám", ["Morituri te salutant.", "Jdoucí na smrt tě zdraví.", "Pozdrav gladiátorů císaři. Odtud mortalita."]),
  n("mysterium", "mystēriī n.", "tajemství", ["Mysterium fidei", "Tajemství víry", "Zvolání při mši po proměňování."]),
  o("nimis", "příslovce", "příliš, velmi", ["Peccavi nimis.", "Velmi jsem zhřešil.", "Z Confiteor. Ne quid nimis = nic přespříliš."]),
  n("omissio", "omissiōnis f.", "opomenutí, zanedbání", ["Peccatum omissionis", "Hřích opomenutí", "Odtud anglické omission."]),
  a("omnipotens", "gen. omnipotentis", "všemohoucí", ["Credo in Deum, Patrem omnipotentem.", "Věřím v Boha, Otce všemohoucího.", "Omnis + potens."]),
  v("ostendo", "ostendere, ostendī, ostentum", "ukazuji, dokazuji", ["Iesum nobis post hoc exsilium ostende.", "Ježíše nám po tomto vyhnanství ukaž.", "Ze Zdrávas Královno. Odtud ostentativní."]),
  n("peccatum", "peccātī n.", "hřích, provinění", ["Agnus Dei, qui tollis peccata mundi.", "Beránku Boží, který snímáš hříchy světa."]),
  v("pecco", "peccāre, peccāvī, peccātum", "hřeším", ["Pater, peccavi in caelum.", "Otče, zhřešil jsem proti nebi.", "Lk 15,18."]),
  n("praeceptum", "praeceptī n.", "příkaz, rada", ["Praecepta patris servo.", "Zachovávám otcovy rady.", "Odtud anglické precept."]),
  v("precor", "precārī, precātus sum", "prosím, modlím se", ["Precor te, Domine.", "Prosím tě, Pane.", "Odtud prekérní – původně získaný prosbou."]),
  o("quia", "spojka", "protože", ["Credo quia absurdum.", "Věřím, protože je to nesmyslné.", "Výrok připisovaný Tertullianovi."]),
  o("quoniam", "spojka", "protože, neboť", ["Quoniam tu solus sanctus.", "Neboť ty jediný jsi svatý.", "Z Gloria."]),
  a("salutaris", "salūtāre", "léčivý, spasitelný", ["O salutaris hostia", "Ó spasitelná oběti", "Eucharistický hymnus sv. Tomáše Akvinského."]),
  o("salve", "pozdrav (pl. salvēte)", "buď zdráv, vítej", ["Salve, Regina!", "Zdrávas, Královno!", "Mariánská antifona. Pl. salvete = buďte zdrávi."]),
  v("salveo", "salvēre", "jsem zdráv", ["Salvere iubeo.", "Pozdravuji (doslova: velím být zdráv).", "Běžně jen salve, salvete."]),
  v("sano", "sānāre, sānāvī, sānātum", "uzdravuji, léčím", ["Sana me, Domine.", "Uzdrav mě, Pane.", "Odtud sanatorium."]),
  o("se", "zvratné zájmeno (suī, sibi)", "sebe, se", ["Qui se humiliat, exaltabitur.", "Kdo se ponižuje, bude povýšen.", "Lk 14,11. Nemá nominativ."]),
  v("sequor", "sequī, secūtus sum", "následuji, sleduji", ["Sequere me.", "Následuj mě.", "Mt 9,9. Odtud sekvence, konsekvence."]),
  o("sero", "příslovce", "pozdě", ["Sero te amavi.", "Pozdě jsem tě miloval.", "Augustin, Vyznání X,27."]),
  v("studeo", "studēre, studuī (+ dat.)", "snažím se, zabývám se", ["Linguae Latinae studeo.", "Studuji latinu.", "Pojí se s dativem. Odtud student, studium."]),
  v("suspiro", "suspīrāre, suspīrāvī, suspīrātum", "vzdychám, toužím", ["Ad te suspiramus.", "K tobě vzdycháme.", "Ze Zdrávas Královno."]),
  o("tertius", "tertia, tertium (číslovka)", "třetí", ["Tertia die resurrexit.", "Třetího dne vstal z mrtvých.", "Z Kréda. Odtud tercie, terciář."]),
  a("verus", "vēra, vērum", "pravý, pravdivý", ["Deum verum de Deo vero", "Boha pravého z Boha pravého", "Z Kréda. Odtud verifikace."]),
  a("vester", "vestra, vestrum", "váš", ["Pater vester caelestis", "Váš nebeský Otec", "Mt 6,14."]),
  o("vos", "osobní zájmeno (vestrī, vōbīs)", "vy", ["Pax vobis.", "Pokoj vám.", "Jan 20,19. Vobiscum = cum vobis."]),
  n("aestas", "aestātis f.", "léto", ["Aestate dies longi sunt.", "V létě jsou dny dlouhé."]),
  n("animal", "animālis n.", "živočich, zvíře", ["Homo est animal rationale.", "Člověk je rozumný živočich.", "Aristotelská definice člověka. Odtud animální."]),
  n("baptisma", "baptismatis n.", "křest", ["Confiteor unum baptisma.", "Vyznávám jeden křest.", "Z Kréda. Z řečtiny: ponoření."]),
  a("caelestis", "caeleste", "nebeský", ["Pater caelestis", "Nebeský Otec", "Od caelum (nebe)."]),
  n("caritas", "cāritātis f.", "láska, úcta", ["Ubi caritas et amor, Deus ibi est.", "Kde je láska a dobrota, tam je Bůh.", "Zpěv Zeleného čtvrtku. Odtud charita."]),
  n("civitas", "cīvitātis f.", "obec, občanství", ["De civitate Dei", "O obci Boží", "Spis sv. Augustina. Odtud civilizace."]),
  n("communicatio", "commūnicātiōnis f.", "sdělení, společenství", ["Communicatio Spiritus Sancti", "Společenství Ducha Svatého", "2 Kor 13,13. Odtud komunikace."]),
  v("concedo", "concēdere, concessī, concessum", "ustupuji, dovoluji", ["Concede nobis pacem.", "Dopřej nám pokoj.", "Odtud koncese."]),
  v("corrigo", "corrigere, corrēxī, corrēctum", "opravuji, napravuji", ["Errata corrigo.", "Opravuji chyby.", "Odtud korekce, korektor."]),
  a("cunctus", "cūncta, cūnctum", "veškerý, všechen", ["Cuncta creavit Deus.", "Bůh stvořil všechno."]),
  v("custodio", "custōdīre, custōdīvī, custōdītum", "hlídám, střežím", ["Custodi nos, Domine.", "Ochraňuj nás, Pane.", "Odtud anglické custody."]),
  v("defendo", "dēfendere, dēfendī, dēfēnsum", "hájím, bráním", ["Defende nos in proelio.", "Braň nás v boji.", "Z modlitby k sv. Michaelovi. Odtud defenzíva."]),
  n("dens", "dentis m.", "zub", ["Oculum pro oculo, dentem pro dente", "Oko za oko, zub za zub", "Ex 21,24. Odtud dentista."]),
  n("deprecatio", "dēprecātiōnis f.", "prosba, přímluva", ["Exaudi deprecationem meam.", "Vyslyš mou prosbu.", "Odtud deprekace."]),
  v("diligo", "dīligere, dīlēxī, dīlēctum", "miluji, vážím si", ["Diliges proximum tuum sicut te ipsum.", "Budeš milovat bližního jako sebe.", "Mt 22,39. Odtud diligentní – pečlivý."]),
  a("divinus", "dīvīna, dīvīnum", "božský, boží", ["Divina misericordia", "Boží milosrdenství"]),
  v("exaudio", "exaudīre, exaudīvī, exaudītum", "vyslyším, slyším", ["Domine, exaudi orationem meam.", "Pane, vyslyš mou modlitbu.", "Ž 102,2."]),
  n("exemplar", "exemplāris n.", "vzor, obraz", ["Exemplar virtutis", "Vzor ctnosti", "Odtud exemplář."]),
  v("fallo", "fallere, fefellī, falsum", "klamu, podvádím", ["Spes me fefellit.", "Naděje mě zklamala.", "Příčestí falsus – odtud falešný."]),
  v("finio", "fīnīre, fīnīvī, fīnītum", "končím, omezuji", ["Opus finitum est.", "Dílo je dokončeno.", "Odtud finiš, definice."]),
  n("fons", "fontis m.", "pramen, zdroj", ["Fons vitae", "Pramen života", "Odtud fontána."]),
  n("generatio", "generātiōnis f.", "pokolení, plození", ["A generatione in generationem", "Z pokolení na pokolení", "Odtud generace."]),
  v("glorifico", "glōrificāre, glōrificāvī, glōrificātum", "oslavuji", ["Glorificamus te.", "Velebíme tě.", "Z hymnu Gloria."]),
  n("imago", "imāginis f.", "obraz, podoba", ["Ad imaginem Dei creavit illum.", "K obrazu Božímu jej stvořil.", "Gn 1,27. Odtud imaginace."]),
  v("impleo", "implēre, implēvī, implētum", "naplňuji", ["Imple superna gratia.", "Naplň nebeskou milostí.", "Z hymnu Veni Creator Spiritus."]),
  n("iter", "itineris n.", "pochod, cesta", ["Iter longum est.", "Cesta je dlouhá.", "Odtud itinerář."]),
  n("ius", "iūris n.", "právo", ["Summum ius, summa iniuria.", "Nejvyšší právo, nejvyšší bezpráví.", "Cicero. Odtud justice, jurista."]),
  n("iuvenis", "iuvenis m.", "mladík", ["Iuvenes et virgines laudent nomen Domini.", "Mladíci a panny ať chválí jméno Páně.", "Žalm 148,12. Odtud juvenilní."]),
  n("lumen", "lūminis n.", "světlo", ["Lumen de lumine", "Světlo ze světla", "Z Kréda."]),
  n("mos", "mōris m.", "mrav, zvyk", ["O tempora, o mores!", "Ó časy, ó mravy!", "Cicero. Odtud morálka."]),
  v("mundo", "mundāre, mundāvī, mundātum", "čistím, očišťuji", ["Munda cor meum.", "Očisť mé srdce.", "Z modlitby kněze před evangeliem."]),
  n("mundus", "mundī m.", "svět, vesmír", ["Agnus Dei, qui tollis peccata mundi", "Beránku Boží, který snímáš hříchy světa", "Z mše. Neplést s mundus, a, um = čistý."]),
  n("oratio", "ōrātiōnis f.", "řeč, modlitba", ["Oratio dominica", "Modlitba Páně", "Odtud orace, oratoř."]),
  n("orbis", "orbis m.", "kruh, svět", ["Orbis terrarum", "Okruh zemí, svět", "Odtud orbita."]),
  n("ōs", "ōris n.", "ústa, tvář", ["Ore et corde", "Ústy i srdcem", "Neplést s os, ossis = kost. Odtud orální."]),
  n("os", "ossis n.", "kost", ["Os ex ossibus meis", "Kost z mých kostí", "Gn 2,23. Neplést s ōs, ōris = ústa."]),
  n("pastor", "pastōris m.", "pastýř", ["Ego sum pastor bonus.", "Já jsem dobrý pastýř.", "Jan 10,11. Odtud pastorace."]),
  n("plebs", "plēbis f.", "lid, plebejové", ["Plebs in foro clamat.", "Lid křičí na náměstí.", "Odtud plebejec."]),
  n("potestas", "potestātis f.", "moc, pravomoc", ["Data est mihi omnis potestas.", "Je mi dána veškerá moc.", "Mt 28,18."]),
  o("propter", "předložka + akuz.", "kvůli, pro", ["Propter nos homines et propter nostram salutem", "Pro nás lidi a pro naši spásu", "Z Kréda."]),
  v("protego", "prōtegere, prōtēxī, prōtēctum", "kryji, chráním", ["Protege nos, Domine.", "Chraň nás, Pane.", "Odtud protekce, protektor."]),
  o("quartus", "quarta, quartum (číslovka)", "čtvrtý", ["Quarta hora", "Čtvrtá hodina", "Odtud kvarta, kvartet."]),
  v("recipio", "recipere, recēpī, receptum", "přijímám, beru zpět", ["Recipe librum tuum.", "Vezmi si zpět svou knihu.", "Odtud recepce, recept."]),
  n("redemptor", "redēmptōris m.", "vykupitel", ["Redemptor mundi", "Vykupitel světa", "Od redimo = vykupuji."]),
  n("ritus", "rītūs m.", "obřad, ritus", ["Ritus Romanus", "Římský obřad", "Odtud rituál."]),
  n("salvator", "salvātōris m.", "spasitel, zachránce", ["Salvator mundi, salva nos.", "Spasiteli světa, spas nás.", "Odtud jméno Salvátor."]),
  v("salvo", "salvāre, salvāvī, salvātum", "zachraňuji, spasím", ["Salva nos, Domine.", "Zachraň nás, Pane."]),
  n("sanguis", "sanguinis m.", "krev", ["Sanguis Christi, inebria me.", "Krvi Kristova, opoj mě.", "Z modlitby Anima Christi. Odtud sangvinik."]),
  n("scientia", "scientiae f.", "vědění, věda", ["Scientia potentia est.", "Vědění je moc.", "Připisuje se Francisu Baconovi."]),
  n("sententia", "sententiae f.", "výrok, mínění, věta", ["Quot homines, tot sententiae.", "Kolik lidí, tolik názorů.", "Terentius. Odtud sentence."]),
  v("sitio", "sitīre, sitīvī", "žízním, dychtím", ["Sitio.", "Žízním.", "Slova Ježíše na kříži (Jan 19,28)."]),
  a("solus", "sōla, sōlum", "sám, jediný", ["Tu solus Sanctus", "Ty jediný jsi Svatý", "Z hymnu Gloria. Odtud sólo."]),
  v("sumo", "sūmere, sūmpsī, sūmptum", "beru, přijímám", ["Cibum sumimus.", "Přijímáme pokrm.", "Odtud konzumovat (con-sumo)."]),
  v("suscipio", "suscipere, suscēpī, susceptum", "přijímám, ujímám se", ["Suscipe, sancte Pater, hanc hostiam.", "Přijmi, svatý Otče, tuto oběť.", "Z obětování ve mši."]),
  v("taceo", "tacēre, tacuī, tacitum", "mlčím", ["Qui tacet, consentire videtur.", "Kdo mlčí, zdá se souhlasit.", "Česky: mlčení znamená souhlas."]),
  v("tollo", "tollere, sustulī, sublātum", "zdvihám, odnáším", ["Tolle, lege.", "Vezmi, čti.", "Hlas, který slyšel sv. Augustin před svým obrácením."]),
  n("vis", "f. (akuz. vim, abl. vī)", "síla, moc", ["Vis unita fortior.", "Spojená síla je silnější.", "Pozor: vis je i „chceš“ (od volo)."]),
  v("adiuvo", "adiuvāre, adiūvī, adiūtum", "pomáhám, podporuji", ["Adiuva nos, Deus.", "Pomoz nám, Bože.", "Odtud adjutant."]),
  a("admirabilis", "admīrābile", "podivuhodný", ["Quam admirabile est nomen tuum!", "Jak podivuhodné je tvé jméno!", "Žalm 8,2."]),
  n("annalis", "annālis m., obv. pl. annālēs", "letopis, kronika", ["Annales Romanorum", "Letopisy Římanů", "Odtud anály."]),
  n("avaritia", "avāritiae f.", "lakota, hrabivost", ["Radix omnium malorum est avaritia.", "Kořenem všeho zla je lakota.", "1 Tim 6,10."]),
  v("blandior", "blandīrī, blandītus sum", "lichotím, pochlebuji", ["Puer matri blanditur.", "Chlapec lichotí matce.", "Deponens; pojí se s dativem."]),
  a("celeber", "celebris, celebre", "slavný, proslulý", ["Urbs celebris", "Slavné město", "Odtud celebrita."]),
  v("consentio", "cōnsentīre, cōnsēnsī, cōnsēnsum", "souhlasím, shoduji se", ["Omnes consentiunt.", "Všichni souhlasí.", "Odtud konsenzus."]),
  v("cupio", "cupere, cupīvī, cupītum", "žádám, přeji si, toužím", ["Cupio dissolvi et esse cum Christo.", "Toužím odejít a být s Kristem.", "Flp 1,23."]),
  v("curo", "cūrāre, cūrāvī, cūrātum", "pečuji, starám se", ["Aegrotum curo.", "Starám se o nemocného.", "Odtud kúra, kurátor."]),
  v("gaudeo", "gaudēre, gāvīsus sum", "raduji se, těším se", ["Gaudete in Domino semper.", "Radujte se v Pánu vždycky.", "Flp 4,4. Polodeponens: perf. gavisus sum."]),
  v("gigno", "gignere, genuī, genitum", "plodím, rodím", ["Genitum, non factum", "Zrozený, nestvořený", "Z Kréda. Odtud genitiv."]),
  v("hortor", "hortārī, hortātus sum", "povzbuzuji, vybízím", ["Hortor vos, fratres.", "Vybízím vás, bratři.", "Deponens."]),
  a("humilis", "humile", "nízký, pokorný", ["Mitis sum et humilis corde.", "Jsem tichý a pokorný srdcem.", "Mt 11,29. Od humus = země."]),
  n("ingenium", "ingeniī n.", "povaha, nadání, talent", ["Vir magni ingenii", "Muž velkého nadání", "Odtud ingeniózní."]),
  o("invicem", "příslovce", "navzájem, střídavě", ["Diligite invicem.", "Milujte se navzájem.", "Jan 13,34."]),
  v("loquor", "loquī, locūtus sum", "mluvím, hovořím", ["Loquere, Domine, quia audit servus tuus.", "Mluv, Pane, tvůj služebník slyší.", "1 Sam 3,9. Deponens."]),
  v("maledico", "maledīcere, maledīxī, maledictum", "tupím, zlořečím", ["Benedicite et nolite maledicere.", "Žehnejte a nezlořečte.", "Řím 12,14."]),
  a("mendax", "gen. mendācis", "lživý, prolhaný", ["Omnis homo mendax.", "Každý člověk je lhář.", "Žalm 116,11."]),
  v("miror", "mīrārī, mīrātus sum", "divím se, obdivuji", ["Miramur opus tuum.", "Obdivujeme tvé dílo.", "Odtud miraculum = zázrak."]),
  v("nascor", "nāscī, nātus sum", "rodím se, vznikám", ["Puer natus est nobis.", "Narodilo se nám dítě.", "Iz 9,5; vánoční introit."]),
  n("negotium", "negōtiī n.", "zaměstnání, práce, úkol", ["Negotium est negatio otii.", "Zaměstnání je nedostatek volna.", "Nec + otium. Odtud negociace."]),
  a("particeps", "gen. participis", "účastný; účastník", ["Particeps gaudii", "Účastník radosti", "Odtud participace."]),
  v("patior", "patī, passus sum", "trpím, snáším", ["Passus sub Pontio Pilato", "Trpěl pod Pontským Pilátem", "Z Apoštolského vyznání. Deponens. Odtud pasivní, pasije."]),
  a("proximus", "proxima, proximum", "nejbližší", ["Proximus sum egomet mihi.", "Nejbližší jsem sám sobě.", "Terentius."]),
  n("proximus", "proximī m.", "bližní", ["Diliges proximum tuum sicut te ipsum.", "Budeš milovat bližního jako sebe.", "Mt 22,39."]),
  a("prudens", "gen. prūdentis", "rozumný, rozvážný", ["Virgines prudentes", "Moudré panny", "Podobenství o deseti pannách (Mt 25)."]),
  a("quintus", "quīnta, quīntum", "pátý", ["Quinta essentia", "Pátá podstata", "Odtud kvintesence."]),
  o("quisque", "zájmeno, quidque", "každý", ["Suum cuique.", "Každému, co jeho jest.", "Zásada římského práva."]),
  v("resisto", "resistere, restitī", "odporuji, stavím se na odpor", ["Resistite diabolo.", "Vzepřete se ďáblu.", "Jak 4,7. Pojí se s dativem."]),
  n("sapiens", "sapientis m.", "mudrc", ["Sapienti sat.", "Moudrému stačí.", "Rozumnému netřeba víc vysvětlovat."]),
  n("serpens", "serpentis m./f.", "had", ["Serpens erat callidior.", "Had byl chytřejší.", "Gn 3,1."]),
  v("servio", "servīre, servīvī, servītum", "sloužím, otročím", ["Servire Deo regnare est.", "Sloužit Bohu znamená kralovat.", "Odtud servis."]),
  v("surgo", "surgere, surrēxī, surrēctum", "vstávám, povstávám", ["Surge et ambula.", "Vstaň a choď.", "Sk 3,6."]),
  v("vereor", "verērī, veritus sum", "bojím se, ostýchám se", ["Vereor ne veniat.", "Obávám se, že přijde.", "Po slovesech obav znamená ne „že“."]),
  n("auctoritas", "auctōritātis f.", "vážnost, moc, autorita", ["Auctoritas, non veritas facit legem.", "Zákon dělá autorita, ne pravda.", "Thomas Hobbes. Odtud autorita."]),
  v("carpo", "carpere, carpsī, carptum", "trhám; užívám", ["Carpe florem.", "Utrhni květ.", "Srovnej Horatiovo carpe diem."]),
  v("constituo", "cōnstituere, cōnstituī, cōnstitūtum", "ustanovuji, rozhoduji", ["Constituit eum dominum domus suae.", "Ustanovil ho pánem svého domu.", "Žalm 105,21. Odtud konstituce."]),
  n("consul", "cōnsulis m.", "konzul", ["Consules creati sunt.", "Byli zvoleni konzulové.", "Římané volili každý rok dva konzuly."]),
  v("creo", "creāre, creāvī, creātum", "tvořím, plodím; volím", ["In principio creavit Deus caelum et terram.", "Na počátku stvořil Bůh nebe a zemi.", "Gn 1,1. Odtud kreativní."]),
  n("cursus", "cursūs m.", "běh, dráha, směr", ["Cursum consummavi.", "Běh jsem dokonal.", "2 Tim 4,7. Odtud kurz."]),
  v("disputo", "disputāre, disputāvī, disputātum", "rozvažuji, pojednávám", ["De veritate disputamus.", "Rozmlouváme o pravdě.", "Odtud disputace."]),
  v("emo", "emere, ēmī, ēmptum", "kupuji", ["Panem emo.", "Kupuji chléb."]),
  n("gens", "gentis f.", "rod, kmen, národ", ["Laudate Dominum, omnes gentes.", "Chvalte Hospodina, všechny národy.", "Žalm 117,1."]),
  a("gratus", "grāta, grātum", "milý, vítaný; vděčný", ["Gratus sum tibi.", "Jsem ti vděčný.", "Odtud gratulace."]),
  n("hiems", "hiemis f.", "zima", ["Hieme nix cadit.", "V zimě padá sníh.", "Odtud hibernace (hibernus = zimní)."]),
  a("humanus", "hūmāna, hūmānum", "lidský, vzdělaný", ["Homo sum, humani nihil a me alienum puto.", "Jsem člověk, nic lidského mi není cizí.", "Terentius. Odtud humanismus."]),
  o("idem", "zájmeno, eadem, idem", "týž, tentýž", ["Semper idem", "Vždy tentýž", "Ženský rod eadem, střední idem."]),
  n("magistratus", "magistrātūs m.", "úřad; úředník", ["Magistratus virum indicat.", "Úřad ukáže, jaký je kdo muž.", "Odtud magistrát."]),
  a("mortuus", "mortua, mortuum", "mrtvý", ["Resurrectio mortuorum", "Vzkříšení mrtvých", "Z Kréda. Od morior = umírám."]),
  n("oleum", "oleī n.", "olej", ["Oleum et operam perdidi.", "Ztratil jsem olej i námahu.", "Plautus: pracoval jsem zbytečně."]),
  v("pello", "pellere, pepulī, pulsum", "ženu, vyháním", ["Pelle moras.", "Zažeň otálení.", "Odtud impuls, propeler."]),
  v("pendeo", "pendēre, pependī", "visím, závisím", ["Pendet in cruce.", "Visí na kříži.", "Odtud přívěsek = pendant."]),
  n("potus", "pōtūs m.", "nápoj, pití", ["Potum puero do.", "Dávám chlapci napít."]),
  o("quisquam", "zájmeno, quidquam", "někdo, něco", ["Nec quisquam venit.", "A nikdo nepřišel.", "Užívá se v záporných a tázacích větách."]),
  o("quo", "příslovce", "kam", ["Quo vadis?", "Kam jdeš?", "Podle legendy Petrova otázka Kristu."]),
  a("rectus", "rēcta, rēctum", "rovný, přímý, správný", ["Via recta", "Přímá cesta", "Odtud korektní."]),
  v("rego", "regere, rēxī, rēctum", "řídím, spravuji", ["Deus regit mundum.", "Bůh řídí svět.", "Odtud regent, režim."]),
  v("repleo", "replēre, replēvī, replētum", "naplňuji, doplňuji", ["Reple tuorum corda fidelium.", "Naplň srdce svých věrných.", "Z modlitby k Duchu Svatému."]),
  v("requiesco", "requiēscere, requiēvī, requiētum", "odpočívám", ["Requiescat in pace.", "Ať odpočívá v pokoji.", "Zkratka R. I. P. na náhrobcích."]),
  v("resurgo", "resurgere, resurrēxī, resurrēctum", "vstávám z mrtvých", ["Resurrexit, sicut dixit.", "Vstal z mrtvých, jak řekl.", "Z antifony Regina caeli."]),
  n("revelatio", "revēlātiōnis f.", "odhalení, zjevení", ["Revelatio Ioannis", "Zjevení Janovo", "Latinský název Apokalypsy."]),
  n("salus", "salūtis f.", "zdraví, záchrana, spása", ["Salus populi suprema lex esto.", "Blaho lidu budiž nejvyšším zákonem.", "Cicero."]),
  a("sextus", "sexta, sextum", "šestý", ["Sexta hora", "Šestá hodina (poledne)", "Odtud siesta (sexta hora)."]),
  a("talis", "tāle", "takový", ["Qualis pater, talis filius.", "Jaký otec, takový syn.", "Qualis… talis = jaký… takový."]),
  v("tribuo", "tribuere, tribuī, tribūtum", "rozděluji, uděluji", ["Pacem tribue nobis.", "Uděl nám pokoj.", "Odtud atribut, distribuce."]),
  o("unde", "příslovce", "odkud", ["Unde venis?", "Odkud přicházíš?", "Unde, ubi, quo = odkud, kde, kam."]),
  v("vado", "vādere, vāsī, vāsum", "kráčím, jdu", ["Vado ad Patrem.", "Jdu k Otci.", "Jan 16,10."]),
  o("vere", "příslovce", "opravdu, vpravdě", ["Vere dignum et iustum est.", "Je opravdu důstojné a spravedlivé.", "Z preface mše."]),
  v("ascendo", "ascendere, ascendī, ascēnsum", "vystupuji", ["Ascendit in caelum.", "Vstoupil na nebesa.", "Z Kréda. Odtud ascendent."]),
  v("audeo", "audēre, ausus sum", "odvažuji se", ["Sapere aude!", "Odvaž se být moudrý!", "Horatius; heslo osvícenství (Kant)."]),
  v("averto", "āvertere, āvertī, āversum", "odvracím", ["Averte faciem tuam a peccatis meis.", "Odvrať svou tvář od mých hříchů.", "Žalm 51,11."]),
  v("claudo", "claudere, clausī, clausum", "zavírám, zamykám", ["Claude ianuam.", "Zavři dveře.", "Odtud klauzura."]),
  n("consummatio", "cōnsummātiōnis f.", "dovršení, konec", ["Usque ad consummationem saeculi", "Až do skonání světa", "Mt 28,20."]),
  v("crucifigo", "crucifīgere, crucifīxī, crucifīxum", "přibíjím na kříž", ["Crucifixus etiam pro nobis", "Byl za nás i ukřižován", "Z Kréda. Odtud krucifix."]),
  v("descendo", "dēscendere, dēscendī, dēscēnsum", "sestupuji", ["Descendit de caelis.", "Sestoupil z nebe.", "Z Kréda."]),
  o("enim", "spojka", "neboť, totiž", ["Non enim scio.", "Neboť nevím.", "Stojí obvykle na druhém místě ve větě."]),
  n("factor", "factōris m.", "stvořitel, tvůrce", ["Factorem caeli et terrae", "Stvořitele nebe i země", "Z Kréda. Od facio = dělám."]),
  n("finis", "fīnis m.", "hranice, konec, cíl", ["Finis coronat opus.", "Konec korunuje dílo.", "Odtud finále, finance."]),
  v("gero", "gerere, gessī, gestum", "nesu, konám, spravuji", ["Bellum gerimus.", "Vedeme válku.", "Res gestae = vykonané činy. Odtud gesto."]),
  n("herba", "herbae f.", "bylina, rostlina", ["Herba crescit.", "Bylina roste.", "Odtud herbář."]),
  v("imitor", "imitārī, imitātus sum", "napodobuji", ["Puer patrem imitatur.", "Chlapec napodobuje otce.", "Deponens. Odtud imitace."]),
  v("incarno", "incarnāre, incarnāvī, incarnātum", "vtěluji", ["Et incarnatus est de Spiritu Sancto", "A vtělil se skrze Ducha Svatého", "Z Kréda. Od caro, carnis = maso."]),
  a("innocens", "gen. innocentis", "nevinný, bezúhonný", ["Lavabo inter innocentes manus meas.", "Umyji si ruce mezi nevinnými.", "Žalm 26,6."]),
  v("intro", "intrāre, intrāvī, intrātum", "vstupuji, vcházím", ["Intra in gaudium domini tui.", "Vejdi do radosti svého pána.", "Mt 25,21."]),
  o("iterum", "příslovce", "opět, znovu", ["Et iterum venturus est", "A znovu přijde", "Z Kréda. Odtud iterace."]),
  v("iudico", "iūdicāre, iūdicāvī, iūdicātum", "soudím, posuzuji", ["Nolite iudicare.", "Nesuďte.", "Mt 7,1."]),
  a("natus", "nāta, nātum", "narozený; syn, dcera", ["Natus ex Maria Virgine", "Narozený z Marie Panny", "Z Kréda. Od nascor = rodím se."]),
  n("pons", "pontis m.", "most", ["Pons Carolinus", "Karlův most", "Odtud pontifex – doslova stavitel mostů."]),
  v("procedo", "prōcēdere, prōcessī, prōcessum", "jdu vpřed, postupuji", ["Qui ex Patre Filioque procedit.", "Který z Otce i Syna vychází.", "Z Kréda. Odtud procedura, proces."]),
  v("prohibeo", "prohibēre, prohibuī, prohibitum", "zdržuji, zabraňuji", ["Prohibeo te abire.", "Bráním ti odejít.", "Odtud prohibice."]),
  a("publicus", "pūblica, pūblicum", "veřejný, státní", ["Via publica", "Veřejná cesta", "Odtud publikum, publikace."]),
  n("radix", "rādīcis f.", "kořen, původ", ["O radix Iesse", "Ó kořeni Jesse", "Adventní antifona. Odtud radikální."]),
  v("redimo", "redimere, redēmī, redēmptum", "vykupuji", ["Redemisti nos, Domine.", "Vykoupil jsi nás, Pane.", "Odtud redemptor = vykupitel."]),
  n("remissio", "remissiōnis f.", "propuštění, odpuštění", ["In remissionem peccatorum", "Na odpuštění hříchů", "Z Kréda. Odtud remise."]),
  v("restituo", "restituere, restituī, restitūtum", "obnovuji; vracím", ["Librum restituo.", "Vracím knihu.", "Odtud restituce."]),
  v("revertor", "revertī, reversus", "vracím se", ["Revertere ad Dominum.", "Obrať se k Hospodinu.", "Deponens."]),
  v("rogo", "rogāre, rogāvī, rogātum", "ptám se; prosím", ["Te rogamus, audi nos.", "Prosíme tě, vyslyš nás.", "Z litanií. Rogo = ptám se i prosím."]),
  n("scriptura", "scrīptūrae f.", "psaní, písmo, spis", ["Sacra Scriptura", "Písmo svaté", "Od scribo = píšu."]),
  v("sepelio", "sepelīre, sepelīvī, sepultum", "pohřbívám", ["Passus et sepultus est.", "Trpěl a byl pohřben.", "Z Kréda."]),
  v("soleo", "solēre, solitus sum", "mám ve zvyku", ["Mane surgere soleo.", "Obvykle vstávám ráno.", "Polodeponens: solitus sum."]),
  n("species", "speciēī f.", "vzhled, podoba; druh", ["Sub specie aeternitatis", "Z hlediska věčnosti", "Spinoza. Odtud speciální."]),
  n("symbolum", "symbolī n.", "znamení; vyznání víry", ["Symbolum Apostolorum", "Apoštolské vyznání víry", "Z řeckého symbolon = znamení."]),
  v("trado", "trādere, trādidī, trāditum", "odevzdávám, předávám", ["Tradidi vobis quod et accepi.", "Odevzdal jsem vám, co jsem i přijal.", "1 Kor 15,3. Odtud tradice."]),
  o("vale", "citoslovce, pl. valēte", "buď zdráv, sbohem", ["Vale et me ama.", "Buď zdráv a měj mě rád.", "Tak Cicero končil dopisy."]),
  n("veritas", "vēritātis f.", "pravda", ["Veritas vincit.", "Pravda vítězí.", "Česky jako motto na prezidentské standartě."]),
  a("visibilis", "vīsibile", "viditelný", ["Visibilium omnium et invisibilium", "Všeho viditelného i neviditelného", "Z Kréda."]),
  v("vivifico", "vīvificāre, vīvificāvī, vīvificātum", "oživuji", ["Dominum et vivificantem", "Pána a dárce života", "Z Kréda (o Duchu Svatém)."]),
  a("vivus", "vīva, vīvum", "živý", ["Iudicare vivos et mortuos", "Soudit živé i mrtvé", "Z Kréda."]),
  v("abeo", "abīre, abiī, abitum", "odcházím; umírám", ["Abiit, excessit, evasit, erupit.", "Odešel, vytratil se, unikl, vyrazil.", "Cicero o Catilinovi."]),
  n("auris", "auris f.", "ucho", ["Qui habet aures audiendi, audiat.", "Kdo má uši k slyšení, slyš.", "Mk 4,9."]),
  v("baptizo", "baptizāre, baptizāvī, baptizātum", "křtím", ["Ego te baptizo.", "Já tě křtím.", "Z řeckého baptizein = ponořit."]),
  a("candidus", "candida, candidum", "bílý, zářivý", ["Nix candida", "Bílý sníh", "Odtud kandidát – uchazeč v bílé tóze."]),
  n("communio", "commūniōnis f.", "společenství; přijímání", ["Sanctorum communionem", "Společenství svatých", "Z Apoštolského vyznání. Odtud komunie."]),
  n("concordia", "concordiae f.", "svornost, soulad", ["Concordia parvae res crescunt.", "Svorností rostou malé věci.", "Sallustius."]),
  n("corona", "corōnae f.", "věnec, koruna", ["Dabo tibi coronam vitae.", "Dám ti korunu života.", "Zj 2,10."]),
  n("creator", "creātōris m.", "stvořitel, tvůrce", ["Creator caeli et terrae", "Stvořitel nebe i země", "Odtud kreativní."]),
  v("cresco", "crēscere, crēvī, crētum", "rostu, vzrůstám", ["Crescite et multiplicamini.", "Ploďte se a množte se.", "Gn 1,28. Odtud crescendo."]),
  v("dubito", "dubitāre, dubitāvī, dubitātum", "pochybuji, váhám", ["Dubito, ergo cogito.", "Pochybuji, tedy myslím.", "Odtud dubiózní."]),
  o("duodecim", "číslovka, neskl.", "dvanáct", ["Duodecim apostoli", "Dvanáct apoštolů", "Duo + decem."]),
  v("esurio", "ēsurīre, ēsurīvī, ēsurītum", "mám hlad, lačním", ["Esurivi enim, et dedistis mihi manducare.", "Měl jsem hlad, a dali jste mi jíst.", "Mt 25,35."]),
  n("humilitas", "humilitātis f.", "nízkost, pokora", ["Humilitas veritas est.", "Pokora je pravda.", "Volně podle sv. Terezie z Ávily."]),
  a("inimicus", "inimīca, inimīcum", "nepřátelský", ["Diligite inimicos vestros.", "Milujte své nepřátele.", "Mt 5,44. In + amicus."]),
  n("initium", "initiī n.", "počátek, začátek", ["Initium sancti Evangelii", "Začátek svatého evangelia", "Odtud iniciála, iniciativa."]),
  a("octavus", "octāva, octāvum", "osmý", ["Octava die", "Osmého dne", "Odtud oktáva."]),
  v("perdo", "perdere, perdidī, perditum", "hubím, ničím, ztrácím", ["Amici, diem perdidi.", "Přátelé, ztratil jsem den.", "Podle Suetonia výrok císaře Tita, když za celý den nikomu neprospěl."]),
  v("persevero", "persevērāre, persevērāvī, persevērātum", "vytrvávám, setrvávám", ["Persevera usque ad finem.", "Vytrvej až do konce.", "Odtud perseverance."]),
  n("pes", "pedis m.", "noha; stopa", ["Pedes eius lavit.", "Umyl mu nohy.", "Odtud pedál, pedikúra."]),
  n("potentia", "potentiae f.", "moc, síla", ["Potentia Dei magna est.", "Boží moc je veliká.", "Odtud potence, potenciál."]),
  a("propinquus", "propinqua, propinquum", "blízký, příbuzný", ["Propinqui mei venerunt.", "Přišli moji příbuzní."]),
  o("quicumque", "zájmeno, quaecumque, quodcumque", "kdokoli, kterýkoli", ["Quicumque vult salvus esse", "Kdokoli chce být spasen", "Začátek Athanasiova vyznání víry."]),
  o("quidam", "zájmeno, quaedam, quiddam", "kdosi, cosi", ["Homo quidam fecit cenam magnam.", "Jeden člověk vystrojil velikou hostinu.", "Lk 14,16."]),
  n("sedes", "sēdis f.", "sedadlo, trůn; sídlo", ["Sedes Sapientiae", "Trůn moudrosti", "Titul Panny Marie z Loretánských litanií."]),
  n("semen", "sēminis n.", "semeno, símě; rod", ["Semen est verbum Dei.", "Semeno je slovo Boží.", "Lk 8,11."]),
  n("sensus", "sēnsūs m.", "vnímání, cit; smysl", ["Sensus communis", "Zdravý rozum", "Odtud senzor; anglicky common sense."]),
  a("stultus", "stulta, stultum", "hloupý, pošetilý", ["Stultorum infinitus est numerus.", "Počet bláznů je nekonečný.", "Kazatel 1,15 podle Vulgáty."]),
  o("undecim", "číslovka, neskl.", "jedenáct", ["Undecim discipuli", "Jedenáct učedníků", "Unus + decem."]),
  v("aestimo", "aestimāre, aestimāvī, aestimātum", "odhaduji, vážím si, oceňuji", ["Te magni aestimo.", "Velice si tě vážím.", "Magni je genitiv ceny: vysoko."]),
]);
