import { lesson, n, v, a, o } from "./define";

// Základní slovní zásoba (■) z učebnice M. Šlesinger: Základy latinského jazyka
// pro posluchače teologie, v pořadí, v jakém se slova v učebnici objevují.
export default lesson("Slovíčka 2", [
  o("ab", "předložka + abl. (ā, ab, abs)", "od, z"),
  v("accipio", "accipere, accēpī, acceptum", "přijímám, beru, dostávám"),
  o("amen", "citoslovce (hebr.)", "opravdu, staň se, amen"),
  o("ave", "rozkaz. způsob (avēte)", "buď zdráv, vítej"),
  a("benedictus", "benedicta, benedictum", "požehnaný, blahořečený"),
  a("caecus", "caeca, caecum", "slepý"),
  n("colloquium", "colloquiī n.", "rozmluva, rozhovor"),
  a("cotidianus", "cotīdiāna, cotīdiānum", "každodenní, denní, všední"),
  n("cultus", "cultūs m.", "péče, uctívání, bohoslužba"),
  n("debitor", "dēbitōris m.", "dlužník; viník, hříšník"),
  n("debitum", "dēbitī n.", "dluh, závazek, vina"),
  v("dimitto", "dīmittere, dīmīsī, dīmissum", "propouštím, odpouštím"),
  n("exemplum", "exemplī n.", "příklad, vzor, ukázka"),
  n("facultas", "facultātis f.", "možnost, schopnost; fakulta"),
  a("falsus", "falsa, falsum", "klamný, nepravdivý, falešný"),
  n("femina", "fēminae f.", "žena"),
  v("fio", "fierī, factus sum", "stávám se, vznikám"),
  n("gratia", "grātiae f.", "vděk, dík, půvab; milost"),
  v("induco", "indūcere, indūxī, inductum", "uvádím, přivádím"),
  a("iniustus", "iniūsta, iniūstum", "nespravedlivý"),
  o("intra", "předložka + akuz.", "uvnitř, dovnitř; během"),
  n("littera", "litterae f.", "písmeno; písmo"),
  n("malum", "malī n.", "zlo, špatnost, neřest"),
  v("misereor", "miserērī, miseritus sum (+ gen.)", "smilovávám se nad někým"),
  o("ne", "záporka (u rozk. a konj.)", "ne, ať ne, kéž ne"),
  n("ordo", "ōrdinis m.", "řada, řád, pořádek; stav"),
  n("passus", "passūs m.", "krok; dvojkrok (míra)"),
  n("peccator", "peccātōris m.", "hříšník"),
  n("philosophus", "philosophī m.", "filozof"),
  a("proprius", "propria, proprium", "vlastní"),
  o("qui", "zájmeno vztažné (quae, quod)", "který, jenž, kdo"),
  n("repetitio", "repetītiōnis f.", "opakování"),
  a("sacer", "sacra, sacrum", "posvátný, svatý"),
  v("sanctifico", "sānctificāre, sānctificāvī, sānctificātum", "posvěcuji"),
  a("sanctus", "sāncta, sānctum", "svatý, posvěcený"),
  o("sicut", "spojka", "tak jako, stejně jako"),
  n("spiritus", "spīritūs m.", "duch; dech, vánek"),
  a("suus", "sua, suum", "svůj"),
  n("tentatio", "tentātiōnis f. (i temptātiō)", "pokušení, zkouška"),
  a("totus", "tōta, tōtum (gen. tōtīus)", "celý, všechen"),
  n("venter", "ventris m.", "břicho; mateřský život"),
  n("voluntas", "voluntātis f.", "vůle, přání, úmysl"),
  n("acies", "aciēī f.", "ostří, bystrost; šik"),
  n("amica", "amīcae f.", "přítelkyně"),
  v("appello", "appellāre, appellāvī, appellātum", "nazývám, oslovuji"),
  v("benedico", "benedīcere, benedīxī, benedictum", "dobrořečím, žehnám"),
  n("benedictio", "benedictiōnis f.", "dobrořečení; požehnání"),
  n("caro", "carnis f.", "maso, tělo"),
  v("concipio", "concipere, concēpī, conceptum", "chápu; počínám"),
  n("cornu", "cornūs n.", "roh; křídlo šiku"),
  n("crux", "crucis f.", "kříž; trápení"),
  n("currus", "currūs m.", "vůz, povoz"),
  v("deleo", "dēlēre, dēlēvī, dēlētum", "ničím, hubím, vyhlazuji"),
  a("dignus", "digna, dignum", "důstojný, hodný"),
  n("ecclesia", "ecclēsiae f.", "církev; shromáždění; kostel"),
  v("educo", "ēducāre, ēducāvī, ēducātum", "vychovávám, pěstuji"),
  v("efficio", "efficere, effēcī, effectum", "způsobuji, vytvářím"),
  v("exsulto", "exsultāre, exsultāvī, exsultātum", "jásám, plesám"),
  n("forma", "fōrmae f.", "tvar, vzhled, podoba"),
  n("fortunae", "fortūnārum f. (pl.)", "statky, majetek"),
  n("genus", "generis n.", "rod, původ, pokolení"),
  n("historia", "historiae f.", "dějiny, historie"),
  n("honor", "honōris m. (i honōs)", "čest, úcta, úřad"),
  v("impero", "imperāre, imperāvī, imperātum", "rozkazuji, velím, vládnu"),
  n("incarnatio", "incarnātiōnis f.", "vtělení"),
  n("iustitia", "iūstitiae f.", "spravedlnost"),
  n("laetitia", "laetitiae f.", "radost, veselí"),
  n("magistra", "magistrae f.", "učitelka; představená"),
  n("mens", "mentis f.", "mysl, rozum, úmysl"),
  n("modus", "modī m.", "míra, způsob; nápěv"),
  a("mysticus", "mystica, mysticum", "tajemný, mystický"),
  o("nisi", "spojka", "jestliže ne; leda, než"),
  v("nomino", "nōmināre, nōmināvī, nōminātum", "jmenuji, nazývám"),
  v("nuntio", "nūntiāre, nūntiāvī, nūntiātum", "oznamuji, zvěstuji"),
  v("orno", "ōrnāre, ōrnāvī, ōrnātum", "zdobím, strojím"),
  n("paenitentia", "paenitentiae f.", "lítost, pokání"),
  n("patriarcha", "patriarchae m.", "praotec, patriarcha"),
  n("persona", "persōnae f.", "osoba; maska"),
  a("pius", "pia, pium", "zbožný, oddaný, laskavý"),
  n("principium", "prīncipiī n.", "počátek, základ, princip"),
  n("promissio", "prōmissiōnis f.", "slib, zaslíbení"),
  n("propheta", "prophētae m.", "prorok"),
  n("prudentia", "prūdentiae f.", "prozíravost, moudrost"),
  n("regina", "rēgīnae f.", "královna"),
  n("resurrectio", "resurrēctiōnis f.", "zmrtvýchvstání, vzkříšení"),
  a("sacratus", "sacrāta, sacrātum", "posvěcený, svatý"),
  n("saeculum", "saeculī n.", "věk, století; svět"),
  o("satis", "příslovce (i sat)", "dost, dostatečně"),
  o("secundum", "předložka + akuz.", "podle, vedle, hned po"),
  a("secundus", "secunda, secundum", "druhý; příznivý"),
  v("spero", "spērāre, spērāvī, spērātum", "doufám, očekávám"),
  o("super", "předložka + akuz.", "nad, na, přes, kromě"),
  n("tenebrae", "tenebrārum f. (pl.)", "tma, temnota"),
  n("trinitas", "trīnitātis f.", "trojice"),
  n("triumphus", "triumphī m.", "triumf, vítězný průvod"),
  n("victor", "victōris m.", "vítěz"),
  v("vigilo", "vigilāre, vigilāvī, vigilātum", "bdím"),
  n("virgo", "virginis f.", "panna, dívka"),
  a("aeternus", "aeterna, aeternum", "věčný, nesmrtelný"),
  v("agnosco", "agnōscere, agnōvī, agnitum", "poznávám, uznávám"),
  n("agnus", "agnī m.", "jehně, beránek"),
  a("alienus", "aliēna, aliēnum", "cizí, jiný"),
  a("aptus", "apta, aptum", "vhodný, připravený"),
  n("argumentum", "argūmentī n.", "důkaz, důvod, obsah"),
  a("aridus", "ārida, āridum", "suchý, vyprahlý"),
  n("arma", "armōrum n. pl.", "zbraně, zbroj"),
  o("atque", "spojka (zkr. ac)", "a, i, a také"),
  a("beatus", "beāta, beātum", "blažený, šťastný"),
  n("canticum", "canticī n.", "píseň, zpěv"),
  n("castra", "castrōrum n. pl.", "tábor, ležení"),
  o("circa", "předložka + akuz.; příslovce", "kolem, okolo"),
  a("clemens", "gen. clēmentis", "mírný, laskavý"),
  n("cogitatio", "cōgitātiōnis f.", "myšlení, myšlenka"),
  v("committo", "committere, commīsī, commissum", "spojuji, páchám, svěřuji"),
  v("confiteor", "cōnfitērī, cōnfessus sum", "vyznávám, přiznávám"),
  o("coram", "předložka + abl.; příslovce", "před, v přítomnosti"),
  n("decalogus", "decalogī m.", "desatero"),
  n("desertum", "dēsertī n.", "poušť, pustina"),
  n("dextera", "dexterae f.", "pravice"),
  n("discipulus", "discipulī m.", "žák, učedník"),
  n("dominica", "dominicae f.", "den Páně, neděle"),
  v("fleo", "flēre, flēvī, flētum", "pláču, naříkám"),
  v("gemo", "gemere, gemuī, gemitum", "lkám, sténám"),
  n("humus", "humī f.", "země, půda"),
  o("ideo", "příslovce", "proto"),
  o("ille", "illa, illud (zájmeno)", "onen, on"),
  n("imperium", "imperiī n.", "rozkaz, vláda, moc"),
  v("interpello", "interpellāre, interpellāvī, interpellātum", "přerušuji, zastávám se"),
  v("interrogo", "interrogāre, interrogāvī, interrogātum", "ptám se, vyslýchám"),
  n("lacrima", "lacrimae f.", "slza"),
  n("mandatum", "mandātī n.", "přikázání, příkaz"),
  a("minimus", "minima, minimum", "nejmenší"),
  n("misericordia", "misericordiae f.", "milosrdenství"),
  v("morior", "morī, mortuus sum", "umírám"),
  n("mysterium", "mystēriī n.", "tajemství"),
  o("nimis", "příslovce", "příliš, velmi"),
  n("omissio", "omissiōnis f.", "opomenutí, zanedbání"),
  a("omnipotens", "gen. omnipotentis", "všemohoucí"),
  v("ostendo", "ostendere, ostendī, ostentum", "ukazuji, dokazuji"),
  n("peccatum", "peccātī n.", "hřích, provinění"),
  v("pecco", "peccāre, peccāvī, peccātum", "hřeším"),
  n("praeceptum", "praeceptī n.", "příkaz, rada"),
  v("precor", "precārī, precātus sum", "prosím, modlím se"),
  o("quia", "spojka", "protože"),
  o("quoniam", "spojka", "protože, neboť"),
  a("salutaris", "salūtāre", "léčivý, spasitelný"),
  o("salve", "pozdrav (pl. salvēte)", "buď zdráv, vítej"),
  v("salveo", "salvēre", "jsem zdráv"),
  v("sano", "sānāre, sānāvī, sānātum", "uzdravuji, léčím"),
  o("se", "zvratné zájmeno (suī, sibi)", "sebe, se"),
  v("sequor", "sequī, secūtus sum", "následuji, sleduji"),
  o("sero", "příslovce", "pozdě"),
  v("studeo", "studēre, studuī (+ dat.)", "snažím se, zabývám se"),
  v("suspiro", "suspīrāre, suspīrāvī, suspīrātum", "vzdychám, toužím"),
  o("tertius", "tertia, tertium (číslovka)", "třetí"),
  a("verus", "vēra, vērum", "pravý, pravdivý"),
  a("vester", "vestra, vestrum", "váš"),
  o("vos", "osobní zájmeno (vestrī, vōbīs)", "vy"),
  n("aestas", "aestātis f.", "léto"),
  n("animal", "animālis n.", "živočich, zvíře"),
  n("baptisma", "baptismatis n.", "křest"),
  a("caelestis", "caeleste", "nebeský"),
  n("caritas", "cāritātis f.", "láska, úcta"),
  n("civitas", "cīvitātis f.", "obec, občanství"),
  n("communicatio", "commūnicātiōnis f.", "sdělení, společenství"),
  v("concedo", "concēdere, concessī, concessum", "ustupuji, dovoluji"),
  v("corrigo", "corrigere, corrēxī, corrēctum", "opravuji, napravuji"),
  a("cunctus", "cūncta, cūnctum", "veškerý, všechen"),
  v("custodio", "custōdīre, custōdīvī, custōdītum", "hlídám, střežím"),
  v("defendo", "dēfendere, dēfendī, dēfēnsum", "hájím, bráním"),
  n("dens", "dentis m.", "zub"),
  n("deprecatio", "dēprecātiōnis f.", "prosba, přímluva"),
  v("diligo", "dīligere, dīlēxī, dīlēctum", "miluji, vážím si"),
  a("divinus", "dīvīna, dīvīnum", "božský, boží"),
  v("exaudio", "exaudīre, exaudīvī, exaudītum", "vyslyším, slyším"),
  n("exemplar", "exemplāris n.", "vzor, obraz"),
  v("fallo", "fallere, fefellī, falsum", "klamu, podvádím"),
  v("finio", "fīnīre, fīnīvī, fīnītum", "končím, omezuji"),
  n("fons", "fontis m.", "pramen, zdroj"),
  n("generatio", "generātiōnis f.", "pokolení, plození"),
  v("glorifico", "glōrificāre, glōrificāvī, glōrificātum", "oslavuji"),
  n("imago", "imāginis f.", "obraz, podoba"),
  v("impleo", "implēre, implēvī, implētum", "naplňuji"),
  n("iter", "itineris n.", "pochod, cesta"),
  n("ius", "iūris n.", "právo"),
  n("iuvenis", "iuvenis m.", "mladík"),
  n("lumen", "lūminis n.", "světlo"),
  n("mos", "mōris m.", "mrav, zvyk"),
  v("mundo", "mundāre, mundāvī, mundātum", "čistím, očišťuji"),
  n("mundus", "mundī m.", "svět, vesmír"),
  n("oratio", "ōrātiōnis f.", "řeč, modlitba"),
  n("orbis", "orbis m.", "kruh, svět"),
  n("ōs", "ōris n.", "ústa, tvář"),
  n("os", "ossis n.", "kost"),
  n("pastor", "pastōris m.", "pastýř"),
  n("plebs", "plēbis f.", "lid, plebejové"),
  n("potestas", "potestātis f.", "moc, pravomoc"),
  o("propter", "předložka + akuz.", "kvůli, pro"),
  v("protego", "prōtegere, prōtēxī, prōtēctum", "kryji, chráním"),
  o("quartus", "quarta, quartum (číslovka)", "čtvrtý"),
  v("recipio", "recipere, recēpī, receptum", "přijímám, beru zpět"),
  n("redemptor", "redēmptōris m.", "vykupitel"),
  n("ritus", "rītūs m.", "obřad, ritus"),
  n("salvator", "salvātōris m.", "spasitel, zachránce"),
  v("salvo", "salvāre, salvāvī, salvātum", "zachraňuji, spasím"),
  n("sanguis", "sanguinis m.", "krev"),
  n("scientia", "scientiae f.", "vědění, věda"),
  n("sententia", "sententiae f.", "výrok, mínění, věta"),
  v("sitio", "sitīre, sitīvī", "žízním, dychtím"),
  a("solus", "sōla, sōlum", "sám, jediný"),
  v("sumo", "sūmere, sūmpsī, sūmptum", "beru, přijímám"),
  v("suscipio", "suscipere, suscēpī, susceptum", "přijímám, ujímám se"),
  v("taceo", "tacēre, tacuī, tacitum", "mlčím"),
  v("tollo", "tollere, sustulī, sublātum", "zdvihám, odnáším"),
  n("vis", "f. (akuz. vim, abl. vī)", "síla, moc"),
  v("adiuvo", "adiuvāre, adiūvī, adiūtum", "pomáhám, podporuji"),
  a("admirabilis", "admīrābile", "podivuhodný"),
  n("annalis", "annālis m., obv. pl. annālēs", "letopis, kronika"),
  n("avaritia", "avāritiae f.", "lakota, hrabivost"),
  v("blandior", "blandīrī, blandītus sum", "lichotím, pochlebuji"),
  a("celeber", "celebris, celebre", "slavný, proslulý"),
  v("consentio", "cōnsentīre, cōnsēnsī, cōnsēnsum", "souhlasím, shoduji se"),
  v("cupio", "cupere, cupīvī, cupītum", "žádám, přeji si, toužím"),
  v("curo", "cūrāre, cūrāvī, cūrātum", "pečuji, starám se"),
  v("gaudeo", "gaudēre, gāvīsus sum", "raduji se, těším se"),
  v("gigno", "gignere, genuī, genitum", "plodím, rodím"),
  v("hortor", "hortārī, hortātus sum", "povzbuzuji, vybízím"),
  a("humilis", "humile", "nízký, pokorný"),
  n("ingenium", "ingeniī n.", "povaha, nadání, talent"),
  o("invicem", "příslovce", "navzájem, střídavě"),
  v("loquor", "loquī, locūtus sum", "mluvím, hovořím"),
  v("maledico", "maledīcere, maledīxī, maledictum", "tupím, zlořečím"),
  a("mendax", "gen. mendācis", "lživý, prolhaný"),
  v("miror", "mīrārī, mīrātus sum", "divím se, obdivuji"),
  v("nascor", "nāscī, nātus sum", "rodím se, vznikám"),
  n("negotium", "negōtiī n.", "zaměstnání, práce, úkol"),
  a("particeps", "gen. participis", "účastný; účastník"),
  v("patior", "patī, passus sum", "trpím, snáším"),
  a("proximus", "proxima, proximum", "nejbližší"),
  n("proximus", "proximī m.", "bližní"),
  a("prudens", "gen. prūdentis", "rozumný, rozvážný"),
  a("quintus", "quīnta, quīntum", "pátý"),
  o("quisque", "zájmeno, quidque", "každý"),
  v("resisto", "resistere, restitī", "odporuji, stavím se na odpor"),
  n("sapiens", "sapientis m.", "mudrc"),
  n("serpens", "serpentis m./f.", "had"),
  v("servio", "servīre, servīvī, servītum", "sloužím, otročím"),
  v("surgo", "surgere, surrēxī, surrēctum", "vstávám, povstávám"),
  v("vereor", "verērī, veritus sum", "bojím se, ostýchám se"),
  n("auctoritas", "auctōritātis f.", "vážnost, moc, autorita"),
  v("carpo", "carpere, carpsī, carptum", "trhám; užívám"),
  v("constituo", "cōnstituere, cōnstituī, cōnstitūtum", "ustanovuji, rozhoduji"),
  n("consul", "cōnsulis m.", "konzul"),
  v("creo", "creāre, creāvī, creātum", "tvořím, plodím; volím"),
  n("cursus", "cursūs m.", "běh, dráha, směr"),
  v("disputo", "disputāre, disputāvī, disputātum", "rozvažuji, pojednávám"),
  v("emo", "emere, ēmī, ēmptum", "kupuji"),
  n("gens", "gentis f.", "rod, kmen, národ"),
  a("gratus", "grāta, grātum", "milý, vítaný; vděčný"),
  n("hiems", "hiemis f.", "zima"),
  a("humanus", "hūmāna, hūmānum", "lidský, vzdělaný"),
  o("idem", "zájmeno, eadem, idem", "týž, tentýž"),
  n("magistratus", "magistrātūs m.", "úřad; úředník"),
  a("mortuus", "mortua, mortuum", "mrtvý"),
  n("oleum", "oleī n.", "olej"),
  v("pello", "pellere, pepulī, pulsum", "ženu, vyháním"),
  v("pendeo", "pendēre, pependī", "visím, závisím"),
  n("potus", "pōtūs m.", "nápoj, pití"),
  o("quisquam", "zájmeno, quidquam", "někdo, něco"),
  o("quo", "příslovce", "kam"),
  a("rectus", "rēcta, rēctum", "rovný, přímý, správný"),
  v("rego", "regere, rēxī, rēctum", "řídím, spravuji"),
  v("repleo", "replēre, replēvī, replētum", "naplňuji, doplňuji"),
  v("requiesco", "requiēscere, requiēvī, requiētum", "odpočívám"),
  v("resurgo", "resurgere, resurrēxī, resurrēctum", "vstávám z mrtvých"),
  n("revelatio", "revēlātiōnis f.", "odhalení, zjevení"),
  n("salus", "salūtis f.", "zdraví, záchrana, spása"),
  a("sextus", "sexta, sextum", "šestý"),
  a("talis", "tāle", "takový"),
  v("tribuo", "tribuere, tribuī, tribūtum", "rozděluji, uděluji"),
  o("unde", "příslovce", "odkud"),
  v("vado", "vādere, vāsī, vāsum", "kráčím, jdu"),
  o("vere", "příslovce", "opravdu, vpravdě"),
  v("ascendo", "ascendere, ascendī, ascēnsum", "vystupuji"),
  v("audeo", "audēre, ausus sum", "odvažuji se"),
  v("averto", "āvertere, āvertī, āversum", "odvracím"),
  v("claudo", "claudere, clausī, clausum", "zavírám, zamykám"),
  n("consummatio", "cōnsummātiōnis f.", "dovršení, konec"),
  v("crucifigo", "crucifīgere, crucifīxī, crucifīxum", "přibíjím na kříž"),
  v("descendo", "dēscendere, dēscendī, dēscēnsum", "sestupuji"),
  o("enim", "spojka", "neboť, totiž"),
  n("factor", "factōris m.", "stvořitel, tvůrce"),
  n("finis", "fīnis m.", "hranice, konec, cíl"),
  v("gero", "gerere, gessī, gestum", "nesu, konám, spravuji"),
  n("herba", "herbae f.", "bylina, rostlina"),
  v("imitor", "imitārī, imitātus sum", "napodobuji"),
  v("incarno", "incarnāre, incarnāvī, incarnātum", "vtěluji"),
  a("innocens", "gen. innocentis", "nevinný, bezúhonný"),
  v("intro", "intrāre, intrāvī, intrātum", "vstupuji, vcházím"),
  o("iterum", "příslovce", "opět, znovu"),
  v("iudico", "iūdicāre, iūdicāvī, iūdicātum", "soudím, posuzuji"),
  a("natus", "nāta, nātum", "narozený; syn, dcera"),
  n("pons", "pontis m.", "most"),
  v("procedo", "prōcēdere, prōcessī, prōcessum", "jdu vpřed, postupuji"),
  v("prohibeo", "prohibēre, prohibuī, prohibitum", "zdržuji, zabraňuji"),
  a("publicus", "pūblica, pūblicum", "veřejný, státní"),
  n("radix", "rādīcis f.", "kořen, původ"),
  v("redimo", "redimere, redēmī, redēmptum", "vykupuji"),
  n("remissio", "remissiōnis f.", "propuštění, odpuštění"),
  v("restituo", "restituere, restituī, restitūtum", "obnovuji; vracím"),
  v("revertor", "revertī, reversus", "vracím se"),
  v("rogo", "rogāre, rogāvī, rogātum", "ptám se; prosím"),
  n("scriptura", "scrīptūrae f.", "psaní, písmo, spis"),
  v("sepelio", "sepelīre, sepelīvī, sepultum", "pohřbívám"),
  v("soleo", "solēre, solitus sum", "mám ve zvyku"),
  n("species", "speciēī f.", "vzhled, podoba; druh"),
  n("symbolum", "symbolī n.", "znamení; vyznání víry"),
  v("trado", "trādere, trādidī, trāditum", "odevzdávám, předávám"),
  o("vale", "citoslovce, pl. valēte", "buď zdráv, sbohem"),
  n("veritas", "vēritātis f.", "pravda"),
  a("visibilis", "vīsibile", "viditelný"),
  v("vivifico", "vīvificāre, vīvificāvī, vīvificātum", "oživuji"),
  a("vivus", "vīva, vīvum", "živý"),
  v("abeo", "abīre, abiī, abitum", "odcházím; umírám"),
  n("auris", "auris f.", "ucho"),
  v("baptizo", "baptizāre, baptizāvī, baptizātum", "křtím"),
  a("candidus", "candida, candidum", "bílý, zářivý"),
  n("communio", "commūniōnis f.", "společenství; přijímání"),
  n("concordia", "concordiae f.", "svornost, soulad"),
  n("corona", "corōnae f.", "věnec, koruna"),
  n("creator", "creātōris m.", "stvořitel, tvůrce"),
  v("cresco", "crēscere, crēvī, crētum", "rostu, vzrůstám"),
  v("dubito", "dubitāre, dubitāvī, dubitātum", "pochybuji, váhám"),
  o("duodecim", "číslovka, neskl.", "dvanáct"),
  v("esurio", "ēsurīre, ēsurīvī, ēsurītum", "mám hlad, lačním"),
  n("humilitas", "humilitātis f.", "nízkost, pokora"),
  a("inimicus", "inimīca, inimīcum", "nepřátelský"),
  n("initium", "initiī n.", "počátek, začátek"),
  a("octavus", "octāva, octāvum", "osmý"),
  v("perdo", "perdere, perdidī, perditum", "hubím, ničím, ztrácím"),
  v("persevero", "persevērāre, persevērāvī, persevērātum", "vytrvávám, setrvávám"),
  n("pes", "pedis m.", "noha; stopa"),
  n("potentia", "potentiae f.", "moc, síla"),
  a("propinquus", "propinqua, propinquum", "blízký, příbuzný"),
  o("quicumque", "zájmeno, quaecumque, quodcumque", "kdokoli, kterýkoli"),
  o("quidam", "zájmeno, quaedam, quiddam", "kdosi, cosi"),
  n("sedes", "sēdis f.", "sedadlo, trůn; sídlo"),
  n("semen", "sēminis n.", "semeno, símě; rod"),
  n("sensus", "sēnsūs m.", "vnímání, cit; smysl"),
  a("stultus", "stulta, stultum", "hloupý, pošetilý"),
  o("undecim", "číslovka, neskl.", "jedenáct"),
  v("aestimo", "aestimāre, aestimāvī, aestimātum", "odhaduji, vážím si, oceňuji"),
]);
