import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 3", [
  v("annuntio", "annūntiāre, annūntiāvī, annūntiātum", "oznamuji, zvěstuji", ["Annuntio vobis gaudium magnum.", "Zvěstuji vám velikou radost.", "Odtud anonce."]),
  n("calix", "calicis m.", "kalich, pohár", ["Hic est calix sanguinis mei.", "Toto je kalich mé krve.", "Ze mše. Odtud kalich."]),
  a("castus", "casta, castum", "čistý, bezúhonný", ["Vita casta et pura", "Čistý a bezúhonný život", "Odtud incest – doslova ne-čistý (in-castus)."]),
  v("colo", "colere, coluī, cultum", "obdělávám, pěstuji, ctím", ["Agricola agros colit.", "Rolník obdělává pole.", "Odtud kultura, kolonie."]),
  a("continuus", "continua, continuum", "souvislý, nepřetržitý", ["Labor continuus", "Nepřetržitá práce", "Odtud kontinuita."]),
  n("dolor", "dolōris m.", "bolest, zármutek", ["Dolor capitis gravis est.", "Bolest hlavy je silná.", "Odtud Mater Dolorosa – Bolestná Matka."]),
  a("dubius", "dubia, dubium", "pochybný, nejistý", ["In dubiis libertas.", "V pochybných věcech svoboda.", "Celé: In necessariis unitas, in dubiis libertas, in omnibus caritas."]),
  a("durus", "dūra, dūrum", "tvrdý, krutý, přísný", ["Durum est saxum.", "Kámen je tvrdý.", "Odtud dur – „tvrdá“ tónina v hudbě."]),
  n("error", "errōris m.", "blud, omyl", ["Error tuus magnus est.", "Tvůj omyl je velký.", "Odtud anglické error."]),
  n("fama", "fāmae f.", "pověst, zpráva", ["Fama volat.", "Pověst letí.", "Vergilius. Odtud fáma."]),
  a("irregularis", "irrēgulāre", "nepravidelný", ["Verbum irregulare", "Nepravidelné sloveso", "Před r se in- mění v ir-: ir-regularis."]),
  o("magnopere", "příslovce", "velmi, velice", ["Te magnopere amo.", "Velmi tě miluji.", "Ze dvou slov: magno opere – s velkou námahou."]),
  v("manduco", "mandūcāre, mandūcāvī, mandūcātum", "jím", ["Qui manducat hunc panem, vivet in aeternum.", "Kdo jí tento chléb, bude žít navěky.", "Jan 6. Odtud francouzské manger – jíst."]),
  n("meritum", "meritī n.", "zásluha, mzda", ["Pro meritis tuis", "Za tvé zásluhy", "Odtud meritorní."]),
  n("munus", "mūneris n.", "úkol, úřad, dar", ["Munus magistri difficile est.", "Úřad učitele je těžký.", "Odtud imunita, remunerace."]),
  a("necessarius", "necessāria, necessārium", "nutný, potřebný", ["In necessariis unitas.", "V nutných věcech jednota."]),
  a("nonus", "nōna, nōnum", "devátý", ["Hora nona", "Devátá hodina", "Nóna – modlitba církve kolem třetí odpoledne."]),
  a("nullus", "nūlla, nūllum", "žádný", ["Nulla dies sine linea.", "Ani den bez čárky.", "Plinius o malíři Apellovi. Odtud nula."]),
  n("nuntius", "nūntiī m.", "zpráva, posel", ["Nuntius apostolicus", "Apoštolský nuncius", "Nuncius je papežský vyslanec."]),
  n("odium", "odiī n.", "nenávist, odpor", ["Odium et amor", "Nenávist a láska", "Příbuzné s odi – nenávidím."]),
  a("optimus", "optima, optimum", "nejlepší", ["Corruptio optimi pessima.", "Zkaženost nejlepšího je nejhorší.", "Superlativ k bonus. Odtud optimální, optimista."]),
  a("perpetuus", "perpetua, perpetuum", "ustavičný, trvalý, věčný", ["Lux perpetua luceat eis.", "Věčné světlo ať jim svítí.", "Z modlitby za zemřelé. Odtud perpetuum mobile."]),
  v("persequor", "persequī, persecūtus sum", "pronásleduji, stíhám", ["Milites hostem persequuntur.", "Vojáci pronásledují nepřítele.", "Odtud perzekuce."]),
  o("prae", "předložka + abl.", "před, pro, kvůli", ["Prae gaudio flevit.", "Plakal radostí.", "Odtud předpona pre- (prezident = kdo sedí vpředu)."]),
  a("prior", "prius", "přednější, dřívější", ["Prior tempore, potior iure.", "Kdo je dřív, má silnější právo.", "Právnická zásada. Odtud priorita, převor."]),
  a("regularis", "rēgulāre", "pravidelný, řeholní", ["Vita regularis", "Řeholní život", "Od regula – pravidlo, řehole."]),
  n("responsum", "respōnsī n.", "odpověď, výrok", ["Responsum dedit.", "Dal odpověď.", "Odtud responzorium – zpěv s odpověďmi."]),
  a("tantus", "tanta, tantum", "tak veliký, takový", ["Tantum ergo sacramentum", "Tak velikou tedy svátost", "Začátek hymnu sv. Tomáše Akvinského."]),
  o("utinam", "částice", "kéž, kéž by", ["Utinam veniat!", "Kéž by přišel!", "Utinam s konjunktivem vyjadřuje přání."]),
  n("victima", "victimae f.", "obětní zvíře, oběť", ["Victimae paschali laudes", "Velikonoční oběti chvály", "Začátek velikonoční sekvence."]),
  o("aliqui", "aliqua, aliquod (zájmeno)", "některý, nějaký", ["Aliqui homines veniunt.", "Přicházejí nějací lidé.", "Přídavné: aliqui homo; podstatné: aliquis."]),
  o("aliquis", "aliquid (zájmeno)", "někdo, něco", ["Aliquis venit.", "Někdo přichází.", "Po si, nisi, ne, num odpadá ali-: si quis."]),
  n("auctor", "auctōris m.", "původce, autor", ["Auctor libri", "Autor knihy", "Odtud autor, autorita."]),
  n("contritio", "contrītiōnis f.", "lítost", ["Contritio cordis", "Lítost srdce", "Od conterere – rozdrtit: srdce zdrcené lítostí."]),
  n("creatura", "creātūrae f.", "stvoření, tvor", ["Omnis creatura Deum laudat.", "Všechno stvoření chválí Boha.", "Odtud kreatura, kreativní."]),
  a("decimus", "decima, decimum", "desátý", ["Decima pars", "Desátá část", "Odtud decimovat – popravit každého desátého."]),
  v("desum", "deesse, dēfuī, dēfutūrus", "chybím, scházím", ["Nihil mihi deest.", "Nic mi nechybí.", "Žalm 23 (22): Dominus regit me, et nihil mihi deerit."]),
  v("dono", "dōnāre, dōnāvī, dōnātum", "daruji, odpouštím", ["Dona nobis pacem.", "Daruj nám pokoj.", "Z Agnus Dei. Odtud donátor."]),
  o("etsi", "spojka", "i když, ačkoli", ["Etsi pauper est, laetus est.", "Ačkoli je chudý, je radostný."]),
  v("evenio", "ēvenīre, ēvēnī, ēventum", "vycházím, stávám se", ["Quid evenit?", "Co se stalo?", "Odtud eventuální."]),
  v("impedio", "impedīre, impedīvī, impedītum", "překážím, zdržuji", ["Nihil me impedit.", "Nic mi nepřekáží.", "Od pes, pedis – noha: doslova zaplést nohy."]),
  a("infelix", "gen. īnfēlīcis", "nešťastný", ["Homo infelix", "Nešťastný člověk", "In- + felix (šťastný)."]),
  n("libertas", "lībertātis f.", "svoboda, volnost", ["Libertas carior auro est.", "Svoboda je dražší než zlato.", "Odtud liberální."]),
  v("luceo", "lūcēre, lūxī", "svítím, skvím se", ["Lux in tenebris lucet.", "Světlo svítí ve tmě.", "Jan 1,5. Od lux – světlo."]),
  o("quadraginta", "číslovka, neskl.", "čtyřicet", ["Quadraginta dies et quadraginta noctes", "Čtyřicet dní a čtyřicet nocí", "Odtud karanténa (z ital. quaranta)."]),
  o("quisquis", "quidquid (zájmeno)", "kdokoli, cokoli", ["Quisquis es, intra!", "Ať jsi kdokoli, vstup!", "Zdvojené quis: kdokoli."]),
  v("reddo", "reddere, reddidī, redditum", "vracím, dávám zpět", ["Reddite quae sunt Caesaris Caesari.", "Dávejte, co je císařovo, císaři.", "Mt 22,21."]),
  v("refero", "referre, rettulī, relātum", "nesu zpět, oznamuji", ["Tibi gratias refero.", "Projevuji ti vděčnost.", "Odtud referát, referendum."]),
  n("requies", "requiētis f.", "klid, odpočinek", ["Requiem aeternam dona eis.", "Věčné odpočinutí dej jim.", "Odtud rekviem – mše za zemřelé."]),
  n("sacramentum", "sacrāmentī n.", "přísaha, svátost", ["Sacramentum baptismi", "Svátost křtu", "Původně vojenská přísaha. Odtud sakrament."]),
  o("sponte", "příslovce", "dobrovolně, sám od sebe", ["Sua sponte venit.", "Přišel sám od sebe.", "Odtud spontánní."]),
  n("testimonium", "testimōniī n.", "svědectví, důkaz", ["Testimonium perhibere", "Vydávat svědectví", "Příbuzné: testis – svědek."]),
  n("timor", "timōris m.", "bázeň, strach", ["Timor Domini", "Bázeň Boží", "Od timeo – bojím se."]),
  n("unitas", "ūnitātis f.", "jednota, jednotka", ["Unitas fratrum", "Jednota bratrská", "Latinský název Jednoty bratrské. Od unus."]),
  n("viaticum", "viāticī n.", "cestovné, pokrm na cestu", ["Viaticum morientibus datur.", "Umírajícím se podává viatikum.", "Poslední přijímání umírajícího. Od via – cesta."]),
  v("accuso", "accūsāre, accūsāvī, accūsātum", "žaluji, obviňuji", ["Me accuso.", "Obviňuji sám sebe.", "Odtud akuzativ – pád obžaloby."]),
  v("administro", "administrāre, administrāvī, administrātum", "obstarávám, spravuji, řídím", ["Rem publicam administrat.", "Spravuje stát.", "Odtud administrativa."]),
  n("altare", "altāris n.", "oltář", ["Introibo ad altare Dei.", "Přistoupím k oltáři Božímu.", "Žalm 43 (42),4; úvod tridentské mše."]),
  v("erigo", "ērigere, ērēxī, ērēctum", "vztyčuji, pozvedám", ["Erige oculos tuos!", "Pozvedni své oči!", "Odtud erigovat – zřídit (např. farnost)."]),
  v("floreo", "flōrēre, flōruī", "kvetu, vzkvétám", ["Rosa floret.", "Růže kvete.", "Odtud floristika, Florencie."]),
  v("genuflecto", "genūflectere, genūflexī, genūflexum", "klekám, poklekám", ["Sacerdos genuflectit.", "Kněz poklekne.", "Z genu (koleno) + flecto (ohýbám)."]),
  n("innocentia", "innocentiae f.", "nevinnost, bezúhonnost", ["Innocentia pueri", "Nevinnost dítěte", "Příbuzné: jméno Inocenc."]),
  v("offero", "offerre, obtulī, oblātum", "podávám, nabízím, obětuji", ["Panem et vinum offerimus.", "Přinášíme chléb a víno.", "Odtud ofertorium – příprava darů."]),
  v("placeo", "placēre, placuī", "líbím se", ["Placet.", "Líbí se, souhlasím.", "Tak se hlasovalo na koncilech. Odtud placebo – „budu se líbit“."]),
  v("proficio", "prōficere, prōfēcī, prōfectum", "pokračuji, prospívám", ["Puer in studiis proficit.", "Chlapec dělá pokroky ve studiu.", "Odtud profit."]),
  a("purus", "pūra, pūrum", "čistý, bezúhonný", ["Aqua pura", "Čistá voda", "Odtud puritán, purismus."]),
  n("regio", "regiōnis f.", "směr, kraj, území", ["Regio montana", "Horský kraj", "Odtud region."]),
  o("semel", "příslovce", "jednou", ["Semel in anno licet insanire.", "Jednou za rok je dovoleno bláznit.", "Středověké úsloví."]),
  o("uterque", "utraque, utrumque (zájmeno)", "oba, jeden i druhý", ["Uterque frater venit.", "Přišli oba bratři.", "Skloňuje se jako uter: gen. utriusque."]),
  v("utor", "ūtī, ūsus sum (+ abl.)", "užívám, používám", ["Utere tempore!", "Využij čas!", "Pojí se s ablativem: utor libro – užívám knihu."]),
  a("amarus", "amāra, amārum", "hořký, trpký", ["Fletus amarus", "Hořký pláč", "Mt 26,75 o Petrovi: flevit amare – hořce plakal."]),
  o("ambo", "ambae, ambō (číslovka)", "oba", ["Ambo venerunt.", "Přišli oba.", "Starý duál: ambo, ambae, ambo."]),
  o("an", "tázací částice", "či, zda", ["Vivit an mortuus est?", "Žije, či je mrtev?", "Ve dvojité otázce: utrum… an – zda… či."]),
  v("assum", "adesse, affuī, affutūrus", "jsem přítomen, pomáhám", ["Adsum!", "Jsem tu! (Přítomen!)", "Odpověď při vyvolávání jmen, např. při svěcení."]),
  v("conficio", "cōnficere, cōnfēcī, cōnfectum", "zhotovuji, dokončuji", ["Opus confeci.", "Dokončil jsem dílo.", "Odtud konfekce."]),
  n("crimen", "crīminis n.", "zločin, vina", ["Crimen laesae maiestatis", "Zločin urážky majestátu", "Odtud kriminální."]),
  v("divido", "dīvidere, dīvīsī, dīvīsum", "odděluji, rozděluji", ["Divide et impera.", "Rozděl a panuj.", "Odtud dividenda, divize."]),
  v("doleo", "dolēre, doluī, dolitūrus", "cítím bolest, lituji", ["Doleo de peccatis meis.", "Lituji svých hříchů.", "Příbuzné: dolor – bolest."]),
  o("dum", "spojka", "zatímco, dokud", ["Dum spiro, spero.", "Dokud dýchám, doufám.", "Dum s indikativem: dokud, zatímco."]),
  a("duodecimus", "duodecima, duodecimum", "dvanáctý", ["Duodecimus mensis", "Dvanáctý měsíc", "Odtud duodecimální (dvanáctková) soustava."]),
  n("eques", "equitis m.", "jezdec, rytíř", ["Eques Romanus", "Římský jezdec", "Od equus – kůň. Jezdci byli druhý stav v Římě."]),
  v("moveo", "movēre, mōvī, mōtum", "hýbám, pohybuji, dojímám", ["Lacrimae me movent.", "Slzy mě dojímají.", "Odtud motor, mobil, emoce."]),
  n("paradisus", "paradīsī m.", "zahrada, ráj", ["Hodie mecum eris in paradiso.", "Dnes budeš se mnou v ráji.", "Lk 23,43. Z perského slova pro ohradu, zahradu."]),
  n("piscis", "piscis m.", "ryba", ["Piscis in aqua natat.", "Ryba plave ve vodě.", "Ryba je starý symbol Krista (řec. ichthys)."]),
  v("praesum", "praeesse, praefuī, praefutūrus", "jsem v čele, řídím", ["Rex regno praeest.", "Král stojí v čele království.", "Pojí se s dativem."]),
  v("prosum", "prōdesse, prōfuī, prōfutūrus", "prospívám, pomáhám", ["Hoc tibi prodest.", "To ti prospívá.", "Před samohláskou se vkládá d: prodest, proderam."]),
  v("puto", "putāre, putāvī, putātum", "domnívám se, myslím", ["Puto te venturum esse.", "Myslím, že přijdeš.", "Odtud amputace; computo – počítám."]),
  o("quando", "příslovce", "kdy, když", ["Quando venies?", "Kdy přijdeš?"]),
  o("quot", "neskl.", "kolik", ["Quot homines, tot sententiae.", "Kolik lidí, tolik názorů.", "Terentius. Odtud kvóta."]),
  n("socius", "sociī m.", "druh, společník, spojenec", ["Socius meus", "Můj společník", "Odtud sociální."]),
  o("tot", "neskl.", "tolik", ["Tot annos exspectavi.", "Tolik let jsem čekal.", "Tot – quot: tolik – kolik."]),
  v("abnego", "abnegāre, abnegāvī, abnegātum", "odpírám, zapírám", ["Abneget semetipsum.", "Ať zapře sám sebe.", "Mt 16,24. Odtud abnegace."]),
  v("aggredior", "aggredī, aggressus sum", "přistupuji, napadám", ["Hostes urbem aggrediuntur.", "Nepřátelé napadají město.", "Odtud agrese."]),
  n("amicitia", "amīcitiae f.", "přátelství", ["Amicitia vera rara est.", "Pravé přátelství je vzácné.", "Cicero napsal spis De amicitia – O přátelství."]),
  o("circum", "předložka + akuz.", "kolem, okolo", ["Circum urbem", "Kolem města", "Příbuzné: circus, cirkulace."]),
  v("coepi", "coepisse, coeptum", "začal jsem", ["Coepit loqui.", "Začal mluvit.", "Má jen tvary perfekta; přítomný čas nahrazuje incipio."]),
  v("confligo", "cōnflīgere, cōnflīxī, cōnflīctum", "srážím se, zápasím", ["Exercitus confligunt.", "Vojska se střetávají.", "Odtud konflikt."]),
  v("conservo", "cōnservāre, cōnservāvī, cōnservātum", "zachovávám, uchovávám", ["Conserva me, Domine.", "Zachovej mě, Pane.", "Žalm 16 (15),1. Odtud konzerva, konzervatoř."]),
  v("eligo", "ēligere, ēlēgī, ēlēctum", "vybírám, volím", ["Non vos me elegistis.", "Ne vy jste vyvolili mne.", "Jan 15,16. Odtud elita, elegantní."]),
  o("erga", "předložka + akuz.", "vůči, k", ["Amor erga patriam", "Láska k vlasti"]),
  v("fruor", "fruī, fruitūrus (+ abl.)", "užívám, těším se z", ["Vita fruere!", "Užívej života!", "Pojí se s ablativem."]),
  v("iaceo", "iacēre, iacuī", "ležím", ["Puer in lecto iacet.", "Chlapec leží v posteli.", "Neplést s iacio – házím."]),
  o("igitur", "spojka", "tedy", ["Gaudeamus igitur.", "Radujme se tedy.", "Začátek studentské hymny."]),
  v("intellego", "intellegere, intellēxī, intellēctum", "poznávám, chápu, rozumím", ["Credo ut intellegam.", "Věřím, abych pochopil.", "Sv. Anselm. Odtud inteligence."]),
  v("malo", "mālle, māluī", "raději chci", ["Malo mori quam foedari.", "Raději zemřít než být poskvrněn.", "Staré heslo. Z magis + volo."]),
  v("memini", "meminisse", "pamatuji se", ["Memento, homo, quia pulvis es.", "Pamatuj, člověče, že jsi prach.", "Popeleční středa. Rozkaz: memento."]),
  n("monumentum", "monumentī n.", "památka, pomník", ["Exegi monumentum aere perennius.", "Postavil jsem si památník trvalejší než bronz.", "Horatius. Odtud monument."]),
  v("nosco", "nōscere, nōvī, nōtum", "poznávám; perf. znám", ["Nosce te ipsum.", "Poznej sám sebe.", "Perfektum novi znamená znám."]),
  o("ob", "předložka + akuz.", "před, kvůli", ["Ob eam causam", "Z toho důvodu", "Odtud předpona ob- (objekt)."]),
  v("odi", "ōdisse, ōsūrus", "nenávidím", ["Odi et amo.", "Nenávidím a miluji.", "Catullus. Tvary perfekta s významem přítomným."]),
  a("paschalis", "paschāle", "velikonoční", ["Agnus paschalis", "Velikonoční beránek", "Od pascha – Velikonoce."]),
  v("praedico", "praedīcere, praedīxī, praedictum", "předpovídám, varuji", ["Futura praedicit.", "Předpovídá budoucnost.", "Neplést s praedico, -are – hlásám, kážu."]),
  v("reconcilio", "reconciliāre, reconciliāvī, reconciliātum", "smiřuji, obnovuji", ["Reconciliamini Deo.", "Smiřte se s Bohem.", "2 Kor 5,20."]),
  v("regno", "rēgnāre, rēgnāvī, rēgnātum", "kraluji, vládnu", ["Christus vincit, Christus regnat.", "Kristus vítězí, Kristus kraluje.", "Začátek chvalozpěvu Laudes regiae."]),
  n("sabbatum", "sabbatī n.", "sobota, sabat", ["Sabbatum propter hominem factum est.", "Sobota je tu pro člověka.", "Mk 2,27."]),
  a("varius", "varia, varium", "rozličný, rozmanitý", ["Variae sunt hominum sententiae.", "Názory lidí jsou rozmanité.", "Odtud variace, varieté."]),
  n("vestis", "vestis f.", "šat, oděv", ["Vestis virum facit.", "Šaty dělají člověka.", "Odtud vesta."]),
  v("affero", "afferre, attulī, allātum", "donáším, oznamuji", ["Quid novi affers?", "Co nového přinášíš?", "Ad + fero; d se mění v f."]),
  n("autumnus", "autumnī m.", "podzim", ["Autumno folia cadunt.", "Na podzim padá listí."]),
  o("bis", "číselné příslovce", "dvakrát", ["Bis dat, qui cito dat.", "Dvakrát dává, kdo dává rychle.", "Odtud bis – přídavek na koncertě."]),
  n("capitulum", "capitulī n.", "kapitola, kapitula", ["Primum capitulum", "První kapitola", "Zdrobnělina od caput – hlavička. Odtud kapitula."]),
  n("circulus", "circulī m.", "kruh, okruh", ["Circulus vitiosus", "Bludný kruh", "Zdrobnělina od circus. Odtud cirkulář."]),
  v("confero", "cōnferre, contulī, collātum", "snáším, srovnávám, uděluji", ["Confer!", "Srovnej!", "Zkratka cf. v knihách znamená confer – srovnej."]),
  v("designo", "dēsīgnāre, dēsīgnāvī, dēsīgnātum", "označuji, určuji", ["Locum designo.", "Určuji místo.", "Odtud design."]),
  n("disciplina", "disciplīnae f.", "učení, nauka, kázeň", ["Disciplina militaris", "Vojenská kázeň", "Od disco – učím se. Odtud disciplína."]),
  a("duodevicesimus", "duodēvīcēsima, duodēvīcēsimum", "osmnáctý", ["Duodevicesimus annus", "Osmnáctý rok", "Doslova: dva od dvacátého."]),
  o("duodeviginti", "číslovka, neskl.", "osmnáct", ["Duodeviginti annos natus", "Osmnáctiletý", "Dva od dvaceti: 20 − 2 = 18."]),
  v("explico", "explicāre, explicāvī, explicātum", "rozvinuji, vysvětluji", ["Rem explicat.", "Vysvětluje věc.", "Odtud explikace, explicitní."]),
  n("feria", "fēriae f.", "den, všední den", ["Feria secunda", "Pondělí", "Církevní názvy dnů: feria secunda = pondělí, tertia = úterý…"]),
  n("hebdomas", "hebdomadis f.", "sedmička, týden", ["Hebdomas sancta", "Svatý týden", "Z řečtiny: hepta – sedm."]),
  v("lapido", "lapidāre, lapidāvī, lapidātum", "kamenuji", ["Lapidabant Stephanum.", "Kamenovali Štěpána.", "Sk 7,59. Od lapis – kámen."]),
  n("lapis", "lapidis m.", "kámen, milník", ["Lapis angularis", "Úhelný kámen", "Odtud lapidárium, lapidární."]),
  n("martyr", "martyris m.", "svědek, mučedník", ["Sanguis martyrum semen christianorum.", "Krev mučedníků je semenem křesťanů.", "Podle Tertulliána. Z řeckého martys – svědek."]),
  n("mensis", "mēnsis m.", "měsíc", ["Mensis Ianuarius", "Měsíc leden", "Odtud semestr (sex menses – šest měsíců)."]),
  n("nativitas", "nātīvitātis f.", "narození, Vánoce", ["Nativitas Domini", "Narození Páně", "Odtud italské Natale – Vánoce."]),
  o("novem", "číslovka, neskl.", "devět", ["Novem dies", "Devět dní", "Odtud novéna; November byl původně 9. měsíc."]),
  o("octo", "číslovka, neskl.", "osm", ["Octo dies", "Osm dní", "Oktáva – osm dní po svátku. October byl 8. měsíc."]),
  a("opportunus", "opportūna, opportūnum", "příhodný, vhodný", ["Tempus opportunum", "Příhodný čas", "Odtud oportunista."]),
  v("praetereo", "praeterīre, praeteriī, praeteritum", "míjím, opomíjím", ["Tempus praeterit.", "Čas míjí.", "Odtud préteritum – minulý čas."]),
  v("propono", "prōpōnere, prōposuī, prōpositum", "předkládám, navrhuji", ["Homo proponit, sed Deus disponit.", "Člověk míní, Pán Bůh mění.", "Tomáš Kempenský. Odtud propozice."]),
  n("quadragesima", "quadrāgēsimae f.", "čtyřicetina", ["Tempus quadragesimae", "Čtyřicetidenní postní doba", "Postní doba trvá čtyřicet dní."]),
  o("quater", "číselné příslovce", "čtyřikrát", ["Quater in anno", "Čtyřikrát do roka"]),
  o("quindecim", "číslovka, neskl.", "patnáct", ["Quindecim anni", "Patnáct let", "Quinque + decem."]),
  v("redeo", "redīre, rediī, reditum", "vracím se", ["Redi ad me!", "Vrať se ke mně!", "Re(d) + eo; časuje se jako eo."]),
  o("sedecim", "číslovka, neskl.", "šestnáct", ["Sedecim annos natus", "Šestnáctiletý", "Sex + decem."]),
  o("sex", "číslovka, neskl.", "šest", ["Sex diebus operaberis.", "Šest dní budeš pracovat.", "Ex 20,9. Odtud sexta – šestá hodina."]),
  n("tabula", "tabulae f.", "deska, tabule, listina", ["Tabula rasa", "Nepopsaná deska", "Odtud tabule, tabulka."]),
  v("tego", "tegere, tēxī, tēctum", "kryji, přikrývám", ["Nox terram tegit.", "Noc přikrývá zemi.", "Odtud tectum – střecha; detektiv – kdo odkrývá."]),
  o("ter", "číselné příslovce", "třikrát", ["Ter in die", "Třikrát denně"]),
  o("tredecim", "číslovka, neskl.", "třináct", ["Tredecim dies", "Třináct dní", "Tres + decem."]),
  o("triginta", "číslovka, neskl.", "třicet", ["Triginta argenteos", "Třicet stříbrných", "Mt 26,15 – Jidášova odměna."]),
  n("ver", "vēris n.", "jaro", ["Vere flores florent.", "Na jaře kvetou květiny.", "Odtud italské primavera – jaro."]),
  a("vicesimus", "vīcēsima, vīcēsimum", "dvacátý", ["Vicesimus dies", "Dvacátý den"]),
  o("viginti", "číslovka, neskl.", "dvacet", ["Viginti anni", "Dvacet let", "Odtud vigesimální (dvacítková) soustava."]),
  v("accidit", "accidere, accidit (neosobní)", "stává se, přihází se", ["Saepe accidit, ut erremus.", "Často se stává, že se mýlíme.", "Neosobní: accidit, ut… – stává se, že…"]),
  v("accido", "accidere, accidī", "dopadám, nastávám", ["Sagitta ad pedes accidit.", "Šíp dopadl k nohám.", "Ad + cado. Odtud akcident – nehoda."]),
  n("affinitas", "affīnitātis f.", "sousedství, příbuzenství", ["Affinitas et consanguinitas", "Švagrovství a pokrevní příbuzenství", "Odtud afinita."]),
  a("carnalis", "carnāle", "tělesný", ["Desideria carnalia", "Tělesné touhy", "Od caro, carnis – maso, tělo."]),
  v("circumdo", "circumdare, circumdedī, circumdatum", "obklopuji, obkličuji", ["Circumdederunt me gemitus mortis.", "Obklíčily mě steny smrti.", "Introit neděle Septuagesima."]),
  a("communis", "commūne", "společný, obecný", ["Sensus communis", "Zdravý rozum", "Odtud komunita."]),
  n("concursus", "concursūs m.", "sběh, srocení, srážka", ["Concursus populi", "Sběh lidu", "Odtud konkurz."]),
  v("congredior", "congredī, congressus sum", "setkávám se, utkávám se", ["Amici in foro congrediuntur.", "Přátelé se setkávají na náměstí.", "Odtud kongres."]),
  n("consanguinitas", "cōnsanguinitātis f.", "pokrevní příbuzenství", ["Consanguinitas impedit matrimonium.", "Pokrevní příbuzenství brání sňatku.", "Con + sanguis (krev)."]),
  n("constantia", "cōnstantiae f.", "stálost, vytrvalost", ["Constantia in adversis", "Vytrvalost v nepřízni", "Odtud konstanta."]),
  v("constat", "cōnstāre, cōnstitit (neosobní)", "je známo, je zjištěno", ["Constat inter omnes.", "Všichni to vědí.", "Neosobní: constat – je jisto, ví se."]),
  v("contero", "conterere, contrīvī, contrītum", "roztírám, ničím", ["Ipsa conteret caput tuum.", "Ona ti rozdrtí hlavu.", "Gn 3,15 podle Vulgáty."]),
  v("contingit", "contingere, contigit (neosobní)", "stává se, daří se", ["Non cuivis homini contingit adire Corinthum.", "Ne každému se poštěstí dostat se do Korintu.", "Horatius."]),
  v("contingo", "contingere, contigī, contāctum", "dotýkám se, dostihuji", ["Vestem eius contigit.", "Dotkl se jeho šatu.", "Odtud kontakt."]),
  v("convenio", "convenīre, convēnī, conventum", "scházím se, shoduji se", ["Omnes in ecclesia conveniunt.", "Všichni se scházejí v kostele.", "Odtud konvent, konvence."]),
  n("cultura", "cultūrae f.", "pěstění, vzdělávání, uctívání", ["Cultura animi philosophia est.", "Pěstování ducha je filozofie.", "Cicero. Od colo – pěstuji."]),
  v("decet", "decēre, decuit (neosobní)", "sluší se, hodí se", ["Te decet hymnus, Deus.", "Tobě, Bože, náleží chvalozpěv.", "Žalm 65 (64),2."]),
  v("deduco", "dēdūcere, dēdūxī, dēductum", "svádím, odvádím, odvozuji", ["Hoc ex principiis deducitur.", "To se odvozuje ze zásad.", "Odtud dedukce."]),
  v("ēdo", "ēdere, ēdidī, ēditum", "vydávám, vyhlašuji", ["Librum edidit.", "Vydal knihu.", "Neplést s edo – jím. Odtud edice, editor."]),
  n("flos", "flōris m.", "květ, květina", ["Flos campi", "Polní květ", "Odtud flóra."]),
  n("gubernaculum", "gubernāculī n.", "kormidlo, řízení", ["Gubernaculum navis", "Kormidlo lodi", "Odtud guvernér, anglické government."]),
  n("imperator", "imperātōris m.", "velitel, císař", ["Ave, imperator, morituri te salutant.", "Buď zdráv, císaři, jdoucí na smrt tě zdraví.", "Pozdrav gladiátorů podle Suetonia."]),
  n("iniuria", "iniūriae f.", "křivda, bezpráví", ["Iniuriam facile patior.", "Křivdu snáším snadno.", "Odtud injurie – urážka na cti."]),
  n("iustificatio", "iūstificātiōnis f.", "ospravedlnění", ["Iustificatio ex fide est.", "Ospravedlnění je z víry.", "Pojem z listu sv. Pavla Římanům."]),
  v("noceo", "nocēre, nocuī, nocitum", "škodím", ["Primum non nocere.", "Především neškodit.", "Zásada lékařské etiky. Noceo se pojí s dativem."]),
  v("oportet", "oportēre, oportuit (neosobní)", "je třeba, sluší se", ["Illum oportet crescere, me autem minui.", "On musí růst, já však se menšit.", "Jan 3,30."]),
  n("ornamentum", "ōrnāmentī n.", "ozdoba, výzdoba", ["Templum multis ornamentis plenum est.", "Chrám je plný ozdob.", "Odtud ornament."]),
  v("pateo", "patēre, patuī", "jsem otevřen, rozkládám se", ["Porta patet.", "Brána je otevřená.", "Odtud patentní – zjevný."]),
  n("scriptor", "scrīptōris m.", "písař, spisovatel", ["Scriptor librum scribit.", "Spisovatel píše knihu.", "Odtud skriptor – písař v klášteře."]),
  v("secedo", "sēcēdere, sēcessī, sēcessum", "odcházím, vzdaluji se", ["Plebs in montem sacrum secessit.", "Lid odešel na Posvátnou horu.", "Odtud secese – odtržení."]),
  n("testamentum", "testāmentī n.", "závěť, smlouva, zákon", ["Novum Testamentum", "Nový zákon", "Odtud testament – poslední vůle."]),
  n("tribulatio", "tribulātiōnis f.", "trápení, útisk", ["In tribulatione invocavi Dominum.", "V soužení jsem vzýval Pána."]),
  n("voluptas", "voluptātis f.", "rozkoš, slast", ["Voluptas non est summum bonum.", "Rozkoš není nejvyšší dobro."]),
  n("aeternitas", "aeternitātis f.", "věčnost", ["Ars aeternitatis", "Umění věčnosti"]),
  n("argentum", "argentī n.", "stříbro", ["Argentum et aurum non est mihi.", "Stříbro ani zlato nemám.", "Sk 3,6. Značka stříbra Ag je z argentum."]),
  v("consulo", "cōnsulere, cōnsuluī, cōnsultum", "radím se, pečuji", ["Medicum consulo.", "Radím se s lékařem.", "Odtud konzultace."]),
  v("frango", "frangere, frēgī, frāctum", "lámu, rozbíjím", ["Panem frangimus.", "Lámeme chléb.", "Odtud fraktura, fragment."]),
  a("patiens", "gen. patientis", "trpělivý, vytrvalý", ["Caritas patiens est.", "Láska je trpělivá.", "1 Kor 13,4. Odtud pacient – ten, kdo trpí."]),
  n("praemium", "praemiī n.", "odměna", ["Virtus praemium est optimum.", "Ctnost je nejlepší odměna.", "Odtud prémie."]),
  n("proverbium", "prōverbiī n.", "přísloví, podobenství", ["Proverbium vetus est.", "Je to staré přísloví."]),
  n("quies", "quiētis f.", "klid, pokoj, odpočinek", ["Quies post laborem dulcis est.", "Odpočinek po práci je sladký.", "Od quies je requies – odpočinutí (Requiem aeternam)."]),
  n("status", "statūs m.", "postavení, stav", ["Status quo", "Stávající stav", "Odtud status, statistika."]),
  v("appropinquo", "appropinquāre, appropinquāvī, appropinquātum", "přibližuji se, blížím se", ["Appropinquavit regnum caelorum.", "Přiblížilo se království nebeské.", "Mt 3,2."]),
  v("arbitror", "arbitrārī, arbitrātus sum", "soudím, domnívám se", ["Ita arbitror.", "Tak soudím.", "Odtud arbitr, arbitráž."]),
  v("ieiuno", "iēiūnāre, iēiūnāvī, iēiūnātum", "postím se", ["Ieiuno bis in sabbato.", "Postím se dvakrát týdně.", "Lk 18,12."]),
  n("morbus", "morbī m.", "nemoc", ["Morbus gravis est.", "Nemoc je těžká.", "Odtud morbidní – chorobný."]),
  o("necesse est", "neosobní výraz", "je nutno, je třeba", ["Necesse est discere.", "Je nutné se učit.", "Navigare necesse est – plout je nutné."]),
  v("neglego", "neglegere, neglēxī, neglēctum", "nedbám, zanedbávám", ["Officium non neglego.", "Nezanedbávám povinnost.", "Odtud negližé (z fr. négligé)."]),
  v("nego", "negāre, negāvī, negātum", "popírám, zapírám", ["Petrus Dominum ter negavit.", "Petr třikrát zapřel Pána.", "Odtud negace, negativní."]),
  o("opus est", "neosobní výraz (+ abl.)", "je zapotřebí", ["Opus est mihi auxilio.", "Potřebuji pomoc.", "Opus est se pojí s ablativem toho, co je potřeba."]),
  n("paupertas", "paupertātis f.", "chudoba", ["Paupertas non est vitium.", "Chudoba není neřest.", "Odtud pauperismus."]),
  v("praebeo", "praebēre, praebuī, praebitum", "poskytuji, ukazuji", ["Aquam praebeo.", "Podávám vodu."]),
  a("reliquus", "reliqua, reliquum", "zbývající, ostatní", ["Reliqui milites fugerunt.", "Ostatní vojáci utekli.", "Odtud relikvie – pozůstatky."]),
  v("remitto", "remittere, remīsī, remissum", "posílám zpět, odpouštím", ["Epistulam tibi remitto.", "Posílám ti dopis zpět.", "Odtud remissio peccatorum – odpuštění hříchů."]),
  v("solvo", "solvere, solvī, solūtum", "rozvazuji, osvobozuji, platím", ["Debitum solvo.", "Splácím dluh.", "Odtud solventní, absolutorium."]),
  n("turba", "turbae f.", "zmatek, dav, zástup", ["Turba magna sequebatur eum.", "Šel za ním velký zástup.", "Odtud turbulence."]),
  v("veto", "vetāre, vetuī, vetitum", "zakazuji", ["Lex furtum vetat.", "Zákon zakazuje krádež.", "Odtud veto – zakazuji."]),
  o("aliquot", "nesklonné", "několik", ["Aliquot dies manebo.", "Zůstanu několik dní.", "Nesklonné, jako quot a tot."]),
  n("aspectus", "aspectūs m.", "pohled, vzhled", ["Aspectus maris pulcher est.", "Pohled na moře je krásný.", "Odtud aspekt."]),
  n("assumptio", "assumptiōnis f.", "přijetí, nanebevzetí", ["Assumptio Beatae Mariae Virginis", "Nanebevzetí Panny Marie", "Svátek 15. srpna."]),
  a("avarus", "avāra, avārum", "lakomý", ["Avarus numquam satis habet.", "Lakomec nemá nikdy dost.", "Odtud avarice (fr.) – lakota."]),
  n("avis", "avis f.", "pták", ["Rara avis", "Vzácný pták", "Juvenalis. Odtud aviatika."]),
  n("calamitas", "calamitātis f.", "pohroma, neštěstí", ["Bellum magna calamitas est.", "Válka je velké neštěstí.", "Odtud kalamita."]),
  n("calcar", "calcāris n.", "ostruha, pobídka", ["Calcar equo addo.", "Pobízím koně ostruhou."]),
  n("calculus", "calculī m.", "kamínek, počet", ["Calculos pono.", "Počítám (kamínky).", "Římané počítali kamínky. Odtud kalkulace."]),
  n("campus", "campī m.", "pole, pláň", ["Campus Martius", "Martovo pole", "Odtud kampus, kemp."]),
  a("causalis", "causāle", "příčinný", ["Nexus causalis", "Příčinná souvislost", "Odtud kauzální."]),
  v("cedo", "cēdere, cessī, cessum", "kráčím, ustupuji", ["Cedant arma togae.", "Ať zbraně ustoupí tóze.", "Cicero. Neplést s caedo – sekám."]),
  v("censeo", "cēnsēre, cēnsuī, cēnsum", "cením, soudím, domnívám se", ["Ceterum censeo Carthaginem esse delendam.", "Ostatně soudím, že Kartágo musí být zničeno.", "Cato starší. Odtud cenzor, cenzura."]),
  n("cerebrum", "cerebrī n.", "mozek", ["Cerebrum hominis magnum est.", "Lidský mozek je velký.", "Odtud cerebrální."]),
  v("cingo", "cingere, cīnxī, cīnctum", "opásávám, obklopuji", ["Gladio se cingit.", "Opásává se mečem.", "Odtud cingulum – kněžský pás."]),
  v("circumvenio", "circumvenīre, circumvēnī, circumventum", "obkličuji, obcházím", ["Hostes nos circumveniunt.", "Nepřátelé nás obkličují."]),
  n("classis", "classis f.", "třída, loďstvo", ["Classis in portu est.", "Loďstvo je v přístavu.", "Odtud klasický, klasifikace."]),
  n("collegium", "collēgiī n.", "sbor, kolegium", ["Collegium cardinalium", "Kardinálské kolegium", "Odtud kolega, kolej."]),
  n("colonia", "colōniae f.", "osada, kolonie", ["Colonia Agrippina", "Kolonie Agrippina (Kolín nad Rýnem)", "Odtud kolonie, kolonizace."]),
  n("color", "colōris m.", "barva", ["Color albus est.", "Barva je bílá.", "Odtud kolorit, kolorovat."]),
  n("commemoratio", "commemorātiōnis f.", "připomínka, památka", ["Commemoratio omnium fidelium defunctorum", "Vzpomínka na všechny věrné zemřelé", "Dušičky, 2. listopadu."]),
  v("commendo", "commendāre, commendāvī, commendātum", "svěřuji, doporučuji", ["In manus tuas commendo spiritum meum.", "Do tvých rukou svěřuji svého ducha.", "Lk 23,46."]),
  n("commentarius", "commentāriī m.", "zápis, komentář", ["Commentarii de bello Gallico", "Zápisky o válce galské", "Caesar. Odtud komentář."]),
  v("communico", "commūnicāre, commūnicāvī, commūnicātum", "sděluji, dělím se", ["Gaudium cum amicis communico.", "Dělím se o radost s přáteli.", "Odtud komunikace."]),
  v("computo", "computāre, computāvī, computātum", "počítám", ["Dies computo.", "Počítám dny.", "Odtud computer, komputistika."]),
  n("condicio", "condiciōnis f.", "podmínka", ["Sine condicione", "Bez podmínky", "Odtud kondice."]),
  n("coniunctio", "coniūnctiōnis f.", "spojení, spojka", ["Et est coniunctio.", "Et je spojka.", "Odtud konjunkce."]),
  n("coniuratio", "coniūrātiōnis f.", "spiknutí", ["Coniuratio Catilinae", "Katilinovo spiknutí", "Sallustius o ní napsal spis."]),
  v("conor", "cōnārī, cōnātus sum", "pokouším se, snažím se", ["Conor intellegere.", "Snažím se porozumět."]),
  n("conscientia", "cōnscientiae f.", "vědomí, svědomí", ["Mea mihi conscientia pluris est.", "Mé svědomí je mi cennější.", "Cicero."]),
  n("consultatio", "cōnsultātiōnis f.", "porada", ["Consultatio longa erat.", "Porada byla dlouhá.", "Odtud konzultace."]),
  n("consultum", "cōnsultī n.", "usnesení, rozhodnutí", ["Senatus consultum", "Usnesení senátu", "Zkratka SC na římských nápisech."]),
  n("contextus", "contextūs m.", "souvislost, kontext", ["Verbum in contextu intellegitur.", "Slovo se chápe v souvislosti.", "Odtud kontext."]),
  n("copia", "cōpiae f.", "množství, zásoba", ["Magna copia frumenti", "Velká zásoba obilí", "Odtud kopie – původně hojnost opisů."]),
  n("correctio", "corrēctiōnis f.", "oprava, náprava", ["Correctio fraterna", "Bratrské napomenutí", "Odtud korektura, korekce."]),
  v("corrumpo", "corrumpere, corrūpī, corruptum", "kazím, porušuji", ["Pecunia mores corrumpit.", "Peníze kazí mravy.", "Odtud korupce."]),
  a("crudelis", "crūdēle", "krutý", ["Tyrannus crudelis erat.", "Tyran byl krutý.", "Odtud anglické cruel."]),
  o("cum – tum", "spojka", "jak – tak", ["Cum in bello, tum in pace", "Jak ve válce, tak v míru"]),
  v("decerno", "dēcernere, dēcrēvī, dēcrētum", "rozhoduji, nařizuji", ["Senatus bellum decrevit.", "Senát rozhodl o válce.", "Odtud dekret."]),
  n("decus", "decoris n.", "ozdoba, čest", ["Decus et gloria", "Čest a sláva"]),
  o("dies fastus", "diēs fāstus m.", "úřední, všední den", ["Hodie dies fastus est.", "Dnes je úřední den.", "Ve dny fasti se smělo soudit a jednat."]),
  o("dies nefastus", "diēs nefāstus m.", "sváteční den", ["Dies nefastus erat.", "Byl to sváteční den.", "Ve dny nefasti se nesmělo soudit."]),
  o("diligenter", "příslovce", "pečlivě, svědomitě", ["Diligenter laboro.", "Pracuji pečlivě.", "Odtud diligence – pečlivost."]),
  n("disputatio", "disputātiōnis f.", "rozprava, výklad", ["Disputatio de fide", "Rozprava o víře", "Odtud disputace."]),
  n("dissensio", "dissēnsiōnis f.", "neshoda, spor", ["Dissensio inter fratres", "Neshoda mezi bratry", "Odtud disent."]),
  v("dissero", "disserere, disseruī, dissertum", "rozmlouvám, vykládám", ["De amicitia disseruit.", "Pojednal o přátelství.", "Odtud disertace."]),
  v("dissimulo", "dissimulāre, dissimulāvī, dissimulātum", "zastírám, zatajuji", ["Iram dissimulo.", "Zastírám hněv.", "Odtud disimulace."]),
  n("divinitas", "dīvīnitātis f.", "božství", ["Divinitas Christi", "Božství Kristovo"]),
  n("documentum", "documentī n.", "naučení, doklad", ["Documentum fidei", "Doklad víry", "Odtud dokument."]),
  n("dominatus", "dominātūs m.", "panství, vláda", ["Dominatus Romanorum", "Panství Římanů", "Od dominus. Odtud dominát."]),
  a("egregius", "ēgregia, ēgregium", "vynikající", ["Vir egregius", "Vynikající muž", "Odtud anglické egregious."]),
  n("eloquentia", "ēloquentiae f.", "výmluvnost", ["Ciceronis eloquentia", "Ciceronova výmluvnost", "Odtud elokvence."]),
  v("expello", "expellere, expulī, expulsum", "vyháním, vypuzuji", ["Naturam expelles furca, tamen usque recurret.", "Vyžeň přírodu vidlemi, stejně se vrátí.", "Horatius."]),
  v("expono", "expōnere, exposuī, expositum", "vykládám, vystavuji", ["Magister regulam exponit.", "Učitel vykládá pravidlo.", "Odtud exponát, expozice."]),
  v("exprimo", "exprimere, expressī, expressum", "vytlačuji, vyjadřuji", ["Verbis sententiam exprimo.", "Slovy vyjadřuji myšlenku.", "Odtud exprese, expres."]),
  n("facinus", "facinoris n.", "čin, zločin", ["Facinus magnum", "Velký zločin"]),
  n("factio", "factiōnis f.", "strana, sdružení", ["Factio nobilium", "Strana šlechticů", "Odtud frakce."]),
  n("figura", "figūrae f.", "podoba, tvar", ["Figura pulchra", "Krásná postava", "Odtud figura, figurína."]),
  v("fingo", "fingere, fīnxī, fictum", "tvořím, vymýšlím", ["Hypotheses non fingo.", "Hypotézy nevymýšlím.", "Isaac Newton. Odtud fikce."]),
  v("fluo", "fluere, flūxī, flūxum", "teču, plynu", ["Omnia fluunt.", "Všechno plyne.", "Latinsky podle Hérakleitova panta rhei. Odtud fluidum."]),
  n("forum", "forī n.", "náměstí, tržiště", ["Forum Romanum", "Římské fórum", "Odtud fórum."]),
  a("frequens", "gen. frequentis", "četný, častý", ["Frequens in templo erat.", "Byl často v chrámu.", "Odtud frekvence."]),
  n("furor", "furōris m.", "zuřivost, šílenství", ["Furor Teutonicus", "Germánská zuřivost", "Lucanus. Odtud furore."]),
  n("gladiator", "gladiātōris m.", "gladiátor", ["Gladiator in arena pugnat.", "Gladiátor bojuje v aréně.", "Od gladius – meč."]),
  n("gustus", "gustūs m.", "chuť", ["Gustus vini bonus est.", "Chuť vína je dobrá.", "Odtud gusto, degustace."]),
  n("gutta", "guttae f.", "kapka", ["Gutta cavat lapidem.", "Kapka vyhloubí kámen.", "Ovidius. Odtud gutace."]),
  n("guttur", "gutturis n.", "hrdlo", ["Guttur siccum est.", "Hrdlo je vyschlé.", "Odtud gutturála – hrdelní hláska."]),
  n("hiberna", "hībernōrum n. pl.", "zimní tábor", ["Legiones in hibernis manent.", "Legie zůstávají v zimním táboře.", "Odtud hibernace."]),
  v("iacto", "iactāre, iactāvī, iactātum", "házím, chlubím se", ["Alea iacta est.", "Kostky jsou vrženy.", "Caesar u Rubikonu."]),
  v("ignoro", "ignōrāre, ignōrāvī, ignōrātum", "nevím, neznám", ["Ignoro, quid dicas.", "Nevím, co říkáš.", "Odtud ignorovat, ignorant."]),
  v("incendo", "incendere, incendī, incēnsum", "zapaluji", ["Urbem incenderunt.", "Zapálili město.", "Odtud incendium – požár."]),
  n("industria", "industriae f.", "píle, pracovitost", ["Industria et labore", "Pílí a prací", "Odtud industrie – průmysl."]),
  n("insigne", "īnsignis n.", "znak, odznak", ["Insignia regalia", "Královské odznaky", "Odtud insignie."]),
  v("instruo", "īnstruere, īnstrūxī, īnstrūctum", "zřizuji, vybavuji, poučuji", ["Aciem instruo.", "Šikuji bitevní řadu.", "Odtud instrukce, instrument."]),
  n("integritas", "integritātis f.", "neporušenost, poctivost", ["Integritas morum", "Bezúhonnost mravů", "Odtud integrita."]),
  v("invado", "invādere, invāsī, invāsum", "vpadám, napadám", ["Hostes urbem invaserunt.", "Nepřátelé vpadli do města.", "Odtud invaze."]),
  n("licentia", "licentiae f.", "dovolení, volnost", ["Licentia poetica", "Básnická volnost", "Odtud licence."]),
  v("ligo", "ligāre, ligāvī, ligātum", "svazuji, spojuji", ["Funem ligo.", "Svazuji provaz.", "Odtud liga, ligatura."]),
  n("linea", "līneae f.", "řádka, linka", ["Nulla dies sine linea.", "Ani den bez čáry.", "Plinius o malíři Apellovi. Odtud lineární."]),
  n("ludus", "lūdī m.", "hra, zábava", ["Ludus litterarius", "Základní škola", "Ludus znamená hra i škola."]),
  n("luxuria", "luxuriae f.", "přepych", ["Luxuria mores corrumpit.", "Přepych kazí mravy.", "Odtud luxusní."]),
  n("luxus", "luxūs m.", "přepych, nádhera", ["Luxus regius", "Královská nádhera", "Odtud luxus."]),
  n("macula", "maculae f.", "skvrna", ["Macula non est in te.", "Není na tobě poskvrny.", "Z mariánské antifony Tota pulchra es."]),
  n("magnitudo", "magnitūdinis f.", "velikost", ["Magnitudo animi", "Velkodušnost", "Odtud magnitudo zemětřesení."]),
  n("maiores", "maiōrum m. pl.", "předkové", ["Mos maiorum", "Zvyk předků", "Základ římské tradice."]),
  n("matrimonium", "mātrimōniī n.", "manželství", ["Sacramentum matrimonii", "Svátost manželství", "Od mater. Odtud matrimoniální."]),
  n("membrum", "membrī n.", "úd, člen", ["Membra corporis", "Údy těla", "Odtud membrána."]),
  v("metuo", "metuere, metuī", "bojím se, obávám se", ["Oderint, dum metuant.", "Ať nenávidí, jen když se bojí.", "Verš z Acciovy tragédie, oblíbený výrok Caliguly."]),
  v("misceo", "miscēre, miscuī, mixtum", "mísím, míchám", ["Vinum aqua misceo.", "Mísím víno s vodou.", "Odtud mixovat."]),
  a("mitis", "mīte", "mírný, vlídný", ["Discite a me, quia mitis sum.", "Učte se ode mne, neboť jsem tichý.", "Mt 11,29."]),
  v("monstro", "mōnstrāre, mōnstrāvī, mōnstrātum", "ukazuji", ["Viam monstro.", "Ukazuji cestu.", "Odtud monstrance a demonstrace."]),
  v("noto", "notāre, notāvī, notātum", "označuji, zapisuji", ["Nota bene!", "Dobře si všimni!", "Zkratka N. B. Odtud notace, notář."]),
  a("notus", "nōta, nōtum", "známý, slavný", ["Res nota est.", "Věc je známá.", "Odtud notorický."]),
  v("nudo", "nūdāre, nūdāvī, nūdātum", "obnažuji, svlékám", ["Arbores hieme nudatae sunt.", "Stromy jsou v zimě obnažené.", "Odtud nudismus."]),
  n("nummus", "nummī m.", "peníz, mince", ["Nummus aureus", "Zlatá mince", "Odtud numismatika."]),
  n("obses", "obsidis m./f.", "rukojmí", ["Obsides dederunt.", "Dali rukojmí."]),
  n("ops", "opis f. (pl. opēs)", "moc, pomoc; pl. bohatství", ["Opem fero.", "Přináším pomoc.", "Pl. opes = bohatství. Odtud opulentní."]),
  n("orator", "ōrātōris m.", "řečník", ["Cicero orator clarus erat.", "Cicero byl slavný řečník.", "Odtud oratorium."]),
  o("orbis terrarum", "orbis terrārum m.", "svět", ["Urbi et orbi terrarum", "Městu a celému světu", "Doslova okruh zemí."]),
  n("otium", "ōtiī n.", "volný čas, klid", ["Otium cum dignitate", "Čestný odpočinek", "Cicero."]),
  o("paenitentiam ago", "agere, ēgī, āctum", "činím pokání", ["Paenitentiam agite!", "Čiňte pokání!", "Mt 3,2."]),
  n("patientia", "patientiae f.", "trpělivost", ["Patientia vincit omnia.", "Trpělivost přemůže vše.", "Odtud pacient."]),
  v("perverto", "pervertere, pervertī, perversum", "převracím, ničím", ["Mores perverti sunt.", "Mravy jsou zkažené.", "Odtud perverzní."]),
  a("piger", "pigra, pigrum", "líný", ["Piger semper eget.", "Líný vždycky strádá."]),
  n("pompa", "pompae f.", "nádhera, okázalost", ["Pompa funebris", "Pohřební průvod", "Odtud pompa, pompézní."]),
  v("postulo", "postulāre, postulāvī, postulātum", "žádám, požaduji", ["Iustitiam postulamus.", "Požadujeme spravedlnost.", "Odtud postulát."]),
  n("praedicatio", "praedicātiōnis f.", "hlásání, kázání", ["Praedicatio Evangelii", "Hlásání evangelia", "Odtud predikace."]),
  n("principatus", "prīncipātūs m.", "první místo, vláda", ["Principatus Augusti", "Augustova vláda", "Odtud principát."]),
  v("privo", "prīvāre, prīvāvī, prīvātum", "zbavuji, olupuji", ["Vita privatus est.", "Byl zbaven života.", "Odtud privátní – soukromý."]),
  v("progredior", "prōgredī, prōgressus sum", "postupuji, pokračuji", ["Non progredi est regredi.", "Nepostupovat vpřed znamená couvat.", "Odtud progres."]),
  n("promissum", "prōmissī n.", "slib", ["Promissum servo.", "Dodržuji slib.", "Odtud promise (angl.)."]),
  v("queror", "querī, questus sum", "naříkám, stěžuji si", ["De fortuna queror.", "Stěžuji si na osud.", "Odtud kverulant."]),
  o("quin", "spojka", "proč ne?; že, aby ne", ["Quin venis?", "Proč nepřijdeš?", "Quin s indikativem = proč ne."]),
  v("rapio", "rapere, rapuī, raptum", "uchvacuji, unáším", ["Lupus ovem rapit.", "Vlk uchvacuje ovci.", "Odtud rapidní, dravec = raptor."]),
  n("reconciliatio", "reconciliātiōnis f.", "smíření", ["Sacramentum reconciliationis", "Svátost smíření"]),
  o("recte", "příslovce", "správně, dobře", ["Recte dicis.", "Říkáš správně.", "Od rectus. Odtud rektor."]),
  n("religio", "religiōnis f.", "náboženství", ["Libertas religionis", "Svoboda náboženství", "Odtud religiózní."]),
  v("revoco", "revocāre, revocāvī, revocātum", "volám zpět, odvolávám", ["Verba revocare non possum.", "Slova nemohu vzít zpět.", "Odtud revokace."]),
  n("rosarium", "rosāriī n.", "růženec", ["Rosarium oro.", "Modlím se růženec.", "Doslova růžová zahrada."]),
  n("sacrificium", "sacrificiī n.", "oběť", ["Sacrificium laudis", "Oběť chvály", "Žalm 50(49)."]),
  n("satisfactio", "satisfactiōnis f.", "zadostiučinění", ["Satisfactio pro peccatis", "Zadostiučinění za hříchy", "Odtud satisfakce."]),
  v("semino", "sēmināre, sēmināvī, sēminātum", "seji, osívám", ["Qui seminant in lacrimis, in exsultatione metent.", "Kdo rozsévají v slzách, sklízejí s jásotem.", "Žalm 126(125)."]),
  n("serva", "servae f.", "otrokyně, služka", ["Serva in villa laborat.", "Služka pracuje na statku.", "Ženský tvar od servus."]),
  n("sodalis", "sodālis m.", "druh, společník", ["Sodalis meus", "Můj druh", "Odtud sodalita – bratrstvo."]),
  n("statua", "statuae f.", "socha", ["Statua marmorea", "Mramorová socha", "Odtud statue."]),
  n("stipendium", "stīpendiī n.", "plat, žold", ["Stipendia peccati mors.", "Žold hříchu je smrt.", "Řím 6,23. Odtud stipendium."]),
  n("stirps", "stirpis f.", "kmen, rod, kořen", ["Stirps Iesse", "Kmen Jesse", "Odtud extirpace – vytržení s kořenem."]),
  v("suadeo", "suādēre, suāsī, suāsum", "radím, doporučuji", ["Pacem tibi suadeo.", "Radím ti mír.", "Odtud persvaze."]),
  n("successus", "successūs m.", "úspěch, zdar", ["Successus laborem sequitur.", "Úspěch následuje práci.", "Odtud anglické success."]),
  o("sursum", "příslovce", "vzhůru, nahoru", ["Oculos sursum tollo.", "Zvedám oči vzhůru.", "Sursum corda – vzhůru srdce (ze mše)."]),
  n("tectum", "tēctī n.", "střecha, příbytek", ["Sub tecto meo", "Pod mou střechou", "Od tego – kryji; odtud protekce."]),
  n("theatrum", "theātrī n.", "divadlo", ["Theatrum mundi", "Divadlo světa", "Odtud teatrální."]),
  n("theologus", "theologī m.", "teolog", ["Theologus de Deo disputat.", "Teolog pojednává o Bohu.", "Z řečtiny: theos + logos."]),
  v("traho", "trahere, trāxī, tractum", "táhnu, vleču", ["Trahimur omnes studio laudis.", "Všechny nás táhne touha po slávě.", "Cicero. Odtud traktor."]),
  n("universum", "ūniversī n.", "vesmír, svět", ["Universum infinitum est.", "Vesmír je nekonečný.", "Odtud univerzum."]),
  a("universus", "ūniversa, ūniversum", "veškerý, celý", ["Universa Ecclesia", "Celá Církev", "Odtud univerzita."]),
  n("usus", "ūsūs m.", "užívání, užitek", ["Usus magister est optimus.", "Praxe je nejlepší učitel.", "Odtud úzus."]),
  n("valetudo", "valētūdinis f.", "zdraví", ["Bona valetudo", "Dobré zdraví", "Od valeo."]),
  v("vasto", "vastāre, vastāvī, vastātum", "pustoším", ["Hostes agros vastant.", "Nepřátelé pustoší pole.", "Odtud devastace."]),
  v("verto", "vertere, vertī, versum", "obracím, otáčím", ["Vertit terga.", "Obrací se zády (dává se na útěk).", "Odtud verze, konverze."]),
  n("villa", "vīllae f.", "statek, vila", ["Villa rustica", "Venkovský statek", "Odtud vila."]),
]);
