import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 3", [
  v("annuntio", "annūntiāre, annūntiāvī, annūntiātum", "oznamuji, zvěstuji"),
  n("calix", "calicis m.", "kalich, pohár"),
  a("castus", "casta, castum", "čistý, bezúhonný"),
  v("colo", "colere, coluī, cultum", "obdělávám, pěstuji, ctím"),
  a("continuus", "continua, continuum", "souvislý, nepřetržitý"),
  n("dolor", "dolōris m.", "bolest, zármutek"),
  a("dubius", "dubia, dubium", "pochybný, nejistý"),
  a("durus", "dūra, dūrum", "tvrdý, krutý, přísný"),
  n("error", "errōris m.", "blud, omyl"),
  n("fama", "fāmae f.", "pověst, zpráva"),
  a("irregularis", "irrēgulāre", "nepravidelný"),
  o("magnopere", "příslovce", "velmi, velice"),
  v("manduco", "mandūcāre, mandūcāvī, mandūcātum", "jím"),
  n("meritum", "meritī n.", "zásluha, mzda"),
  n("munus", "mūneris n.", "úkol, úřad, dar"),
  a("necessarius", "necessāria, necessārium", "nutný, potřebný"),
  a("nonus", "nōna, nōnum", "devátý"),
  a("nullus", "nūlla, nūllum", "žádný"),
  n("nuntius", "nūntiī m.", "zpráva, posel"),
  n("odium", "odiī n.", "nenávist, odpor"),
  a("optimus", "optima, optimum", "nejlepší"),
  a("perpetuus", "perpetua, perpetuum", "ustavičný, trvalý, věčný"),
  v("persequor", "persequī, persecūtus sum", "pronásleduji, stíhám"),
  o("prae", "předložka + abl.", "před, pro, kvůli"),
  a("prior", "prius", "přednější, dřívější"),
  a("regularis", "rēgulāre", "pravidelný, řeholní"),
  n("responsum", "respōnsī n.", "odpověď, výrok"),
  a("tantus", "tanta, tantum", "tak veliký, takový"),
  o("utinam", "částice", "kéž, kéž by"),
  n("victima", "victimae f.", "obětní zvíře, oběť"),
  o("aliqui", "aliqua, aliquod (zájmeno)", "některý, nějaký"),
  o("aliquis", "aliquid (zájmeno)", "někdo, něco"),
  n("auctor", "auctōris m.", "původce, autor"),
  n("contritio", "contrītiōnis f.", "lítost"),
  n("creatura", "creātūrae f.", "stvoření, tvor"),
  a("decimus", "decima, decimum", "desátý"),
  v("desum", "deesse, dēfuī, dēfutūrus", "chybím, scházím"),
  v("dono", "dōnāre, dōnāvī, dōnātum", "daruji, odpouštím"),
  o("etsi", "spojka", "i když, ačkoli"),
  v("evenio", "ēvenīre, ēvēnī, ēventum", "vycházím, stávám se"),
  v("impedio", "impedīre, impedīvī, impedītum", "překážím, zdržuji"),
  a("infelix", "gen. īnfēlīcis", "nešťastný"),
  n("libertas", "lībertātis f.", "svoboda, volnost"),
  v("luceo", "lūcēre, lūxī", "svítím, skvím se"),
  o("quadraginta", "číslovka, neskl.", "čtyřicet"),
  o("quisquis", "quidquid (zájmeno)", "kdokoli, cokoli"),
  v("reddo", "reddere, reddidī, redditum", "vracím, dávám zpět"),
  v("refero", "referre, rettulī, relātum", "nesu zpět, oznamuji"),
  n("requies", "requiētis f.", "klid, odpočinek"),
  n("sacramentum", "sacrāmentī n.", "přísaha, svátost"),
  o("sponte", "příslovce", "dobrovolně, sám od sebe"),
  n("testimonium", "testimōniī n.", "svědectví, důkaz"),
  n("timor", "timōris m.", "bázeň, strach"),
  n("unitas", "ūnitātis f.", "jednota, jednotka"),
  n("viaticum", "viāticī n.", "cestovné, pokrm na cestu"),
  v("accuso", "accūsāre, accūsāvī, accūsātum", "žaluji, obviňuji"),
  v("administro", "administrāre, administrāvī, administrātum", "obstarávám, spravuji, řídím"),
  n("altare", "altāris n.", "oltář"),
  v("erigo", "ērigere, ērēxī, ērēctum", "vztyčuji, pozvedám"),
  v("floreo", "flōrēre, flōruī", "kvetu, vzkvétám"),
  v("genuflecto", "genūflectere, genūflexī, genūflexum", "klekám, poklekám"),
  n("innocentia", "innocentiae f.", "nevinnost, bezúhonnost"),
  v("offero", "offerre, obtulī, oblātum", "podávám, nabízím, obětuji"),
  v("placeo", "placēre, placuī", "líbím se"),
  v("proficio", "prōficere, prōfēcī, prōfectum", "pokračuji, prospívám"),
  a("purus", "pūra, pūrum", "čistý, bezúhonný"),
  n("regio", "regiōnis f.", "směr, kraj, území"),
  o("semel", "příslovce", "jednou"),
  o("uterque", "utraque, utrumque (zájmeno)", "oba, jeden i druhý"),
  v("utor", "ūtī, ūsus sum (+ abl.)", "užívám, používám"),
  a("amarus", "amāra, amārum", "hořký, trpký"),
  o("ambo", "ambae, ambō (číslovka)", "oba"),
  o("an", "tázací částice", "či, zda"),
  v("assum", "adesse, affuī, affutūrus", "jsem přítomen, pomáhám"),
  v("conficio", "cōnficere, cōnfēcī, cōnfectum", "zhotovuji, dokončuji"),
  n("crimen", "crīminis n.", "zločin, vina"),
  v("divido", "dīvidere, dīvīsī, dīvīsum", "odděluji, rozděluji"),
  v("doleo", "dolēre, doluī, dolitūrus", "cítím bolest, lituji"),
  o("dum", "spojka", "zatímco, dokud"),
  a("duodecimus", "duodecima, duodecimum", "dvanáctý"),
  n("eques", "equitis m.", "jezdec, rytíř"),
  v("moveo", "movēre, mōvī, mōtum", "hýbám, pohybuji, dojímám"),
  n("paradisus", "paradīsī m.", "zahrada, ráj"),
  n("piscis", "piscis m.", "ryba"),
  v("praesum", "praeesse, praefuī, praefutūrus", "jsem v čele, řídím"),
  v("prosum", "prōdesse, prōfuī, prōfutūrus", "prospívám, pomáhám"),
  v("puto", "putāre, putāvī, putātum", "domnívám se, myslím"),
  o("quando", "příslovce", "kdy, když"),
  o("quot", "neskl.", "kolik"),
  n("socius", "sociī m.", "druh, společník, spojenec"),
  o("tot", "neskl.", "tolik"),
  v("abnego", "abnegāre, abnegāvī, abnegātum", "odpírám, zapírám"),
  v("aggredior", "aggredī, aggressus sum", "přistupuji, napadám"),
  n("amicitia", "amīcitiae f.", "přátelství"),
  o("circum", "předložka + akuz.", "kolem, okolo"),
  v("coepi", "coepisse, coeptum", "začal jsem"),
  v("confligo", "cōnflīgere, cōnflīxī, cōnflīctum", "srážím se, zápasím"),
  v("conservo", "cōnservāre, cōnservāvī, cōnservātum", "zachovávám, uchovávám"),
  v("eligo", "ēligere, ēlēgī, ēlēctum", "vybírám, volím"),
  o("erga", "předložka + akuz.", "vůči, k"),
  v("fruor", "fruī, fruitūrus (+ abl.)", "užívám, těším se z"),
  v("iaceo", "iacēre, iacuī", "ležím"),
  o("igitur", "spojka", "tedy"),
  v("intellego", "intellegere, intellēxī, intellēctum", "poznávám, chápu, rozumím"),
  v("malo", "mālle, māluī", "raději chci"),
  v("memini", "meminisse", "pamatuji se"),
  n("monumentum", "monumentī n.", "památka, pomník"),
  v("nosco", "nōscere, nōvī, nōtum", "poznávám; perf. znám"),
  o("ob", "předložka + akuz.", "před, kvůli"),
  v("odi", "ōdisse, ōsūrus", "nenávidím"),
  a("paschalis", "paschāle", "velikonoční"),
  v("praedico", "praedīcere, praedīxī, praedictum", "předpovídám, varuji"),
  v("reconcilio", "reconciliāre, reconciliāvī, reconciliātum", "smiřuji, obnovuji"),
  v("regno", "rēgnāre, rēgnāvī, rēgnātum", "kraluji, vládnu"),
  n("sabbatum", "sabbatī n.", "sobota, sabat"),
  a("varius", "varia, varium", "rozličný, rozmanitý"),
  n("vestis", "vestis f.", "šat, oděv"),
  v("affero", "afferre, attulī, allātum", "donáším, oznamuji"),
  n("autumnus", "autumnī m.", "podzim"),
  o("bis", "číselné příslovce", "dvakrát"),
  n("capitulum", "capitulī n.", "kapitola, kapitula"),
  n("circulus", "circulī m.", "kruh, okruh"),
  v("confero", "cōnferre, contulī, collātum", "snáším, srovnávám, uděluji"),
  v("designo", "dēsīgnāre, dēsīgnāvī, dēsīgnātum", "označuji, určuji"),
  n("disciplina", "disciplīnae f.", "učení, nauka, kázeň"),
  a("duodevicesimus", "duodēvīcēsima, duodēvīcēsimum", "osmnáctý"),
  o("duodeviginti", "číslovka, neskl.", "osmnáct"),
  v("explico", "explicāre, explicāvī, explicātum", "rozvinuji, vysvětluji"),
  n("feria", "fēriae f.", "den, všední den"),
  n("hebdomas", "hebdomadis f.", "sedmička, týden"),
  v("lapido", "lapidāre, lapidāvī, lapidātum", "kamenuji"),
  n("lapis", "lapidis m.", "kámen, milník"),
  n("martyr", "martyris m.", "svědek, mučedník"),
  n("mensis", "mēnsis m.", "měsíc"),
  n("nativitas", "nātīvitātis f.", "narození, Vánoce"),
  o("novem", "číslovka, neskl.", "devět"),
  o("octo", "číslovka, neskl.", "osm"),
  a("opportunus", "opportūna, opportūnum", "příhodný, vhodný"),
  v("praetereo", "praeterīre, praeteriī, praeteritum", "míjím, opomíjím"),
  v("propono", "prōpōnere, prōposuī, prōpositum", "předkládám, navrhuji"),
  n("quadragesima", "quadrāgēsimae f.", "čtyřicetina"),
  o("quater", "číselné příslovce", "čtyřikrát"),
  o("quindecim", "číslovka, neskl.", "patnáct"),
  v("redeo", "redīre, rediī, reditum", "vracím se"),
  o("sedecim", "číslovka, neskl.", "šestnáct"),
  o("sex", "číslovka, neskl.", "šest"),
  n("tabula", "tabulae f.", "deska, tabule, listina"),
  v("tego", "tegere, tēxī, tēctum", "kryji, přikrývám"),
  o("ter", "číselné příslovce", "třikrát"),
  o("tredecim", "číslovka, neskl.", "třináct"),
  o("triginta", "číslovka, neskl.", "třicet"),
  n("ver", "vēris n.", "jaro"),
  a("vicesimus", "vīcēsima, vīcēsimum", "dvacátý"),
  o("viginti", "číslovka, neskl.", "dvacet"),
  v("accidit", "accidere, accidit (neosobní)", "stává se, přihází se"),
  v("accido", "accidere, accidī", "dopadám, nastávám"),
  n("affinitas", "affīnitātis f.", "sousedství, příbuzenství"),
  a("carnalis", "carnāle", "tělesný"),
  v("circumdo", "circumdare, circumdedī, circumdatum", "obklopuji, obkličuji"),
  a("communis", "commūne", "společný, obecný"),
  n("concursus", "concursūs m.", "sběh, srocení, srážka"),
  v("congredior", "congredī, congressus sum", "setkávám se, utkávám se"),
  n("consanguinitas", "cōnsanguinitātis f.", "pokrevní příbuzenství"),
  n("constantia", "cōnstantiae f.", "stálost, vytrvalost"),
  v("constat", "cōnstāre, cōnstitit (neosobní)", "je známo, je zjištěno"),
  v("contero", "conterere, contrīvī, contrītum", "roztírám, ničím"),
  v("contingit", "contingere, contigit (neosobní)", "stává se, daří se"),
  v("contingo", "contingere, contigī, contāctum", "dotýkám se, dostihuji"),
  v("convenio", "convenīre, convēnī, conventum", "scházím se, shoduji se"),
  n("cultura", "cultūrae f.", "pěstění, vzdělávání, uctívání"),
  v("decet", "decēre, decuit (neosobní)", "sluší se, hodí se"),
  v("deduco", "dēdūcere, dēdūxī, dēductum", "svádím, odvádím, odvozuji"),
  v("ēdo", "ēdere, ēdidī, ēditum", "vydávám, vyhlašuji"),
  n("flos", "flōris m.", "květ, květina"),
  n("gubernaculum", "gubernāculī n.", "kormidlo, řízení"),
  n("imperator", "imperātōris m.", "velitel, císař"),
  n("iniuria", "iniūriae f.", "křivda, bezpráví"),
  n("iustificatio", "iūstificātiōnis f.", "ospravedlnění"),
  v("noceo", "nocēre, nocuī, nocitum", "škodím"),
  v("oportet", "oportēre, oportuit (neosobní)", "je třeba, sluší se"),
  n("ornamentum", "ōrnāmentī n.", "ozdoba, výzdoba"),
  v("pateo", "patēre, patuī", "jsem otevřen, rozkládám se"),
  n("scriptor", "scrīptōris m.", "písař, spisovatel"),
  v("secedo", "sēcēdere, sēcessī, sēcessum", "odcházím, vzdaluji se"),
  n("testamentum", "testāmentī n.", "závěť, smlouva, zákon"),
  n("tribulatio", "tribulātiōnis f.", "trápení, útisk"),
  n("voluptas", "voluptātis f.", "rozkoš, slast"),
  n("aeternitas", "aeternitātis f.", "věčnost"),
  n("argentum", "argentī n.", "stříbro"),
  v("consulo", "cōnsulere, cōnsuluī, cōnsultum", "radím se, pečuji"),
  v("frango", "frangere, frēgī, frāctum", "lámu, rozbíjím"),
  a("patiens", "gen. patientis", "trpělivý, vytrvalý"),
  n("praemium", "praemiī n.", "odměna"),
  n("proverbium", "prōverbiī n.", "přísloví, podobenství"),
  n("quies", "quiētis f.", "klid, pokoj, odpočinek"),
  n("status", "statūs m.", "postavení, stav"),
  v("appropinquo", "appropinquāre, appropinquāvī, appropinquātum", "přibližuji se, blížím se"),
  v("arbitror", "arbitrārī, arbitrātus sum", "soudím, domnívám se"),
  v("ieiuno", "iēiūnāre, iēiūnāvī, iēiūnātum", "postím se"),
  n("morbus", "morbī m.", "nemoc"),
  o("necesse est", "neosobní výraz", "je nutno, je třeba"),
  v("neglego", "neglegere, neglēxī, neglēctum", "nedbám, zanedbávám"),
  v("nego", "negāre, negāvī, negātum", "popírám, zapírám"),
  o("opus est", "neosobní výraz (+ abl.)", "je zapotřebí"),
  n("paupertas", "paupertātis f.", "chudoba"),
  v("praebeo", "praebēre, praebuī, praebitum", "poskytuji, ukazuji"),
  a("reliquus", "reliqua, reliquum", "zbývající, ostatní"),
  v("remitto", "remittere, remīsī, remissum", "posílám zpět, odpouštím"),
  v("solvo", "solvere, solvī, solūtum", "rozvazuji, osvobozuji, platím"),
  n("turba", "turbae f.", "zmatek, dav, zástup"),
  v("veto", "vetāre, vetuī, vetitum", "zakazuji"),
  o("aliquot", "nesklonné", "několik"),
  n("aspectus", "aspectūs m.", "pohled, vzhled"),
  n("assumptio", "assumptiōnis f.", "přijetí, nanebevzetí"),
  a("avarus", "avāra, avārum", "lakomý"),
  n("avis", "avis f.", "pták"),
  n("calamitas", "calamitātis f.", "pohroma, neštěstí"),
  n("calcar", "calcāris n.", "ostruha, pobídka"),
  n("calculus", "calculī m.", "kamínek, počet"),
  n("campus", "campī m.", "pole, pláň"),
  a("causalis", "causāle", "příčinný"),
  v("cedo", "cēdere, cessī, cessum", "kráčím, ustupuji"),
  v("censeo", "cēnsēre, cēnsuī, cēnsum", "cením, soudím, domnívám se"),
  n("cerebrum", "cerebrī n.", "mozek"),
  v("cingo", "cingere, cīnxī, cīnctum", "opásávám, obklopuji"),
  v("circumvenio", "circumvenīre, circumvēnī, circumventum", "obkličuji, obcházím"),
  n("classis", "classis f.", "třída, loďstvo"),
  n("collegium", "collēgiī n.", "sbor, kolegium"),
  n("colonia", "colōniae f.", "osada, kolonie"),
  n("color", "colōris m.", "barva"),
  n("commemoratio", "commemorātiōnis f.", "připomínka, památka"),
  v("commendo", "commendāre, commendāvī, commendātum", "svěřuji, doporučuji"),
  n("commentarius", "commentāriī m.", "zápis, komentář"),
  v("communico", "commūnicāre, commūnicāvī, commūnicātum", "sděluji, dělím se"),
  v("computo", "computāre, computāvī, computātum", "počítám"),
  n("condicio", "condiciōnis f.", "podmínka"),
  n("coniunctio", "coniūnctiōnis f.", "spojení, spojka"),
  n("coniuratio", "coniūrātiōnis f.", "spiknutí"),
  v("conor", "cōnārī, cōnātus sum", "pokouším se, snažím se"),
  n("conscientia", "cōnscientiae f.", "vědomí, svědomí"),
  n("consultatio", "cōnsultātiōnis f.", "porada"),
  n("consultum", "cōnsultī n.", "usnesení, rozhodnutí"),
  n("contextus", "contextūs m.", "souvislost, kontext"),
  n("copia", "cōpiae f.", "množství, zásoba"),
  n("correctio", "corrēctiōnis f.", "oprava, náprava"),
  v("corrumpo", "corrumpere, corrūpī, corruptum", "kazím, porušuji"),
  a("crudelis", "crūdēle", "krutý"),
  o("cum – tum", "spojka", "jak – tak"),
  v("decerno", "dēcernere, dēcrēvī, dēcrētum", "rozhoduji, nařizuji"),
  n("decus", "decoris n.", "ozdoba, čest"),
  o("dies fastus", "diēs fāstus m.", "úřední, všední den"),
  o("dies nefastus", "diēs nefāstus m.", "sváteční den"),
  o("diligenter", "příslovce", "pečlivě, svědomitě"),
  n("disputatio", "disputātiōnis f.", "rozprava, výklad"),
  n("dissensio", "dissēnsiōnis f.", "neshoda, spor"),
  v("dissero", "disserere, disseruī, dissertum", "rozmlouvám, vykládám"),
  v("dissimulo", "dissimulāre, dissimulāvī, dissimulātum", "zastírám, zatajuji"),
  n("divinitas", "dīvīnitātis f.", "božství"),
  n("documentum", "documentī n.", "naučení, doklad"),
  n("dominatus", "dominātūs m.", "panství, vláda"),
  a("egregius", "ēgregia, ēgregium", "vynikající"),
  n("eloquentia", "ēloquentiae f.", "výmluvnost"),
  v("expello", "expellere, expulī, expulsum", "vyháním, vypuzuji"),
  v("expono", "expōnere, exposuī, expositum", "vykládám, vystavuji"),
  v("exprimo", "exprimere, expressī, expressum", "vytlačuji, vyjadřuji"),
  n("facinus", "facinoris n.", "čin, zločin"),
  n("factio", "factiōnis f.", "strana, sdružení"),
  n("figura", "figūrae f.", "podoba, tvar"),
  v("fingo", "fingere, fīnxī, fictum", "tvořím, vymýšlím"),
  v("fluo", "fluere, flūxī, flūxum", "teču, plynu"),
  n("forum", "forī n.", "náměstí, tržiště"),
  a("frequens", "gen. frequentis", "četný, častý"),
  n("furor", "furōris m.", "zuřivost, šílenství"),
  n("gladiator", "gladiātōris m.", "gladiátor"),
  n("gustus", "gustūs m.", "chuť"),
  n("gutta", "guttae f.", "kapka"),
  n("guttur", "gutturis n.", "hrdlo"),
  n("hiberna", "hībernōrum n. pl.", "zimní tábor"),
  v("iacto", "iactāre, iactāvī, iactātum", "házím, chlubím se"),
  v("ignoro", "ignōrāre, ignōrāvī, ignōrātum", "nevím, neznám"),
  v("incendo", "incendere, incendī, incēnsum", "zapaluji"),
  n("industria", "industriae f.", "píle, pracovitost"),
  n("insigne", "īnsignis n.", "znak, odznak"),
  v("instruo", "īnstruere, īnstrūxī, īnstrūctum", "zřizuji, vybavuji, poučuji"),
  n("integritas", "integritātis f.", "neporušenost, poctivost"),
  v("invado", "invādere, invāsī, invāsum", "vpadám, napadám"),
  n("licentia", "licentiae f.", "dovolení, volnost"),
  v("ligo", "ligāre, ligāvī, ligātum", "svazuji, spojuji"),
  n("linea", "līneae f.", "řádka, linka"),
  n("ludus", "lūdī m.", "hra, zábava"),
  n("luxuria", "luxuriae f.", "přepych"),
  n("luxus", "luxūs m.", "přepych, nádhera"),
  n("macula", "maculae f.", "skvrna"),
  n("magnitudo", "magnitūdinis f.", "velikost"),
  n("maiores", "maiōrum m. pl.", "předkové"),
  n("matrimonium", "mātrimōniī n.", "manželství"),
  n("membrum", "membrī n.", "úd, člen"),
  v("metuo", "metuere, metuī", "bojím se, obávám se"),
  v("misceo", "miscēre, miscuī, mixtum", "mísím, míchám"),
  a("mitis", "mīte", "mírný, vlídný"),
  v("monstro", "mōnstrāre, mōnstrāvī, mōnstrātum", "ukazuji"),
  v("noto", "notāre, notāvī, notātum", "označuji, zapisuji"),
  a("notus", "nōta, nōtum", "známý, slavný"),
  v("nudo", "nūdāre, nūdāvī, nūdātum", "obnažuji, svlékám"),
  n("nummus", "nummī m.", "peníz, mince"),
  n("obses", "obsidis m./f.", "rukojmí"),
  n("ops", "opis f. (pl. opēs)", "moc, pomoc; pl. bohatství"),
  n("orator", "ōrātōris m.", "řečník"),
  o("orbis terrarum", "orbis terrārum m.", "svět"),
  n("otium", "ōtiī n.", "volný čas, klid"),
  o("paenitentiam ago", "agere, ēgī, āctum", "činím pokání"),
  n("patientia", "patientiae f.", "trpělivost"),
  v("perverto", "pervertere, pervertī, perversum", "převracím, ničím"),
  a("piger", "pigra, pigrum", "líný"),
  n("pompa", "pompae f.", "nádhera, okázalost"),
  v("postulo", "postulāre, postulāvī, postulātum", "žádám, požaduji"),
  n("praedicatio", "praedicātiōnis f.", "hlásání, kázání"),
  n("principatus", "prīncipātūs m.", "první místo, vláda"),
  v("privo", "prīvāre, prīvāvī, prīvātum", "zbavuji, olupuji"),
  v("progredior", "prōgredī, prōgressus sum", "postupuji, pokračuji"),
  n("promissum", "prōmissī n.", "slib"),
  v("queror", "querī, questus sum", "naříkám, stěžuji si"),
  o("quin", "spojka", "proč ne?; že, aby ne"),
  v("rapio", "rapere, rapuī, raptum", "uchvacuji, unáším"),
  n("reconciliatio", "reconciliātiōnis f.", "smíření"),
  o("recte", "příslovce", "správně, dobře"),
  n("religio", "religiōnis f.", "náboženství"),
  v("revoco", "revocāre, revocāvī, revocātum", "volám zpět, odvolávám"),
  n("rosarium", "rosāriī n.", "růženec"),
  n("sacrificium", "sacrificiī n.", "oběť"),
  n("satisfactio", "satisfactiōnis f.", "zadostiučinění"),
  v("semino", "sēmināre, sēmināvī, sēminātum", "seji, osívám"),
  n("serva", "servae f.", "otrokyně, služka"),
  n("sodalis", "sodālis m.", "druh, společník"),
  n("statua", "statuae f.", "socha"),
  n("stipendium", "stīpendiī n.", "plat, žold"),
  n("stirps", "stirpis f.", "kmen, rod, kořen"),
  v("suadeo", "suādēre, suāsī, suāsum", "radím, doporučuji"),
  n("successus", "successūs m.", "úspěch, zdar"),
  o("sursum", "příslovce", "vzhůru, nahoru"),
  n("tectum", "tēctī n.", "střecha, příbytek"),
  n("theatrum", "theātrī n.", "divadlo"),
  n("theologus", "theologī m.", "teolog"),
  v("traho", "trahere, trāxī, tractum", "táhnu, vleču"),
  n("universum", "ūniversī n.", "vesmír, svět"),
  a("universus", "ūniversa, ūniversum", "veškerý, celý"),
  n("usus", "ūsūs m.", "užívání, užitek"),
  n("valetudo", "valētūdinis f.", "zdraví"),
  v("vasto", "vastāre, vastāvī, vastātum", "pustoším"),
  v("verto", "vertere, vertī, versum", "obracím, otáčím"),
  n("villa", "vīllae f.", "statek, vila"),
]);
