import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 4", [
  o("eleison", "nesklonné (řec.)", "smiluj se"),
  n("Christus", "Christī m.", "Kristus, Pomazaný"),
  o("Kyrie", "nesklonné (řec.)", "Pane"),
  o("is", "ea, id (gen. eius)", "on, ona, ono; ten"),
  a("excelsus", "excelsa, excelsum", "vysoký; pl. výsosti"),
  o("alleluia", "nesklonné (hebr.)", "aleluja, chvalte Pána"),
  o("-que", "spojka (příklonka)", "a"),
  o("hosanna", "nesklonné (hebr.)", "hosana, sláva"),
  v("adoro", "adōrāre, adōrāvī, adōrātum", "klaním se, uctívám"),
  n("missa", "missae f.", "mše"),
  a("unigenitus", "ūnigenita, ūnigenitum", "jednorozený"),
  n("genetrix", "genetrīcis f.", "rodička, matka"),
  v("quaeso", "nedostatkové; pl. quaesumus", "prosím"),
  n("angelus", "angelī m.", "anděl"),
  a("fidelis", "fidēle", "věrný; věřící"),
  o("sabaoth", "nesklonné (hebr.)", "zástupů"),
  a("misericors", "gen. misericordis", "milosrdný"),
  n("archangelus", "archangelī m.", "archanděl"),
  v("dignor", "dignārī, dignātus sum", "ráčím, uznávám za hodna"),
  v("concelebro", "concelebrāre, concelebrāvī, concelebrātum", "společně slavím"),
  v("tremo", "tremere, tremuī", "třesu se, chvěji se"),
  v("conglorifico", "conglōrificāre, -āvī, -ātum", "spoluoslavuji"),
  n("sponsus", "spōnsī m.", "snoubenec, ženich"),
  a("sempiternus", "sempiterna, sempiternum", "věčný, ustavičný"),
  n("iuventus", "iuventūtis f.", "mládí"),
  o("quoque", "příslovce", "také, i"),
  o("seraphim", "nesklonné (hebr.)", "serafové"),
  n("exsultatio", "exsultātiōnis f.", "plesání, jásot"),
  n("confessio", "cōnfessiōnis f.", "vyznání"),
  o("vero", "příslovce", "však, vskutku"),
  v("respicio", "respicere, respexī, respectum", "shlížím, ohlížím se"),
  v("infundo", "īnfundere, īnfūdī, īnfūsum", "vlévám"),
  n("vas", "vāsis n.", "nádoba"),
  v("laetifico", "laetificāre, laetificāvī, laetificātum", "obveseluji, těším"),
  n("dominatio", "dominātiōnis f.", "panstvo, vláda"),
  v("deprecor", "dēprecārī, dēprecātus sum", "prosím, vyprošuji"),
  a("supplex", "gen. supplicis", "pokorně prosící"),
  n("intercessio", "intercessiōnis f.", "přímluva"),
  o("ecce", "citoslovce", "hle, aj"),
  n("maiestas", "maiestātis f.", "velebnost, majestát"),
  a("salvus", "salva, salvum", "zachráněný, spasený"),
  n("laus", "laudis f.", "chvála"),
  a("gloriosus", "glōriōsa, glōriōsum", "slavný"),
  v("laetor", "laetārī, laetātus sum", "raduji se"),
  v("praesto", "praestāre, praestitī, praestitum", "poskytuji, uděluji"),
  n("famulus", "famulī m.", "služebník"),
  a("infirmus", "īnfirma, īnfirmum", "slabý, nemocný"),
  n("genitor", "genitōris m.", "otec, rodič"),
  n("chorus", "chorī m.", "sbor, kůr"),
  v("emitto", "ēmittere, ēmīsī, ēmissum", "vysílám"),
  v("introeo", "introīre, introiī, introitum", "vcházím, vstupuji"),
  o("quare", "příslovce", "proč"),
  o("adhuc", "příslovce", "dosud, ještě"),
  n("indulgentia", "indulgentiae f.", "shovívavost, odpuštění"),
  n("hymnus", "hymnī m.", "chvalozpěv, hymnus"),
  a("invisibilis", "invīsibile", "neviditelný"),
  n("apostolus", "apostolī m.", "apoštol"),
  v("reparo", "reparāre, reparāvī, reparātum", "obnovuji, napravuji"),
  o("quidem", "příslovce", "sice, ovšem"),
  v("effundo", "effundere, effūdī, effūsum", "vylévám, prolévám"),
  o("apud", "předložka + akuz.", "u, při"),
  n("refugium", "refugiī n.", "útočiště"),
  v("lavo", "lavāre, lāvī, lautum", "myji, omývám"),
  o("devote", "příslovce", "zbožně"),
  v("accendo", "accendere, accendī, accēnsum", "zapaluji, rozněcuji"),
  n("praesidium", "praesidiī n.", "ochrana, záštita"),
  n("speculum", "speculī m.", "zrcadlo"),
  n("turris", "turris f.", "věž"),
  n("custos", "custōdis m.", "strážce"),
  n("rector", "rēctōris m.", "správce, vládce"),
  v("perduco", "perdūcere, perdūxī, perductum", "přivádím, dovádím"),
  n("introitus", "introitūs m.", "vstup, introit"),
  v("formo", "fōrmāre, fōrmāvī, fōrmātum", "tvořím, utvářím"),
  v("aspergo", "aspergere, aspersī, aspersum", "kropím"),
  v("pervenio", "pervenīre, pervēnī, perventum", "dospívám, docházím"),
  o("iste", "ista, istud", "tento, ten"),
  n("princeps", "prīncipis m.", "kníže, vládce"),
  n("passio", "passiōnis f.", "utrpení"),
  v("veneror", "venerārī, venerātus sum", "uctívám"),
  a("spiritualis", "spīrituāle", "duchovní"),
  v("discerno", "discernere, discrēvī, discrētum", "rozlišuji, rozsuzuji"),
  v("adduco", "addūcere, addūxī, adductum", "přivádím"),
  n("tabernaculum", "tabernāculī n.", "stan, svatostánek"),
  n("cithara", "citharae f.", "citera, harfa"),
  v("conturbo", "conturbāre, conturbāvī, conturbātum", "znepokojuji, rmoutím"),
  n("vultus", "vultūs m.", "tvář, obličej"),
  n("adiutorium", "adiūtōriī n.", "pomoc"),
  n("absolutio", "absolūtiōnis f.", "rozhřešení"),
  v("converto", "convertere, convertī, conversum", "obracím"),
  n("clamor", "clāmōris m.", "křik, volání"),
  n("sequentia", "sequentiae f.", "sekvence"),
  a("consubstantialis", "cōnsubstantiāle", "soupodstatný"),
  o("simul", "příslovce", "zároveň, spolu"),
  a("apostolicus", "apostolica, apostolicum", "apoštolský"),
  n("offertorium", "offertōriī n.", "obětování, ofertorium"),
  n("utilitas", "ūtilitātis f.", "užitek, prospěch"),
  n("secreta", "sēcrētae f.", "tichá modlitba"),
  v("admitto", "admittere, admīsī, admissum", "připouštím"),
  n("singularitas", "singulāritātis f.", "jedinost"),
  n("differentia", "differentiae f.", "rozdíl"),
  n("discretio", "discrētiōnis f.", "rozlišení"),
  n("deitas", "deitātis f.", "božství"),
  v("iustifico", "iūstificāre, iūstificāvī, iūstificātum", "ospravedlňuji"),
  a("impius", "impia, impium", "bezbožný"),
  o("prope", "příslovce; předložka + akuz.", "blízko"),
  n("immortalitas", "immortālitātis f.", "nesmrtelnost"),
  a("manifestus", "manifesta, manifestum", "zjevný, zřejmý"),
  v("appareo", "appārēre, appāruī, appāritum", "zjevuji se, ukazuji se"),
  v("cerno", "cernere, crēvī, crētum", "vidím, rozeznávám"),
  v("elevo", "ēlevāre, ēlevāvī, ēlevātum", "pozvedám"),
  n("thronus", "thronī m.", "trůn"),
  n("miseratio", "miserātiōnis f.", "slitování"),
  a("hodiernus", "hodierna, hodiernum", "dnešní"),
  n("adoptio", "adoptiōnis f.", "přijetí za vlastní"),
  o("quapropter", "příslovce", "proto"),
  v("profundo", "prōfundere, prōfūdī, prōfūsum", "vylévám, rozlévám"),
  n("institutio", "īnstitūtiōnis f.", "ustanovení, poučení"),
  n("postcommunio", "postcommūniōnis f.", "modlitba po přijímání"),
  n("evangelium", "ēvangeliī n.", "evangelium"),
  v("perhibeo", "perhibēre, perhibuī, perhibitum", "vydávám (svědectví)"),
  n("dulcedo", "dulcēdinis f.", "sladkost"),
  n("prex", "precis f. (obv. pl. precēs)", "prosba, modlitba"),
  a("benignus", "benigna, benignum", "dobrotivý, laskavý"),
  n("proelium", "proeliī n.", "boj, bitva"),
  n("nequitia", "nēquitiae f.", "zlovolnost, nešlechetnost"),
  n("infernus", "īnfernī m.", "peklo, podsvětí"),
  n("nix", "nivis f.", "sníh"),
  v("foveo", "fovēre, fōvī, fōtum", "hřeji, opatruji"),
  v("visito", "vīsitāre, vīsitāvī, vīsitātum", "navštěvuji"),
  v("egredior", "ēgredī, ēgressus sum", "vycházím"),
  n("latus", "lateris n.", "bok, strana"),
  a("dexter", "dext(e)ra, dext(e)rum", "pravý"),
  o("cherubim", "nesklonné (hebr.)", "cherubové"),
  n("iubilum", "iūbilī n.", "jásot, plesání"),
  a("incessabilis", "incessābile", "neustávající"),
  a("immensus", "immēnsa, immēnsum", "nezměrný"),
  a("unicus", "ūnica, ūnicum", "jediný"),
  n("uterus", "uterī m.", "lůno, život"),
  v("numero", "numerāre, numerāvī, numerātum", "počítám"),
  n("hereditas", "hērēditātis f.", "dědictví"),
  o("usque", "příslovce", "až, stále"),
  o("quemadmodum", "příslovce", "jak, jakým způsobem"),
  v("confundo", "cōnfundere, cōnfūdī, cōnfūsum", "zahanbuji, mátu"),
  n("firmamentum", "firmāmentī n.", "obloha, opora"),
  n("bonitas", "bonitātis f.", "dobrota"),
  a("infinitus", "īnfīnīta, īnfīnītum", "nekonečný"),
  n("thesaurus", "thēsaurī m.", "poklad"),
  v("exoro", "exōrāre, exōrāvī, exōrātum", "vyprošuji"),
  n("hostia", "hostiae f.", "oběť, hostie"),
  v("premo", "premere, pressī, pressum", "tisknu, tížím"),
  a("hostilis", "hostīle", "nepřátelský"),
  a("trinus", "trīna, trīnum", "trojí"),
  n("terminus", "terminī m.", "hranice, konec"),
  v("pango", "pangere, pepigī, pāctum", "opěvuji, skládám"),
  a("pretiosus", "pretiōsa, pretiōsum", "drahocenný"),
  n("pretium", "pretiī n.", "cena, výkupné"),
  a("generosus", "generōsa, generōsum", "šlechetný, urozený"),
  a("intactus", "intācta, intāctum", "nedotčený, neporušený"),
  v("spargo", "spargere, sparsī, sparsum", "rozsévám, kropím"),
  v("observo", "observāre, observāvī, observātum", "zachovávám"),
  a("legalis", "lēgāle", "zákonný"),
  n("supplementum", "supplēmentī n.", "doplněk, náhrada"),
  n("defectus", "dēfectūs m.", "nedostatek"),
  n("laudatio", "laudātiōnis f.", "chvála, oslava"),
  a("mirabilis", "mīrābile", "podivuhodný"),
  v("lateo", "latēre, latuī", "jsem skryt"),
  v("subicio", "subicere, subiēcī, subiectum", "podrobuji"),
  v("contemplor", "contemplārī, contemplātus sum", "rozjímám, pozoruji"),
  v("deficio", "dēficere, dēfēcī, dēfectum", "selhávám, ochabuji"),
  n("visus", "vīsūs m.", "zrak"),
  n("tactus", "tāctūs m.", "hmat, dotek"),
  n("auditus", "audītūs m.", "sluch"),
  n("pelicanus", "pelicānī m.", "pelikán"),
  n("scelus", "sceleris n.", "zločin, hřích"),
  a("immaculatus", "immaculāta, immaculātum", "neposkvrněný"),
  n("conceptio", "conceptiōnis f.", "početí"),
  n("sinus", "sinūs m.", "náruč, lůno"),
  n("sanctitas", "sānctitātis f.", "svatost"),
  n("votum", "vōtī n.", "slib, přání"),
  n("probrum", "probrī n.", "potupa, hanba"),
  n("deliciae", "dēliciārum f. pl.", "rozkoš, potěšení"),
  a("dilectus", "dīlēcta, dīlēctum", "milovaný"),
  v("placo", "plācāre, plācāvī, plācātum", "usmiřuji"),
  o("autem", "spojka", "však, ale"),
  v("repudio", "repudiāre, repudiāvī, repudiātum", "zavrhuji"),
  v("discedo", "discēdere, discessī, discessum", "odcházím, odstupuji"),
  n("miseria", "miseriae f.", "bída, neštěstí"),
  n("fames", "famis f.", "hlad"),
  v("pereo", "perīre, periī, peritum", "hynu, zanikám"),
  n("opinio", "opīniōnis f.", "mínění, názor"),
  n("ovile", "ovīlis n.", "ovčinec, stádo"),
  v("vindico", "vindicāre, vindicāvī, vindicātum", "osvobozuji, nárokuji"),
  v("renuo", "renuere, renuī", "odmítám"),
  o("denique", "příslovce", "konečně, nakonec"),
  o("olim", "příslovce", "kdysi, jednou"),
  v("largior", "largīrī, largītus sum", "štědře uděluji"),
  n("tranquillitas", "tranquillitātis f.", "klid, pokoj"),
  v("perficio", "perficere, perfēcī, perfectum", "dokonávám"),
  a("supernus", "superna, supernum", "nebeský, horní"),
  n("paraclitus", "paraclitī m.", "Utěšitel, přímluvce"),
  n("unctio", "ūnctiōnis f.", "pomazání"),
  a("septiformis", "septiforme", "sedmerý"),
  n("digitus", "digitī m.", "prst"),
  a("paternus", "paterna, paternum", "otcovský"),
  o("rite", "příslovce", "náležitě, řádně"),
  n("sermo", "sermōnis m.", "řeč, slovo"),
  v("dito", "ditāre, ditāvī, ditātum", "obohacuji"),
  v("firmo", "fīrmāre, fīrmāvī, fīrmātum", "posiluji, upevňuji"),
  v("repello", "repellere, reppulī, repulsum", "odháním, odrážím"),
  o("longe", "příslovce", "daleko"),
  o("protinus", "příslovce", "ihned, hned"),
  n("ductor", "ductōris m.", "vůdce"),
  o("sic", "příslovce", "tak"),
  a("praevius", "praevia, praevium", "jdoucí napřed"),
  v("vito", "vītāre, vītāvī, vītātum", "vyhýbám se"),
  a("noxius", "noxia, noxium", "škodlivý"),
  n("illustratio", "illūstrātiōnis f.", "osvícení"),
  a("almus", "alma, almum", "vznešený, dobrotivý"),
  n("partus", "partūs m.", "porod"),
  n("virginitas", "virginitātis f.", "panenství"),
  a("fecundus", "fēcunda, fēcundum", "plodný"),
  o("valde", "příslovce", "velmi"),
  a("decorus", "decōra, decōrum", "krásný, ozdobný"),
  n("fragilitas", "fragilitātis f.", "křehkost, slabost"),
  n("iniquitas", "inīquitātis f.", "nepravost, hřích"),
  n("vallis", "vallis f.", "údolí"),
  o("eia", "citoslovce", "nuže, ach"),
  n("necessitas", "necessitātis f.", "nouze, potřeba"),
  a("inviolatus", "inviolāta, inviolātum", "neporušený"),
  a("intemeratus", "intemerāta, intemerātum", "neposkvrněný"),
  a("amabilis", "amābile", "milý, laskavý"),
  a("honorabilis", "honōrābile", "ctihodný"),
  n("devotio", "dēvōtiōnis f.", "zbožnost"),
  a("eburneus", "eburnea, eburneum", "slonovinový"),
  a("aureus", "aurea, aureum", "zlatý"),
  n("foedus", "foederis n.", "smlouva, úmluva"),
  n("arca", "arcae f.", "truhla, archa"),
  n("ianua", "iānuae f.", "brána, dveře"),
  a("matutinus", "mātūtīna, mātūtīnum", "ranní, jitřní"),
  n("consolatrix", "cōnsōlātrīcis f.", "utěšitelka"),
  a("afflictus", "afflīcta, afflīctum", "zarmoucený, sklíčený"),
  a("christianus", "chrīstiāna, chrīstiānum", "křesťanský"),
  n("confessor", "cōnfessōris m.", "vyznavač"),
  n("labes", "lābis f.", "poskvrna, skvrna"),
  a("originalis", "orīgināle", "původní, dědičný"),
  v("assumo", "assūmere, assūmpsī, assūmptum", "přijímám, beru k sobě"),
  n("sanitas", "sānitātis f.", "zdraví"),
  a("praesens", "gen. praesentis", "přítomný"),
  n("tristitia", "trīstitiae f.", "smutek"),
  v("perfruor", "perfruī, perfrūctus sum", "plně užívám"),
  n("proles", "prōlis f.", "potomstvo, potomek"),
  a("inclitus", "inclita, inclitum", "slavný, proslulý"),
  a("pudicus", "pudīca, pudīcum", "cudný"),
  n("nutricius", "nūtrīciī m.", "pěstoun, živitel"),
  n("defensor", "dēfēnsōris m.", "obhájce, ochránce"),
  a("sedulus", "sēdula, sēdulum", "horlivý, pečlivý"),
  n("praeses", "praesidis m.", "představený, ochránce"),
  a("oboediens", "gen. oboedientis", "poslušný"),
  n("amator", "amātōris m.", "milovník"),
  n("opifex", "opificis m.", "řemeslník, dělník"),
  a("domesticus", "domestica, domesticum", "domácí"),
  n("columen", "columinis n.", "opora, sloup"),
  n("solatium", "sōlātiī n.", "útěcha"),
  v("aegroto", "aegrōtāre, aegrōtāvī, aegrōtātum", "stůňu, jsem nemocen"),
  n("patronus", "patrōnī m.", "ochránce, patron"),
  n("terror", "terrōris m.", "strach, hrůza"),
  n("daemon", "daemonis m.", "démon, zlý duch"),
  n("protector", "prōtēctōris m.", "ochránce"),
  n("possessio", "possessiōnis f.", "majetek"),
  a("ineffabilis", "ineffābile", "nevýslovný"),
  n("providentia", "prōvidentiae f.", "prozřetelnost"),
  v("confirmo", "cōnfīrmāre, cōnfīrmāvī, cōnfīrmātum", "posiluji, potvrzuji"),
  n("grex", "gregis m.", "stádo"),
  a("cernuus", "cernua, cernuum", "sklonený, poklekající"),
]);
