import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 4", [
  o("eleison", "nesklonné (řec.)", "smiluj se", ["Kyrie, eleison.", "Pane, smiluj se.", "Řecky; v latinské mši zůstalo bez překladu."]),
  n("Christus", "Christī m.", "Kristus, Pomazaný", ["Christus vincit, Christus regnat.", "Kristus vítězí, Kristus kraluje.", "Z řeckého christos = pomazaný."]),
  o("Kyrie", "nesklonné (řec.)", "Pane", ["Kyrie, eleison. Christe, eleison.", "Pane, smiluj se. Kriste, smiluj se.", "Řecký vokativ od kyrios = pán."]),
  o("is", "ea, id (gen. eius)", "on, ona, ono; ten", ["Benedictus qui venit in nomine eius.", "Požehnaný, který přichází v jeho jménu.", "Gen. eius, dat. ei; ea = ona, id = ono."]),
  a("excelsus", "excelsa, excelsum", "vysoký; pl. výsosti", ["Gloria in excelsis Deo.", "Sláva Bohu na výsostech.", "Z Glorie. In excelsis = na výsostech."]),
  o("alleluia", "nesklonné (hebr.)", "aleluja, chvalte Pána", ["Alleluia, laudate Dominum.", "Aleluja, chvalte Pána.", "Z hebrejského hallelu Jah = chvalte Hospodina."]),
  o("-que", "spojka (příklonka)", "a", ["Patri Filioque", "Otci i Synu", "Příklonka: připojuje se za slovo, které spojuje."]),
  o("hosanna", "nesklonné (hebr.)", "hosana, sláva", ["Hosanna in excelsis.", "Hosana na výsostech.", "Ze Sanctus. Z hebrejštiny: zachraň, prosíme."]),
  v("adoro", "adōrāre, adōrāvī, adōrātum", "klaním se, uctívám", ["Adoro te devote.", "Zbožně se ti klaním.", "Začátek hymnu sv. Tomáše Akvinského. Odtud adorace."]),
  n("missa", "missae f.", "mše", ["Ite, missa est.", "Jděte, mše skončila.", "Od mittere (posílat); z tohoto zvolání vzniklo slovo mše."]),
  a("unigenitus", "ūnigenita, ūnigenitum", "jednorozený", ["Filius Dei unigenitus", "Jednorozený Syn Boží", "Z Kréda. Unus + genitus = jediný zrozený."]),
  n("genetrix", "genetrīcis f.", "rodička, matka", ["Sancta Dei Genetrix, ora pro nobis.", "Svatá Boží Rodičko, oroduj za nás.", "Z litanií. Překlad řeckého Theotokos."]),
  v("quaeso", "nedostatkové; pl. quaesumus", "prosím", ["Da, quaesumus, pacem.", "Dej, prosíme, pokoj.", "Užívají se hlavně tvary quaeso a quaesumus."]),
  n("angelus", "angelī m.", "anděl", ["Angelus Domini nuntiavit Mariae.", "Anděl Páně zvěstoval Panně Marii.", "Začátek modlitby Anděl Páně. Z řeckého angelos = posel."]),
  a("fidelis", "fidēle", "věrný; věřící", ["Adeste, fideles.", "Pojďte, věrní.", "Začátek vánoční písně. Odtud fidelita."]),
  o("sabaoth", "nesklonné (hebr.)", "zástupů", ["Dominus Deus Sabaoth", "Pán, Bůh zástupů", "Ze Sanctus. Hebrejské množné číslo: zástupy, vojska."]),
  a("misericors", "gen. misericordis", "milosrdný", ["Deus misericors et iustus est.", "Bůh je milosrdný a spravedlivý.", "Miser + cor: srdce pro ubohé."]),
  n("archangelus", "archangelī m.", "archanděl", ["Sancte Michael archangele", "Svatý Michaeli archanděli", "Z řeckého archi- (první) + angelos."]),
  v("dignor", "dignārī, dignātus sum", "ráčím, uznávám za hodna", ["Dignare, Domine, nos custodire.", "Rač nás, Pane, chránit.", "Z Te Deum. Od dignus = hodný."]),
  v("concelebro", "concelebrāre, concelebrāvī, concelebrātum", "společně slavím", ["Sacerdotes missam concelebrant.", "Kněží společně slouží mši.", "Odtud koncelebrace."]),
  v("tremo", "tremere, tremuī", "třesu se, chvěji se", ["Tremunt potestates.", "Mocnosti se chvějí.", "Z preface. Odtud tremolo."]),
  v("conglorifico", "conglōrificāre, -āvī, -ātum", "spoluoslavuji", ["Simul adoratur et conglorificatur.", "Zároveň je uctíván a oslavován.", "Z Kréda: o Duchu Svatém."]),
  n("sponsus", "spōnsī m.", "snoubenec, ženich", ["Ecce sponsus venit.", "Hle, ženich přichází.", "Mt 25,6 (podobenství o pannách)."]),
  a("sempiternus", "sempiterna, sempiternum", "věčný, ustavičný", ["Gloria sempiterna", "Věčná sláva", "Semper + aeternus."]),
  n("iuventus", "iuventūtis f.", "mládí", ["Deus, qui laetificat iuventutem meam.", "Bůh, který obveseluje mé mládí.", "Ze stupňových modliteb (Ž 43)."]),
  o("quoque", "příslovce", "také, i", ["Tu quoque, Brute?", "I ty, Brute?", "Stojí za slovem, ke kterému patří."]),
  o("seraphim", "nesklonné (hebr.)", "serafové", ["Cherubim quoque ac seraphim", "Cherubové i serafové", "Hebrejské množné číslo; serafové = planoucí."]),
  n("exsultatio", "exsultātiōnis f.", "plesání, jásot", ["Exsultatio et laetitia", "Plesání a radost", "Od exsultare = poskakovat radostí."]),
  n("confessio", "cōnfessiōnis f.", "vyznání", ["Confessio peccatorum", "Vyznání hříchů", "Odtud konfese."]),
  o("vero", "příslovce", "však, vskutku", ["Dixit vero Dominus.", "I řekl Pán.", "Stojí obvykle za prvním slovem věty."]),
  v("respicio", "respicere, respexī, respectum", "shlížím, ohlížím se", ["Respice in faciem Christi tui.", "Shlédni na tvář svého Pomazaného.", "Ž 84. Odtud respekt."]),
  v("infundo", "īnfundere, īnfūdī, īnfūsum", "vlévám", ["Infunde amorem cordibus.", "Vlij lásku do srdcí.", "Z hymnu Veni Creator. Odtud infuze."]),
  n("vas", "vāsis n.", "nádoba", ["Vas spirituale, ora pro nobis.", "Nádobo duchovní, oroduj za nás.", "Z Loretánských litanií. Neplést s vas, vadis = ručitel."]),
  v("laetifico", "laetificāre, laetificāvī, laetificātum", "obveseluji, těším", ["Laetifica animam servi tui.", "Obvesel duši svého služebníka.", "Ž 86. Laetus + facere."]),
  n("dominatio", "dominātiōnis f.", "panstvo, vláda", ["Laudant angeli, adorant dominationes.", "Chválí andělé, klanějí se panstva.", "Z preface; panstva jsou jeden z andělských kůrů."]),
  v("deprecor", "dēprecārī, dēprecātus sum", "prosím, vyprošuji", ["Te deprecor, Domine.", "Prosím tě, Pane.", "Deponens. Odtud deprekace."]),
  a("supplex", "gen. supplicis", "pokorně prosící", ["Supplices te rogamus.", "Pokorně tě prosíme.", "Z římského kánonu. Odtud suplikace."]),
  n("intercessio", "intercessiōnis f.", "přímluva", ["Intercessio sanctorum", "Přímluva svatých", "Od intercedere = vstoupit mezi."]),
  o("ecce", "citoslovce", "hle, aj", ["Ecce Agnus Dei.", "Hle, Beránek Boží.", "Slova Jana Křtitele (Jan 1,29)."]),
  n("maiestas", "maiestātis f.", "velebnost, majestát", ["Pleni sunt caeli et terra maiestatis gloriae tuae.", "Nebe i země jsou plny velebnosti tvé slávy.", "Z Te Deum. Odtud majestát."]),
  a("salvus", "salva, salvum", "zachráněný, spasený", ["Salvum fac populum tuum, Domine.", "Spas, Pane, svůj lid.", "Z Te Deum."]),
  n("laus", "laudis f.", "chvála", ["Laus tibi, Christe.", "Chvála tobě, Kriste.", "Odpověď po evangeliu. Gen. laudis."]),
  a("gloriosus", "glōriōsa, glōriōsum", "slavný", ["Gloriosa Virgo Maria", "Slavná Panna Maria", "Od gloria."]),
  v("laetor", "laetārī, laetātus sum", "raduji se", ["Laetatus sum in his.", "Zaradoval jsem se z toho.", "Ž 122. Deponens: tvar trpný, význam činný."]),
  v("praesto", "praestāre, praestitī, praestitum", "poskytuji, uděluji", ["Praesta, quaesumus, omnipotens Deus.", "Dej, prosíme, všemohoucí Bože.", "Častý začátek liturgických modliteb."]),
  n("famulus", "famulī m.", "služebník", ["Ecce famulus tuus.", "Hle, tvůj služebník.", "Příbuzné s familia = celá domácnost."]),
  a("infirmus", "īnfirma, īnfirmum", "slabý, nemocný", ["Visitare infirmos", "Navštěvovat nemocné", "Jeden ze skutků milosrdenství. In- + firmus = ne pevný."]),
  n("genitor", "genitōris m.", "otec, rodič", ["Genitori Genitoque laus", "Rodiči i Zrozenému chvála", "Z Tantum ergo."]),
  n("chorus", "chorī m.", "sbor, kůr", ["Chorus angelorum te suscipiat.", "Kůr andělů ať tě přijme.", "Z pohřebního zpěvu In paradisum. Odtud chór."]),
  v("emitto", "ēmittere, ēmīsī, ēmissum", "vysílám", ["Emitte lucem tuam.", "Sešli své světlo.", "Ze stupňových modliteb (Ž 43). Odtud emise."]),
  v("introeo", "introīre, introiī, introitum", "vcházím, vstupuji", ["Introibo ad altare Dei.", "Přistoupím k oltáři Božímu.", "Začátek stupňových modliteb. Časuje se jako eo."]),
  o("quare", "příslovce", "proč", ["Quare tristis es, anima mea?", "Proč jsi smutná, duše moje?", "Ze stupňových modliteb (Ž 43)."]),
  o("adhuc", "příslovce", "dosud, ještě", ["Adhuc eo loquente", "Když on ještě mluvil", "Ad + huc = až sem."]),
  n("indulgentia", "indulgentiae f.", "shovívavost, odpuštění", ["Indulgentiam tribuat nobis Dominus.", "Odpuštění ať nám udělí Pán.", "Odtud odpustek, indulgence."]),
  n("hymnus", "hymnī m.", "chvalozpěv, hymnus", ["Hymnum dicamus Domino.", "Pějme chvalozpěv Pánu.", "Z řeckého hymnos."]),
  a("invisibilis", "invīsibile", "neviditelný", ["Visibilium omnium et invisibilium", "Všeho viditelného i neviditelného", "Z Kréda."]),
  n("apostolus", "apostolī m.", "apoštol", ["Petrus apostolus", "Apoštol Petr", "Z řeckého apostolos = vyslaný."]),
  v("reparo", "reparāre, reparāvī, reparātum", "obnovuji, napravuji", ["Christus mundum reparavit.", "Kristus obnovil svět.", "Odtud reparace."]),
  o("quidem", "příslovce", "sice, ovšem", ["Spiritus quidem promptus est.", "Duch je sice ochotný.", "Mt 26,41: …caro autem infirma."]),
  v("effundo", "effundere, effūdī, effūsum", "vylévám, prolévám", ["Effundam de Spiritu meo.", "Vyleji ze svého Ducha.", "Jl 3,1."]),
  o("apud", "předložka + akuz.", "u, při", ["Apud te est fons vitae.", "U tebe je pramen života.", "Ž 36. Pojí se s akuzativem."]),
  n("refugium", "refugiī n.", "útočiště", ["Refugium peccatorum", "Útočiště hříšníků", "Z Loretánských litanií."]),
  v("lavo", "lavāre, lāvī, lautum", "myji, omývám", ["Lavabo inter innocentes manus meas.", "Umyji si ruce mezi nevinnými.", "Ž 26; odtud název lavabo."]),
  o("devote", "příslovce", "zbožně", ["Devote te adoro.", "Zbožně se ti klaním.", "Od devotus = oddaný, zbožný."]),
  v("accendo", "accendere, accendī, accēnsum", "zapaluji, rozněcuji", ["Accende lumen sensibus.", "Zažehni světlo smyslům.", "Z hymnu Veni Creator."]),
  n("praesidium", "praesidiī n.", "ochrana, záštita", ["Sub tuum praesidium confugimus.", "Pod tvou ochranu se utíkáme.", "Nejstarší známá mariánská modlitba."]),
  n("speculum", "speculī m.", "zrcadlo", ["Speculum iustitiae", "Zrcadlo spravedlnosti", "Z Loretánských litanií. Odtud spekulovat."]),
  n("turris", "turris f.", "věž", ["Turris Davidica", "Věž Davidova", "Z Loretánských litanií."]),
  n("custos", "custōdis m.", "strážce", ["Custos, quid de nocte?", "Strážce, co je s nocí?", "Iz 21,11. Odtud kustod."]),
  n("rector", "rēctōris m.", "správce, vládce", ["Rector ecclesiae", "Správce kostela", "Odtud rektor."]),
  v("perduco", "perdūcere, perdūxī, perductum", "přivádím, dovádím", ["Perducat nos ad vitam aeternam.", "Ať nás přivede k životu věčnému.", "Z modlitby Misereatur."]),
  n("introitus", "introitūs m.", "vstup, introit", ["Introitus missae", "Vstup mše", "Úvodní zpěv mše. Od introire = vejít."]),
  v("formo", "fōrmāre, fōrmāvī, fōrmātum", "tvořím, utvářím", ["Formavit Deus hominem.", "Bůh utvořil člověka.", "Gn 2,7. Odtud forma."]),
  v("aspergo", "aspergere, aspersī, aspersum", "kropím", ["Asperges me hyssopo.", "Pokropíš mě yzopem.", "Ž 51; zpěv před nedělní mší."]),
  v("pervenio", "pervenīre, pervēnī, perventum", "dospívám, docházím", ["Ad te perveniamus.", "Kéž k tobě dojdeme.", "Per + venire = dojít až do cíle."]),
  o("iste", "ista, istud", "tento, ten", ["Iste confessor", "Tento vyznavač", "Začátek hymnu. Iste, ista, istud."]),
  n("princeps", "prīncipis m.", "kníže, vládce", ["Princeps pacis", "Kníže pokoje", "Iz 9,5. Odtud princ."]),
  n("passio", "passiōnis f.", "utrpení", ["Passio Domini nostri Iesu Christi", "Utrpení našeho Pána Ježíše Krista", "Odtud pašije."]),
  v("veneror", "venerārī, venerātus sum", "uctívám", ["Veneremur cernui.", "Uctívejme vkleče.", "Z Tantum ergo. Odtud venerabilní."]),
  a("spiritualis", "spīrituāle", "duchovní", ["Vas spirituale", "Nádoba duchovní", "Z Loretánských litanií. Odtud spirituál."]),
  v("discerno", "discernere, discrēvī, discrētum", "rozlišuji, rozsuzuji", ["Discerne causam meam.", "Rozsuď mou při.", "Ze stupňových modliteb (Ž 43)."]),
  v("adduco", "addūcere, addūxī, adductum", "přivádím", ["Me adduxerunt in montem sanctum tuum.", "Přivedly mě na tvou svatou horu.", "Ze stupňových modliteb (Ž 43)."]),
  n("tabernaculum", "tabernāculī n.", "stan, svatostánek", ["In tabernacula tua", "Do tvých stanů", "Ze stupňových modliteb. Odtud tabernákl (svatostánek)."]),
  n("cithara", "citharae f.", "citera, harfa", ["Confitebor tibi in cithara.", "Budu tě chválit na citeru.", "Ze stupňových modliteb (Ž 43)."]),
  v("conturbo", "conturbāre, conturbāvī, conturbātum", "znepokojuji, rmoutím", ["Quare conturbas me?", "Proč mě znepokojuješ?", "Ze stupňových modliteb (Ž 43)."]),
  n("vultus", "vultūs m.", "tvář, obličej", ["Salutare vultus mei", "Spása mé tváře", "Ze stupňových modliteb (Ž 43)."]),
  n("adiutorium", "adiūtōriī n.", "pomoc", ["Adiutorium nostrum in nomine Domini.", "Naše pomoc je ve jménu Páně.", "Ze stupňových modliteb (Ž 124)."]),
  n("absolutio", "absolūtiōnis f.", "rozhřešení", ["Absolutionem tribuat nobis Dominus.", "Rozhřešení ať nám udělí Pán.", "Odtud absolutorium."]),
  v("converto", "convertere, convertī, conversum", "obracím", ["Deus, tu conversus vivificabis nos.", "Bože, obrátíš se a oživíš nás.", "Ze stupňových modliteb (Ž 85). Odtud konverze."]),
  n("clamor", "clāmōris m.", "křik, volání", ["Clamor meus ad te veniat.", "Mé volání ať dojde k tobě.", "Ze stupňových modliteb (Ž 102)."]),
  n("sequentia", "sequentiae f.", "sekvence", ["Sequentia sancti Evangelii", "Pokračování svatého evangelia", "Uvozuje čtení evangelia. Od sequi = následovat."]),
  a("consubstantialis", "cōnsubstantiāle", "soupodstatný", ["Consubstantialem Patri", "Soupodstatného s Otcem", "Z Kréda."]),
  o("simul", "příslovce", "zároveň, spolu", ["Simul adoratur et conglorificatur.", "Zároveň je uctíván a oslavován.", "Z Kréda. Odtud simultánní."]),
  a("apostolicus", "apostolica, apostolicum", "apoštolský", ["Unam, sanctam, catholicam et apostolicam Ecclesiam", "Jednu, svatou, obecnou a apoštolskou církev", "Z Kréda."]),
  n("offertorium", "offertōriī n.", "obětování, ofertorium", ["Offertorium cantatur.", "Zpívá se ofertorium.", "Od offerre = přinášet, obětovat."]),
  n("utilitas", "ūtilitātis f.", "užitek, prospěch", ["Ad utilitatem nostram", "K našemu prospěchu", "Z odpovědi Suscipiat. Odtud utilita."]),
  n("secreta", "sēcrētae f.", "tichá modlitba", ["Secreta dicitur.", "Říká se tichá modlitba.", "Od secernere = oddělit. Odtud sekret."]),
  v("admitto", "admittere, admīsī, admissum", "připouštím", ["Nos in consortium sanctorum admitte.", "Přijmi nás do společenství svatých.", "Z římského kánonu."]),
  n("singularitas", "singulāritātis f.", "jedinost", ["Non in unius singularitate personae", "Ne v jedinosti jedné osoby", "Z preface o Nejsvětější Trojici."]),
  n("differentia", "differentiae f.", "rozdíl", ["Sine differentia discretionis", "Bez rozdílu v rozlišení", "Z preface o Nejsvětější Trojici. Odtud diference."]),
  n("discretio", "discrētiōnis f.", "rozlišení", ["Discretio spirituum", "Rozlišování duchů", "Odtud diskrétní."]),
  n("deitas", "deitātis f.", "božství", ["Deitas una et trina", "Jedno a trojí božství", "Od deus."]),
  v("iustifico", "iūstificāre, iūstificāvī, iūstificātum", "ospravedlňuji", ["Fides iustificat.", "Víra ospravedlňuje.", "Iustus + facere. Odtud justifikace."]),
  a("impius", "impia, impium", "bezbožný", ["Fugit impius nemine persequente.", "Bezbožný prchá, i když ho nikdo nepronásleduje.", "Př 28,1."]),
  o("prope", "příslovce; předložka + akuz.", "blízko", ["Dominus prope est.", "Pán je blízko.", "Flp 4,5. S akuzativem i předložka: prope urbem."]),
  n("immortalitas", "immortālitātis f.", "nesmrtelnost", ["Immortalitas animae", "Nesmrtelnost duše", "In- + mortalis."]),
  a("manifestus", "manifesta, manifestum", "zjevný, zřejmý", ["Manifestum est.", "Je to zřejmé.", "Odtud manifest, manifestovat."]),
  v("appareo", "appārēre, appāruī, appāritum", "zjevuji se, ukazuji se", ["Apparuit gratia Dei.", "Zjevila se milost Boží.", "Tit 2,11."]),
  v("cerno", "cernere, crēvī, crētum", "vidím, rozeznávám", ["Lucem cerno.", "Vidím světlo."]),
  v("elevo", "ēlevāre, ēlevāvī, ēlevātum", "pozvedám", ["Sacerdos hostiam elevat.", "Kněz pozvedá hostii.", "Odtud elevace, elevátor."]),
  n("thronus", "thronī m.", "trůn", ["Ad thronum gratiae", "K trůnu milosti", "Žd 4,16. Z řeckého thronos."]),
  n("miseratio", "miserātiōnis f.", "slitování", ["Miseratio Domini", "Slitování Páně", "Od misereri."]),
  a("hodiernus", "hodierna, hodiernum", "dnešní", ["Hodierna die", "Dnešního dne", "Od hodie = dnes."]),
  n("adoptio", "adoptiōnis f.", "přijetí za vlastní", ["Adoptionem filiorum recepimus.", "Přijali jsme synovství.", "Gal 4,5. Odtud adopce."]),
  o("quapropter", "příslovce", "proto", ["Quapropter gaudeamus.", "Proto se radujme.", "Qua + propter."]),
  v("profundo", "prōfundere, prōfūdī, prōfūsum", "vylévám, rozlévám", ["Sanguinem suum profudit.", "Prolil svou krev."]),
  n("institutio", "īnstitūtiōnis f.", "ustanovení, poučení", ["Divina institutione formati", "Božím poučením vedeni", "Z úvodu k Otčenáši. Odtud instituce."]),
  n("postcommunio", "postcommūniōnis f.", "modlitba po přijímání", ["Postcommunio dicitur.", "Říká se modlitba po přijímání.", "Post + communio."]),
  n("evangelium", "ēvangeliī n.", "evangelium", ["Initium sancti Evangelii", "Začátek svatého evangelia", "Z řeckého euangelion = dobrá zpráva."]),
  v("perhibeo", "perhibēre, perhibuī, perhibitum", "vydávám (svědectví)", ["Testimonium perhibet de me.", "Vydává svědectví o mně.", "Jan 5,32. Per + habere."]),
  n("dulcedo", "dulcēdinis f.", "sladkost", ["Vita, dulcedo et spes nostra", "Živote, sladkosti a naděje naše", "Z antifony Salve Regina."]),
  n("prex", "precis f. (obv. pl. precēs)", "prosba, modlitba", ["Exaudi preces nostras.", "Vyslyš naše prosby.", "Běžné hlavně v množném čísle: preces."]),
  a("benignus", "benigna, benignum", "dobrotivý, laskavý", ["Benignus et misericors Dominus", "Dobrotivý a milosrdný Pán", "Odtud benigní (nezhoubný)."]),
  n("proelium", "proeliī n.", "boj, bitva", ["Defende nos in proelio.", "Braň nás v boji.", "Z modlitby k sv. Michaelovi."]),
  n("nequitia", "nēquitiae f.", "zlovolnost, nešlechetnost", ["Contra nequitiam diaboli", "Proti zlovolnosti ďábla", "Z modlitby k sv. Michaelovi."]),
  n("infernus", "īnfernī m.", "peklo, podsvětí", ["Libera nos ab igne inferni.", "Uchraň nás od ohně pekelného.", "Z modlitby O mi Iesu. Odtud infernální."]),
  n("nix", "nivis f.", "sníh", ["Super nivem dealbabor.", "Budu bělejší nad sníh.", "Ž 51. Gen. nivis."]),
  v("foveo", "fovēre, fōvī, fōtum", "hřeji, opatruji", ["Fove quod est frigidum.", "Zahřej, co je chladné.", "Ze sekvence Veni Sancte Spiritus."]),
  v("visito", "vīsitāre, vīsitāvī, vīsitātum", "navštěvuji", ["Visita nos, Domine.", "Navštiv nás, Pane.", "Odtud vizita, vizitace."]),
  v("egredior", "ēgredī, ēgressus sum", "vycházím", ["Egredietur virga de radice Iesse.", "Vyjde výhonek z kořene Jesse.", "Iz 11,1. Deponens: ex + gradior."]),
  n("latus", "lateris n.", "bok, strana", ["A latere dextro", "Z pravé strany", "Z velikonočního Vidi aquam. Neplést s latus, -a, -um = široký."]),
  a("dexter", "dext(e)ra, dext(e)rum", "pravý", ["Sedet ad dexteram Patris.", "Sedí po pravici Otce.", "Z Kréda. Tvary i bez e: dextra, dextrum."]),
  o("cherubim", "nesklonné (hebr.)", "cherubové", ["Tibi cherubim et seraphim proclamant.", "Tobě cherubové a serafové volají.", "Z Te Deum. Hebrejské množné číslo."]),
  n("iubilum", "iūbilī n.", "jásot, plesání", ["Iubilum cordis", "Jásot srdce", "Od iubilare = jásat."]),
  a("incessabilis", "incessābile", "neustávající", ["Incessabili voce proclamant.", "Neustálým hlasem volají.", "Z Te Deum. In- + cessare = přestávat."]),
  a("immensus", "immēnsa, immēnsum", "nezměrný", ["Patrem immensae maiestatis", "Otce nezměrné velebnosti", "Z Te Deum. Odtud imenzní."]),
  a("unicus", "ūnica, ūnicum", "jediný", ["Unicus Filius tuus", "Tvůj jediný Syn", "Odtud unikát."]),
  n("uterus", "uterī m.", "lůno, život", ["Ex utero matris meae", "Od lůna mé matky", "Odtud lékařské uterus (děloha)."]),
  v("numero", "numerāre, numerāvī, numerātum", "počítám", ["In gloria numerari", "Být počítán ve slávě", "Z Te Deum. Odtud numerovat."]),
  n("hereditas", "hērēditātis f.", "dědictví", ["Benedic hereditati tuae.", "Požehnej svému dědictví.", "Z Te Deum. Odtud hereditární (dědičný)."]),
  o("usque", "příslovce", "až, stále", ["Usque in aeternum", "Až na věky", "Z Te Deum."]),
  o("quemadmodum", "příslovce", "jak, jakým způsobem", ["Quemadmodum speravimus in te", "Jak jsme v tebe doufali", "Z Te Deum."]),
  v("confundo", "cōnfundere, cōnfūdī, cōnfūsum", "zahanbuji, mátu", ["Non confundar in aeternum.", "Nebudu zahanben navěky.", "Poslední verš Te Deum. Odtud konfuze."]),
  n("firmamentum", "firmāmentī n.", "obloha, opora", ["Firmamentum caeli", "Klenba nebeská", "Gn 1. Odtud firmament."]),
  n("bonitas", "bonitātis f.", "dobrota", ["Bonitas Dei", "Dobrota Boží", "Od bonus."]),
  a("infinitus", "īnfīnīta, īnfīnītum", "nekonečný", ["Infinita bonitas", "Nekonečná dobrota", "In- + finis = hranice."]),
  n("thesaurus", "thēsaurī m.", "poklad", ["Thesaurus in caelo", "Poklad v nebi", "Z řeckého thésauros. Odtud tezaurus."]),
  v("exoro", "exōrāre, exōrāvī, exōrātum", "vyprošuji", ["Exoramus te, Domine.", "Vyprošujeme si od tebe, Pane."]),
  n("hostia", "hostiae f.", "oběť, hostie", ["O salutaris hostia", "Ó spasná oběti", "Začátek eucharistického hymnu. Odtud hostie."]),
  v("premo", "premere, pressī, pressum", "tisknu, tížím", ["Pondere premor peccatorum.", "Tíží mě břemeno hříchů.", "Odtud represe, imprese."]),
  a("hostilis", "hostīle", "nepřátelský", ["Bella premunt hostilia.", "Doléhají nepřátelské války.", "Z hymnu O salutaris hostia. Od hostis."]),
  a("trinus", "trīna, trīnum", "trojí", ["Deus trinus et unus", "Bůh trojjediný", "Od tres. Příbuzné s Trinitas."]),
  n("terminus", "terminī m.", "hranice, konec", ["Terminus vitae", "Konec života", "Odtud termín."]),
  v("pango", "pangere, pepigī, pāctum", "opěvuji, skládám", ["Pange, lingua, gloriosi", "Opěvuj, jazyku, slavného…", "Začátek hymnu sv. Tomáše Akvinského."]),
  a("pretiosus", "pretiōsa, pretiōsum", "drahocenný", ["Sanguinisque pretiosi", "A krve drahocenné", "Z hymnu Pange lingua. Odtud preciózní."]),
  n("pretium", "pretiī n.", "cena, výkupné", ["Pretium redemptionis", "Cena vykoupení", "Odtud preciózní, apreciace."]),
  a("generosus", "generōsa, generōsum", "šlechetný, urozený", ["Fructus ventris generosi", "Plod šlechetného lůna", "Z hymnu Pange lingua."]),
  a("intactus", "intācta, intāctum", "nedotčený, neporušený", ["Ex intacta Virgine", "Z neporušené Panny", "Z hymnu Pange lingua. In- + tactus = dotčený."]),
  v("spargo", "spargere, sparsī, sparsum", "rozsévám, kropím", ["Sparso verbi semine", "Když rozsel semeno slova", "Z hymnu Pange lingua."]),
  v("observo", "observāre, observāvī, observātum", "zachovávám", ["Observata lege plene", "Když plně zachoval zákon", "Z hymnu Pange lingua. Odtud observace."]),
  a("legalis", "lēgāle", "zákonný", ["Cibis in legalibus", "S pokrmy podle zákona", "Z hymnu Pange lingua. Od lex."]),
  n("supplementum", "supplēmentī n.", "doplněk, náhrada", ["Praestet fides supplementum.", "Ať víra doplní, co chybí.", "Z Tantum ergo."]),
  n("defectus", "dēfectūs m.", "nedostatek", ["Sensuum defectui", "Nedostatku smyslů", "Z Tantum ergo. Odtud defekt."]),
  n("laudatio", "laudātiōnis f.", "chvála, oslava", ["Compar sit laudatio.", "Rovná buď chvála.", "Z Tantum ergo."]),
  a("mirabilis", "mīrābile", "podivuhodný", ["Mirabilis Deus in sanctis suis.", "Podivuhodný je Bůh ve svých svatých.", "Ž 68."]),
  v("lateo", "latēre, latuī", "jsem skryt", ["Latet anguis in herba.", "V trávě se skrývá had.", "Vergilius. Odtud latentní."]),
  v("subicio", "subicere, subiēcī, subiectum", "podrobuji", ["Tibi se cor meum totum subicit.", "Tobě se celé mé srdce podrobuje.", "Z Adoro te. Odtud subjekt."]),
  v("contemplor", "contemplārī, contemplātus sum", "rozjímám, pozoruji", ["Te contemplans totum deficit.", "Když tě rozjímá, docela selhává.", "Z Adoro te. Odtud kontemplace."]),
  v("deficio", "dēficere, dēfēcī, dēfectum", "selhávám, ochabuji", ["Totum deficit.", "Docela selhává.", "Z Adoro te. Odtud deficit."]),
  n("visus", "vīsūs m.", "zrak", ["Visus, tactus, gustus in te fallitur.", "Zrak, hmat a chuť se v tobě mýlí.", "Z Adoro te. Odtud vize."]),
  n("tactus", "tāctūs m.", "hmat, dotek", ["Visus, tactus, gustus", "Zrak, hmat, chuť", "Z Adoro te. Odtud kontakt."]),
  n("auditus", "audītūs m.", "sluch", ["Sed auditu solo tuto creditur.", "Jen sluchu se dá bezpečně věřit.", "Z Adoro te. Odtud auditorium."]),
  n("pelicanus", "pelicānī m.", "pelikán", ["Pie pelicane, Iesu Domine", "Dobrotivý pelikáne, Pane Ježíši", "Z Adoro te. Pelikán krmící mláďata krví je symbol Krista."]),
  n("scelus", "sceleris n.", "zločin, hřích", ["Ab omni scelere", "Od každého zločinu", "Gen. sceleris."]),
  a("immaculatus", "immaculāta, immaculātum", "neposkvrněný", ["Immaculata Conceptio", "Neposkvrněné početí", "In- + macula = skvrna."]),
  n("conceptio", "conceptiōnis f.", "početí", ["Immaculata Conceptio", "Neposkvrněné početí", "Od concipere. Odtud koncepce."]),
  n("sinus", "sinūs m.", "náruč, lůno", ["In sinu Patris", "V náručí Otce", "Jan 1,18."]),
  n("sanctitas", "sānctitātis f.", "svatost", ["Sanctitas vitae", "Svatost života", "Od sanctus."]),
  n("votum", "vōtī n.", "slib, přání", ["Votum facere", "Složit slib", "Odtud votivní mše."]),
  n("probrum", "probrī n.", "potupa, hanba", ["Probrum est mentiri.", "Lhát je hanba."]),
  n("deliciae", "dēliciārum f. pl.", "rozkoš, potěšení", ["Deliciae meae esse cum filiis hominum", "Mou rozkoší je být se syny lidskými", "Př 8,31. Jen v množném čísle."]),
  a("dilectus", "dīlēcta, dīlēctum", "milovaný", ["Hic est Filius meus dilectus.", "Toto je můj milovaný Syn.", "Mt 3,17. Od diligere."]),
  v("placo", "plācāre, plācāvī, plācātum", "usmiřuji", ["Iram Dei placare", "Usmířit Boží hněv", "Neplést s placeo = líbím se."]),
  o("autem", "spojka", "však, ale", ["Dixit autem Iesus.", "Ježíš však řekl.", "Stojí obvykle za prvním slovem věty."]),
  v("repudio", "repudiāre, repudiāvī, repudiātum", "zavrhuji", ["Ne repudies me.", "Nezavrhuj mě.", "Odtud repudiace."]),
  v("discedo", "discēdere, discessī, discessum", "odcházím, odstupuji", ["Discedite a me, maledicti.", "Odejděte ode mne, zlořečení.", "Mt 25,41."]),
  n("miseria", "miseriae f.", "bída, neštěstí", ["Miseria hominis", "Bída člověka", "Od miser. Odtud mizérie."]),
  n("fames", "famis f.", "hlad", ["Fames et sitis", "Hlad a žízeň", "Abl. fame: fame pereo = hynu hladem."]),
  v("pereo", "perīre, periī, peritum", "hynu, zanikám", ["Ego autem hic fame pereo.", "Já tu však hynu hladem.", "Lk 15,17. Časuje se jako eo."]),
  n("opinio", "opīniōnis f.", "mínění, názor", ["Opinio hominum", "Mínění lidí", "Odtud opinie."]),
  n("ovile", "ovīlis n.", "ovčinec, stádo", ["Unum ovile et unus pastor", "Jeden ovčinec a jeden pastýř", "Jan 10,16. Od ovis."]),
  v("vindico", "vindicāre, vindicāvī, vindicātum", "osvobozuji, nárokuji", ["Vindica causam meam.", "Ujmi se mé pře.", "Odtud vindikace."]),
  v("renuo", "renuere, renuī", "odmítám", ["Renuit consolari anima mea.", "Má duše se nechtěla dát potěšit.", "Ž 77."]),
  o("denique", "příslovce", "konečně, nakonec", ["Denique omnia vincit amor.", "Nakonec láska všechno přemůže."]),
  o("olim", "příslovce", "kdysi, jednou", ["Olim erat rex.", "Kdysi byl jeden král.", "Kdysi i jednou v budoucnu."]),
  v("largior", "largīrī, largītus sum", "štědře uděluji", ["Largire nobis pacem.", "Uděl nám štědře pokoj.", "Deponens. Od largus = štědrý."]),
  n("tranquillitas", "tranquillitātis f.", "klid, pokoj", ["Tranquillitas animi", "Klid mysli", "Odtud trankvilizér."]),
  v("perficio", "perficere, perfēcī, perfectum", "dokonávám", ["Opus perfecit.", "Dokonal dílo.", "Per + facere. Odtud perfektní."]),
  a("supernus", "superna, supernum", "nebeský, horní", ["Imple superna gratia", "Naplň nebeskou milostí", "Z hymnu Veni Creator."]),
  n("paraclitus", "paraclitī m.", "Utěšitel, přímluvce", ["Qui diceris Paraclitus", "Jenž se nazýváš Utěšitel", "Z hymnu Veni Creator. Řecky = přivolaný na pomoc."]),
  n("unctio", "ūnctiōnis f.", "pomazání", ["Spiritalis unctio", "Duchovní pomazání", "Z hymnu Veni Creator."]),
  a("septiformis", "septiforme", "sedmerý", ["Tu septiformis munere", "Ty, sedmerý svými dary", "Z hymnu Veni Creator: sedm darů Ducha Svatého."]),
  n("digitus", "digitī m.", "prst", ["Digitus paternae dexterae", "Prst Otcovy pravice", "Z hymnu Veni Creator. Odtud digitální."]),
  a("paternus", "paterna, paternum", "otcovský", ["Digitus paternae dexterae", "Prst Otcovy pravice", "Z hymnu Veni Creator. Od pater."]),
  o("rite", "příslovce", "náležitě, řádně", ["Rite peracta missa", "Řádně sloužená mše", "Od ritus = obřad."]),
  n("sermo", "sermōnis m.", "řeč, slovo", ["Sermone ditans guttura", "Obohacuješ hrdla řečí", "Z hymnu Veni Creator. Gen. sermonis."]),
  v("dito", "ditāre, ditāvī, ditātum", "obohacuji", ["Sermone ditans guttura", "Obohacuješ hrdla řečí", "Z hymnu Veni Creator. Od dives = bohatý."]),
  v("firmo", "fīrmāre, fīrmāvī, fīrmātum", "posiluji, upevňuji", ["Virtute firmans perpeti", "Posiluješ trvalou silou", "Z hymnu Veni Creator. Odtud firma."]),
  v("repello", "repellere, reppulī, repulsum", "odháním, odrážím", ["Hostem repellas longius.", "Zažeň nepřítele co nejdál.", "Z hymnu Veni Creator. Odtud repelent."]),
  o("longe", "příslovce", "daleko", ["Longe a nobis", "Daleko od nás", "2. stupeň longius = dále."]),
  o("protinus", "příslovce", "ihned, hned", ["Pacemque dones protinus.", "A hned nám daruj pokoj.", "Z hymnu Veni Creator."]),
  n("ductor", "ductōris m.", "vůdce", ["Ductore sic te praevio", "Když nás tak vedeš ty", "Z hymnu Veni Creator. Od ducere."]),
  o("sic", "příslovce", "tak", ["Sic Deus dilexit mundum.", "Tak Bůh miloval svět.", "Jan 3,16."]),
  a("praevius", "praevia, praevium", "jdoucí napřed", ["Ductore sic te praevio", "Když ty jdeš před námi jako vůdce", "Z hymnu Veni Creator. Prae + via."]),
  v("vito", "vītāre, vītāvī, vītātum", "vyhýbám se", ["Vitemus omne noxium.", "Vyhněme se všemu škodlivému.", "Z hymnu Veni Creator."]),
  a("noxius", "noxia, noxium", "škodlivý", ["Vitemus omne noxium.", "Vyhněme se všemu škodlivému.", "Z hymnu Veni Creator. Od noxa = škoda."]),
  n("illustratio", "illūstrātiōnis f.", "osvícení", ["Illustratio cordis", "Osvícení srdce", "Odtud ilustrace."]),
  a("almus", "alma, almum", "vznešený, dobrotivý", ["Alma Redemptoris Mater", "Vznešená Matko Vykupitelova", "Začátek mariánské antifony. Odtud alma mater."]),
  n("partus", "partūs m.", "porod", ["Post partum Virgo inviolata permansisti.", "Po porodu jsi zůstala Pannou neporušenou.", "Mariánský verš."]),
  n("virginitas", "virginitātis f.", "panenství", ["Virginitas Mariae", "Panenství Mariino", "Od virgo."]),
  a("fecundus", "fēcunda, fēcundum", "plodný", ["Terra fecunda", "Úrodná země", "Odtud fekundita."]),
  o("valde", "příslovce", "velmi", ["Erant valde bona.", "Bylo to velmi dobré.", "Gn 1,31."]),
  a("decorus", "decōra, decōrum", "krásný, ozdobný", ["Domus decora", "Krásný dům", "Od decus = ozdoba. Odtud dekorace."]),
  n("fragilitas", "fragilitātis f.", "křehkost, slabost", ["Fragilitas humana", "Lidská křehkost", "Od fragilis. Odtud fragilní."]),
  n("iniquitas", "inīquitātis f.", "nepravost, hřích", ["Dele iniquitatem meam.", "Zahlaď mou nepravost.", "Ž 51. In- + aequus."]),
  n("vallis", "vallis f.", "údolí", ["In hac lacrimarum valle", "V tomto slzavém údolí", "Z antifony Salve Regina."]),
  o("eia", "citoslovce", "nuže, ach", ["Eia ergo, advocata nostra", "Nuže tedy, orodovnice naše", "Z antifony Salve Regina."]),
  n("necessitas", "necessitātis f.", "nouze, potřeba", ["In necessitatibus nostris", "V našich potřebách", "Z modlitby Pod tvou ochranu."]),
  a("inviolatus", "inviolāta, inviolātum", "neporušený", ["Inviolata, integra et casta es, Maria.", "Neporušená, celistvá a čistá jsi, Maria.", "Začátek mariánské sekvence. In- + violare."]),
  a("intemeratus", "intemerāta, intemerātum", "neposkvrněný", ["O intemerata", "Ó neposkvrněná", "Mariánský titul. In- + temerare = poskvrnit."]),
  a("amabilis", "amābile", "milý, laskavý", ["Mater amabilis", "Matko láskyhodná", "Z Loretánských litanií."]),
  a("honorabilis", "honōrābile", "ctihodný", ["Vas honorabile", "Nádobo ctihodná", "Z Loretánských litanií."]),
  n("devotio", "dēvōtiōnis f.", "zbožnost", ["Vas insigne devotionis", "Nádobo vznešená zbožnosti", "Z Loretánských litanií. Odtud devoce."]),
  a("eburneus", "eburnea, eburneum", "slonovinový", ["Turris eburnea", "Věži ze slonoviny", "Z Loretánských litanií. Od ebur = slonovina."]),
  a("aureus", "aurea, aureum", "zlatý", ["Domus aurea", "Dome zlatý", "Z Loretánských litanií. Od aurum."]),
  n("foedus", "foederis n.", "smlouva, úmluva", ["Foederis arca", "Archo úmluvy", "Z Loretánských litanií. Odtud federace."]),
  n("arca", "arcae f.", "truhla, archa", ["Arca Noe", "Noemova archa", "Gn 6. Česky archa."]),
  n("ianua", "iānuae f.", "brána, dveře", ["Ianua caeli", "Brána nebeská", "Z Loretánských litanií."]),
  a("matutinus", "mātūtīna, mātūtīnum", "ranní, jitřní", ["Stella matutina", "Hvězdo jitřní", "Z Loretánských litanií. Odtud matiné."]),
  n("consolatrix", "cōnsōlātrīcis f.", "utěšitelka", ["Consolatrix afflictorum", "Těšitelko zarmoucených", "Z Loretánských litanií."]),
  a("afflictus", "afflīcta, afflīctum", "zarmoucený, sklíčený", ["Consolatrix afflictorum", "Těšitelko zarmoucených", "Z Loretánských litanií. Odtud aflikce."]),
  a("christianus", "chrīstiāna, chrīstiānum", "křesťanský", ["Auxilium christianorum", "Pomocnice křesťanů", "Z Loretánských litanií."]),
  n("confessor", "cōnfessōris m.", "vyznavač", ["Regina confessorum", "Královno vyznavačů", "Z Loretánských litanií. Od confiteri."]),
  n("labes", "lābis f.", "poskvrna, skvrna", ["Sine labe concepta", "Počatá bez poskvrny", "Mariánský titul. Gen. labis."]),
  a("originalis", "orīgināle", "původní, dědičný", ["Sine labe originali", "Bez poskvrny dědičného hříchu", "Z Loretánských litanií. Odtud originál."]),
  v("assumo", "assūmere, assūmpsī, assūmptum", "přijímám, beru k sobě", ["In caelum assumpta", "Vzatá do nebe", "Z Loretánských litanií. Odtud asumpce."]),
  n("sanitas", "sānitātis f.", "zdraví", ["Sanitas mentis et corporis", "Zdraví duše i těla", "Odtud sanitka."]),
  a("praesens", "gen. praesentis", "přítomný", ["Praesens auxilium", "Pomoc v přítomnosti", "Odtud prezence."]),
  n("tristitia", "trīstitiae f.", "smutek", ["Tristitia vestra vertetur in gaudium.", "Váš smutek se obrátí v radost.", "Jan 16,20. Od tristis."]),
  v("perfruor", "perfruī, perfrūctus sum", "plně užívám", ["Aeterna gloria perfruantur.", "Ať se plně těší z věčné slávy.", "Deponens s ablativem."]),
  n("proles", "prōlis f.", "potomstvo, potomek", ["Proles David inclita", "Slavný potomku Davidův", "Z litanií ke sv. Josefovi."]),
  a("inclitus", "inclita, inclitum", "slavný, proslulý", ["Proles David inclita", "Slavný potomku Davidův", "Z litanií ke sv. Josefovi. Píše se i inclytus."]),
  a("pudicus", "pudīca, pudīcum", "cudný", ["Custos pudice Virginis", "Cudný strážce Panny", "Z litanií ke sv. Josefovi."]),
  n("nutricius", "nūtrīciī m.", "pěstoun, živitel", ["Filii Dei nutricie", "Pěstoune Syna Božího", "Z litanií ke sv. Josefovi. Od nutrire = živit."]),
  n("defensor", "dēfēnsōris m.", "obhájce, ochránce", ["Christi defensor sedule", "Horlivý ochránce Krista", "Z litanií ke sv. Josefovi. Odtud defenzíva."]),
  a("sedulus", "sēdula, sēdulum", "horlivý, pečlivý", ["Christi defensor sedule", "Horlivý ochránce Krista", "Z litanií ke sv. Josefovi."]),
  n("praeses", "praesidis m.", "představený, ochránce", ["Almae Familiae praeses", "Představený svaté Rodiny", "Z litanií ke sv. Josefovi. Od praesidere = předsedat."]),
  a("oboediens", "gen. oboedientis", "poslušný", ["Ioseph oboedientissime", "Josefe nejposlušnější", "Z litanií ke sv. Josefovi."]),
  n("amator", "amātōris m.", "milovník", ["Amator paupertatis", "Milovníku chudoby", "Z litanií ke sv. Josefovi. Odtud amatér."]),
  n("opifex", "opificis m.", "řemeslník, dělník", ["Exemplar opificum", "Vzore dělníků", "Z litanií ke sv. Josefovi. Opus + facere."]),
  a("domesticus", "domestica, domesticum", "domácí", ["Domesticae vitae decus", "Ozdobo domácího života", "Z litanií ke sv. Josefovi. Od domus."]),
  n("columen", "columinis n.", "opora, sloup", ["Familiarum columen", "Oporo rodin", "Z litanií ke sv. Josefovi."]),
  n("solatium", "sōlātiī n.", "útěcha", ["Solatium miserorum", "Útěcho ubohých", "Z litanií ke sv. Josefovi."]),
  v("aegroto", "aegrōtāre, aegrōtāvī, aegrōtātum", "stůňu, jsem nemocen", ["Spes aegrotantium", "Naděje nemocných", "Z litanií ke sv. Josefovi. Od aeger."]),
  n("patronus", "patrōnī m.", "ochránce, patron", ["Patrone morientium", "Patrone umírajících", "Z litanií ke sv. Josefovi."]),
  n("terror", "terrōris m.", "strach, hrůza", ["Terror daemonum", "Postrachu zlých duchů", "Z litanií ke sv. Josefovi. Odtud teror."]),
  n("daemon", "daemonis m.", "démon, zlý duch", ["Terror daemonum", "Postrachu zlých duchů", "Z litanií ke sv. Josefovi. Z řeckého daimón."]),
  n("protector", "prōtēctōris m.", "ochránce", ["Protector sanctae Ecclesiae", "Ochránce svaté církve", "Z litanií ke sv. Josefovi. Odtud protekce."]),
  n("possessio", "possessiōnis f.", "majetek", ["Princeps omnis possessionis suae", "Správce všeho svého majetku", "Z litanií ke sv. Josefovi. Odtud posese."]),
  a("ineffabilis", "ineffābile", "nevýslovný", ["Ineffabilis Deus", "Nevýslovný Bůh", "Bula o Neposkvrněném početí (1854). In- + fari = mluvit."]),
  n("providentia", "prōvidentiae f.", "prozřetelnost", ["Providentia Dei", "Boží prozřetelnost", "Pro + videre = předvídat."]),
  v("confirmo", "cōnfīrmāre, cōnfīrmāvī, cōnfīrmātum", "posiluji, potvrzuji", ["Confirma hoc, Deus.", "Utvrď to, Bože.", "Ž 68. Odtud konfirmace."]),
  n("grex", "gregis m.", "stádo", ["Pusillus grex", "Malé stádce", "Lk 12,32. Gen. gregis; odtud kongregace."]),
  a("cernuus", "cernua, cernuum", "sklonený, poklekající", ["Veneremur cernui.", "Uctívejme hluboce skloněni.", "Z Tantum ergo."]),
]);
