import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 5", [
  o("ipse", "zájmeno (ipsa, ipsum)", "sám; on", ["Et ipse redimet Israel ex omnibus iniquitatibus eius.", "A on vykoupí Izraele ze všech jeho nepravostí.", "Ž 130,8. Gen. ipsīus."]),
  v("exsurgo", "exsurgere, exsurrēxī, exsurrēctum", "povstávám, vstávám", ["Exsurge, Domine, adiuva nos.", "Povstaň, Pane, pomoz nám.", "Ž 44,27. Ex + surgo."]),
  o("vel", "spojka", "nebo, anebo", ["Hodie vel cras veniam.", "Přijdu dnes nebo zítra.", "Vel – vel = buď – anebo (volná volba, na rozdíl od aut)."]),
  o("septem", "číslovka nesklonná", "sedm", ["Septem sacramenta", "Sedm svátostí", "Srov. září – September (původně sedmý měsíc)."]),
  o("alius", "zájmeno (alia, aliud)", "jiný, druhý", ["Satanam aliosque spiritus malignos", "satana a jiné zlé duchy", "Z modlitby k sv. Michaelu archandělovi. Gen. sg. obvykle alterīus."]),
  n("mensa", "mēnsae f.", "stůl", ["Benedictio mensae", "Požehnání stolu", "Srov. menza."]),
  v("incipio", "incipere, incēpī, inceptum", "začínám", ["Cuncta nostra operatio a te semper incipiat.", "Ať všechno naše jednání vždy u tebe začíná.", "Z modlitby Actiones nostras."]),
  v("adsum", "adesse, adfuī", "jsem přítomen; pomáhám", ["Adesto, Domine, supplicationibus nostris.", "Vyslyš, Pane, naše prosby.", "Ad + sum; s dativem. Imper. budoucí adestō."]),
  o("nemo", "zájmeno (gen. nūllīus, dat. nēminī)", "nikdo", ["Gaudium vestrum nemo tollet a vobis.", "Vaši radost vám nikdo nevezme.", "J 16,22. Z ne + homo."]),
  v("consequor", "cōnsequī, cōnsecūtus sum", "dosahuji, docházím (čeho)", ["Beati misericordes, quia ipsi misericordiam consequentur.", "Blahoslavení milosrdní, neboť oni dojdou milosrdenství.", "Mt 5,7. Česky konsekvence."]),
  n("iudex", "iūdicis m.", "soudce", ["Iudex crederis esse venturus.", "Věříme, že přijdeš jako soudce.", "Z Te Deum."]),
  n("actio", "āctiōnis f.", "jednání, čin, úkon", ["Actiones nostras, quaesumus, Domine, aspirando praeveni.", "Naše skutky, prosíme, Pane, svým vnuknutím předcházej.", "Gratiarum actio = díkůvzdání. Odtud akce."]),
  o("magis", "příslovce", "více, spíše", ["Amicus Plato, sed magis amica veritas.", "Platón je přítel, ale větší přítel je pravda.", "Stupňování: magis – maxime."]),
  v("iungo", "iungere, iūnxī, iūnctum", "spojuji, připojuji", ["Nos iunge beatis.", "Připoj nás k blaženým.", "Srov. jugum = jho, konjunkce."]),
  a("perfectus", "perfecta, perfectum", "dokonalý", ["Estote ergo vos perfecti, sicut et Pater vester caelestis perfectus est.", "Buďte tedy dokonalí, jako je dokonalý váš nebeský Otec.", "Mt 5,48. Původně příčestí od perficio."]),
  v("coniungo", "coniungere, coniūnxī, coniūnctum", "spojuji", ["Quod ergo Deus coniunxit, homo non separet.", "Co tedy Bůh spojil, člověk ať nerozlučuje.", "Mt 19,6. Česky konjunkce."]),
  o("ac", "spojka", "a, a také", ["Deus caelum ac terram creavit.", "Bůh stvořil nebe a zemi.", "Kratší tvar spojky atque; klade se jen před souhlásky."]),
  a("vanus", "vāna, vānum", "marný, prázdný", ["Non assumes nomen Domini Dei tui in vanum.", "Nevezmeš jména Pána Boha svého nadarmo.", "Druhé přikázání (Ex 20,7). In vanum = nadarmo."]),
  v("addo", "addere, addidī, additum", "přidávám, připojuji", ["Adde unum Pater noster.", "Přidej jeden Otčenáš.", "Ad + do."]),
  v("advenio", "advenīre, advēnī, adventum", "přicházím", ["Adveniat regnum tuum.", "Přijď království tvé.", "Z Otčenáše. Srov. advent."]),
  o("quantus", "zájmeno (quanta, quantum)", "jak velký; kolik", ["Quanta est misericordia Dei!", "Jak veliké je Boží milosrdenství!", "Tantus – quantus = tak velký – jak velký."]),
  o("tantum", "příslovce", "jen, pouze; tolik", ["Sed tantum dic verbo, et sanabitur puer meus.", "Ale řekni jen slovo, a můj služebník bude uzdraven.", "Mt 8,8. Tantum – quantum = tolik – kolik."]),
  n("aetas", "aetātis f.", "věk; doba", ["Et Iesus proficiebat sapientia et aetate et gratia apud Deum et homines.", "A Ježíš prospíval moudrostí, věkem a milostí u Boha i u lidí.", "Lk 2,52."]),
  o("alter", "zájmeno (altera, alterum)", "druhý (ze dvou), jiný", ["Alter alterius onera portate.", "Neste břemena jedni druhých.", "Gal 6,2. Gen. alterīus. Srov. alternativa."]),
  a("ceterus", "cētera, cēterum", "ostatní, další", ["Ceterum censeo Carthaginem esse delendam.", "Ostatně soudím, že Kartágo musí být zničeno.", "Výrok připisovaný Catonovi st. Zkratka etc. = et cetera."]),
  v("contineo", "continēre, continuī, contentum", "obsahuji; držím pohromadě", ["Hic liber multas orationes continet.", "Tato kniha obsahuje mnoho modliteb.", "Srov. kontinent, kontejner."]),
  o("extra", "příslovce; předložka + akuz.", "venku, vně; mimo", ["Pueri extra urbem ludunt.", "Chlapci si hrají za městem.", "Srov. extra-, extrémní."]),
  o("nec", "spojka", "a ne, ani", ["Nec aurum nec argentum habeo.", "Nemám ani zlato, ani stříbro.", "Nec … nec = ani … ani. Totéž co neque."]),
  o("postea", "příslovce", "potom, později", ["Postea dicitur Pater noster.", "Potom se říká Otčenáš."]),
  o("quasi", "příslovce, spojka", "jako, jakoby; téměř", ["Omnes nos quasi oves erravimus.", "Všichni jsme bloudili jako ovce.", "Iz 53,6. Srov. kvazi-."]),
  o("diu", "příslovce", "dlouho", ["Diu vixit et feliciter.", "Žil dlouho a šťastně.", "Stupňování: diūtius, diūtissimē."]),
  a("firmus", "firma, firmum", "pevný, silný", ["Fides nostra firma est.", "Naše víra je pevná.", "Opak infirmus (slabý, nemocný); česky firma."]),
  o("maxime", "příslovce", "nejvíce, především", ["Quae misericordiae tuae maxime indigent.", "Které nejvíce potřebují tvého milosrdenství.", "Z fatimské modlitby (O mi Iesu). 3. stupeň k magis; česky maximum."]),
  a("minor", "minus, gen. minōris", "menší", ["Ordo Fratrum Minorum", "Řád menších bratří", "Františkáni. 2. stupeň k parvus; česky minorita."]),
  a("paratus", "parata, paratum", "připravený", ["Paratum cor meum, Deus.", "Připraveno je mé srdce, Bože.", "Ž 57,8. Původně příčestí od paro."]),
  v("promitto", "prōmittere, prōmīsī, prōmissum", "slibuji", ["Et quod promittunt assequamur.", "A dosáhli toho, co slibují.", "Z modlitby po růženci."]),
  v("saluto", "salūtāre, salūtāvī, salūtātum", "zdravím", ["Ave, imperator, morituri te salutant.", "Buď zdráv, císaři, jdoucí na smrt tě zdraví.", "Podle Suetonia. Česky salutovat."]),
  o("supra", "předložka + akuz.", "nad", ["Aves supra terram volant.", "Ptáci létají nad zemí.", "Též příslovce (nahoře, výše)."]),
  n("uxor", "uxōris f.", "manželka", ["Non desiderabis uxorem eius.", "Nebudeš toužit po jeho manželce.", "Deváté přikázání."]),
  v("compono", "compōnere, composuī, compositum", "skládám, uspořádávám", ["Poeta carmen componit.", "Básník skládá báseň.", "Odtud kompozice, komponovat."]),
  v("desidero", "dēsīderāre, dēsīderāvī, dēsīderātum", "toužím, žádám", ["Non desiderabis uxorem proximi tui.", "Nepožádáš manželky bližního svého.", "Deváté přikázání. Odtud dezideráta."]),
  a("diversus", "dīversa, dīversum", "různý, rozdílný", ["Diversis linguis Deum laudamus.", "Chválíme Boha různými jazyky.", "Odtud diverzita."]),
  a("futurus", "futūra, futūrum", "budoucí", ["Et futurae gloriae nobis pignus datur.", "A dává se nám záruka budoucí slávy.", "Z antifony O sacrum convivium. Příčestí budoucí od sum."]),
  o("inde", "příslovce", "odtud; potom", ["Inde venturus est iudicare vivos et mortuos.", "Odtud přijde soudit živé i mrtvé.", "Z Vyznání víry."]),
  v("intersum", "interesse, interfuī", "jsem přítomen, účastním se", ["Missae interesse debemus.", "Máme se účastnit mše.", "Pojí se s dativem. Neosobní interest = záleží na."]),
  n("natio", "nātiōnis f.", "národ, kmen", ["Ex omnibus nationibus fideles conveniunt.", "Věřící se scházejí ze všech národů.", "Odtud nacionalismus."]),
  v("occido", "occīdere, occīdī, occīsum", "zabíjím", ["Non occides.", "Nezabiješ.", "Páté přikázání (Ex 20,13). Nezaměňovat s occĭdo = zapadám."]),
  n("ratio", "ratiōnis f.", "rozum; důvod; účet", ["Redde rationem vilicationis tuae.", "Vydej počet ze svého správcovství.", "Lk 16,2. Odtud racionální."]),
  n("umbra", "umbrae f.", "stín", ["Sub umbra alarum tuarum protege me.", "Ve stínu svých křídel mě ukryj.", "Ž 17,8."]),
  n("processio", "prōcessiōnis f.", "procesí, průvod", ["Post Missam fit processio.", "Po mši se koná procesí.", "Odtud procesí."]),
  a("dominicus", "dominica, dominicum", "Páně; nedělní", ["Oratio Dominica.", "Modlitba Páně.", "Dominica (diēs) = neděle. Od dominus."]),
  n("versus", "versūs m.", "verš", ["Poeta versus pulchros scribit.", "Básník píše krásné verše.", "Od vertere – obracet. Pozor: versus též předložka „směrem k“."]),
  n("psalmus", "psalmī m.", "žalm", ["Septem psalmi paenitentiales.", "Sedm kajících žalmů.", "Z řečtiny (psalmos)."]),
  v("subvenio", "subvenīre, subvēnī, subventum", "přicházím na pomoc, pomáhám", ["Te ergo quaesumus, tuis famulis subveni.", "Proto tě prosíme, přispěj na pomoc svým služebníkům.", "Z Te Deum. Pojí se s dativem."]),
  n("praedicator", "praedicātōris m.", "kazatel, hlasatel", ["Ordo Fratrum Praedicatorum", "Řád bratří kazatelů", "Oficiální název dominikánů (OP)."]),
  a("profundus", "profunda, profundum", "hluboký", ["De profundis clamavi ad te, Domine.", "Z hlubin volám k tobě, Hospodine.", "Ž 130,1. Subst. profundum = hlubina."]),
  n("domina", "dominae f.", "paní, vládkyně", ["Maria est Domina nostra.", "Maria je naše Paní.", "Ženský protějšek k dominus; srov. madona."]),
  a("singulus", "singula, singulum", "jednotlivý, každý", ["Per singulos dies benedicimus te.", "Každý den tě velebíme.", "Z Te Deum. Obvykle v pl.: singulī, -ae, -a."]),
  v("flecto", "flectere, flexī, flexum", "ohýbám, skláním", ["Ut in nomine Iesu omne genu flectatur.", "Aby se ve jménu Ježíšově sklonilo každé koleno.", "Flp 2,10. Srov. reflex, flexibilní."]),
  n("pectus", "pectoris n.", "hruď, prsa; srdce", ["Imple superna gratia quae tu creasti pectora.", "Naplň nebeskou milostí srdce, která jsi stvořil.", "Z hymnu Veni Creator."]),
  v("sustineo", "sustinēre, sustinuī, sustentum", "snáším, vydržím; podpírám", ["Domine, quis sustinebit?", "Pane, kdo obstojí?", "Ž 130,3. Sub + teneo."]),
  a("propitius", "propitia, propitium", "milostivý, příznivý", ["Propitius esto, parce nobis, Domine.", "Buď milostiv, ušetři nás, Pane.", "Z litanie ke všem svatým."]),
  v("intendo", "intendere, intendī, intentum", "napínám, zaměřuji, dbám", ["Deus, in adiutorium meum intende.", "Bože, shlédni a pomoz mi.", "Ž 70,2; úvod denní modlitby církve. Odtud intence."]),
  n("eucharistia", "eucharistiae f.", "eucharistie", ["Eucharistiae sacramentum saltem in Paschate recipere.", "Přijímat svátost eucharistie aspoň v době velikonoční.", "Z církevních přikázání. Z řec. eucharistia = díkůvzdání."]),
  v("sapio", "sapere, sapīvī / sapuī", "jsem moudrý, chápu; chutnám", ["Da nobis in eodem Spiritu recta sapere.", "Dej nám v témže Duchu poznávat, co je správné.", "Z modlitby Deus, qui corda fidelium. Srov. homo sapiens."]),
  n("cena", "cēnae f.", "večeře, hostina", ["Ad cenam vitae aeternae perducat nos Rex gloriae.", "K hostině věčného života ať nás přivede Král slávy.", "Cena Domini = Poslední večeře."]),
  v("illumino", "illūmināre, illūmināvī, illūminātum", "osvěcuji", ["Me tibi commissum illumina, custodi, rege et guberna.", "Mne tobě svěřeného osvěcuj, ochraňuj, veď a spravuj.", "Z modlitby k andělu strážci (Angele Dei). Srov. iluminace."]),
  n("pondus", "ponderis n.", "váha, tíha, břemeno", ["Peccatorum nostrorum pondere premimur.", "Tíží nás břemeno našich hříchů.", "Srov. ponderovat."]),
  v("absolvo", "absolvere, absolvī, absolūtum", "rozhřešuji, osvobozuji; dokončuji", ["Ego te absolvo a peccatis tuis.", "Já tě rozhřešuji z tvých hříchů.", "Ze svátosti smíření. Česky absolvovat, absolutní."]),
  n("regula", "rēgulae f.", "pravidlo; řehole", ["Regula aurea", "Zlaté pravidlo", "Tak se nazývá Mt 7,12. Česky regule, regulovat."]),
  v("dispono", "dispōnere, disposuī, dispositum", "uspořádávám, řídím", ["Deus omnia sapienter disponit.", "Bůh vše moudře řídí.", "Odtud dispozice."]),
  v("renovo", "renovāre, renovāvī, renovātum", "obnovuji", ["Et renovabis faciem terrae.", "A obnovíš tvář země.", "Ž 104,30. Odtud renovace."]),
  v("affligo", "afflīgere, afflīxī, afflīctum", "sužuji, trápím", ["Consolatrix afflictorum, ora pro nobis.", "Těšitelko zarmoucených, oroduj za nás.", "Z litanií loretánských."]),
  o("clementer", "příslovce", "milostivě, laskavě", ["Respice, Domine, clementer populum tuum.", "Shlédni, Pane, milostivě na svůj lid.", "Od clemens; srov. klemence."]),
  a("copiosus", "cōpiōsa, cōpiōsum", "hojný, bohatý", ["Merces vestra copiosa est in caelis.", "Vaše odměna v nebesích je hojná.", "Mt 5,12. Od copia = hojnost."]),
  a("devotus", "dēvōta, dēvōtum", "zbožný, oddaný", ["Populus devotus Deum laudat.", "Zbožný lid chválí Boha.", "Původně příčestí od devoveo; srov. devótní."]),
  n("merces", "mercēdis f.", "odměna, mzda", ["Dignus est operarius mercede sua.", "Dělník je hoden své mzdy.", "Lk 10,7."]),
  o("praesertim", "příslovce", "zvláště, obzvláště", ["Praesertim eas, quae misericordiae tuae maxime indigent.", "Zvláště ty, které tvého milosrdenství nejvíce potřebují.", "Z fatimské modlitby O mi Iesu."]),
  o("saltem", "příslovce", "aspoň, alespoň", ["Peccata saltem semel in anno confiteri.", "Aspoň jednou za rok se vyzpovídat.", "Z církevních přikázání."]),
  a("temporalis", "temporāle", "časný, pozemský, pomíjivý", ["Bona temporalia transeunt.", "Časná dobra pomíjejí.", "Od tempus; opak aeternus."]),
  a("angelicus", "angelica, angelicum", "andělský", ["Panis angelicus fit panis hominum.", "Chléb andělský stává se chlebem lidí.", "Z hymnu Sacris solemniis sv. Tomáše Akvinského."]),
  n("beneficium", "beneficiī n.", "dobrodiní, laskavost", ["Agimus tibi gratias pro universis beneficiis tuis.", "Děkujeme ti za všechna tvá dobrodiní.", "Z modlitby po jídle. Srov. benefice."]),
  n("comes", "comitis m./f.", "průvodce, druh", ["Angelo tuo sancto comite.", "Se svatým andělem tvým jako průvodcem.", "Srov. hrabě (comes) – původně průvodce panovníka."]),
  n("esca", "ēscae f.", "pokrm, jídlo", ["Et tu das escam illorum in tempore opportuno.", "A ty jim dáváš pokrm v pravý čas.", "Ž 145,15. Modlitba před jídlem."]),
  v("festino", "festīnāre, festīnāvī, festīnātum", "spěchám, pospíchám", ["Domine, ad adiuvandum me festina.", "Pane, pospěš mi na pomoc.", "Ž 70,2. Úvod denní modlitby církve."]),
  n("ministerium", "ministeriī n.", "služba, úřad", ["Per ministerium Ecclesiae indulgentiam tibi tribuat et pacem.", "Skrze službu církve ať ti udělí odpuštění a pokoj.", "Z formule rozhřešení. Srov. ministerstvo."]),
  n("redemptio", "redēmptiōnis f.", "vykoupení", ["Et copiosa apud eum redemptio.", "A hojné je u něho vykoupení.", "Ž 130,7. Od redimo."]),
  v("saturo", "saturāre, saturāvī, saturātum", "sytím, nasycuji", ["Beati qui esuriunt et sitiunt iustitiam, quoniam ipsi saturabuntur.", "Blahoslavení, kdo hladovějí a žízní po spravedlnosti, neboť oni budou nasyceni.", "Mt 5,6. Srov. saturovat."]),
  o("demum", "příslovce", "konečně, teprve", ["Tum demum intellexit.", "Teprve tehdy pochopil."]),
  v("excipio", "excipere, excēpī, exceptum", "přijímám; vyjímám", ["Hospites excipere.", "Přijímat pocestné.", "Ze skutků tělesného milosrdenství. Excepto = kromě; česky výjimka, exception."]),
  n("fortitudo", "fortitūdinis f.", "síla; statečnost", ["Fortitudo mea et laus mea Dominus.", "Má síla a má chvála je Hospodin.", "Ex 15,2. Statečnost je jedna ze čtyř základních ctností."]),
  v("pergo", "pergere, perrēxī, perrēctum", "pokračuji, ubírám se", ["Fratres ad capitulum pergunt.", "Bratři se ubírají do kapituly."]),
  v("prosequor", "prōsequī, prōsecūtus sum", "doprovázím, pokračuji", ["Aspirando praeveni et adiuvando prosequere.", "Svým vnuknutím nás předcházej a svou pomocí provázej.", "Z modlitby Actiones nostras."]),
  v("repeto", "repetere, repetīvī, repetītum", "opakuji", ["Chorus repetit antiphonam.", "Sbor opakuje antifonu.", "Česky repetice, repetent."]),
  o("unusquisque", "zájmeno (unaquaeque, unumquodque)", "každý (jednotlivý)", ["Unusquisque proprium donum habet ex Deo.", "Každý má od Boha svůj vlastní dar.", "1 Kor 7,7. Skloňují se obě části: gen. ūnīuscuiusque."]),
  n("ascensio", "ascēnsiōnis f.", "nanebevstoupení, výstup", ["Ascensio eius in caelum.", "Jeho nanebevstoupení.", "Ze slavných tajemství růžence. Od ascendo."]),
  n("castitas", "castitātis f.", "čistota, cudnost", ["Da mihi castitatem et continentiam, sed noli modo.", "Dej mi čistotu a zdrženlivost, ale ještě ne hned.", "Sv. Augustin, Vyznání 8,7."]),
  n("consolatio", "cōnsōlātiōnis f.", "útěcha", ["Et de eius semper consolatione gaudere.", "A vždy se radovat z jeho útěchy.", "Z modlitby k Duchu Svatému (Deus, qui corda fidelium)."]),
  v("detineo", "dētinēre, dētinuī, dētentum", "zdržuji, zadržuji", ["Carcere detentos invisere.", "Navštěvovat vězně.", "Ze skutků tělesného milosrdenství."]),
  v("extollo", "extollere", "pozvedám, vyvyšuji", ["Et rege eos, et extolle illos usque in aeternum.", "Spravuj je a povznes je až na věky.", "Z Te Deum. Perfektum se běžně neužívá."]),
  n("infantia", "īnfantiae f.", "dětství, útlé dětství", ["Ab infantia Deum amavit.", "Od dětství miloval Boha.", "Z infans = nemluvně."]),
  n("oblatio", "oblātiōnis f.", "obětování, oběť, dar", ["Oblatio Christi in templo.", "Obětování Ježíše v chrámě.", "Z radostných tajemství růžence. Odtud oblata."]),
  n("persecutio", "persecūtiōnis f.", "pronásledování", ["Beati, qui persecutionem patiuntur propter iustitiam.", "Blahoslavení, kdo trpí pronásledování pro spravedlnost.", "Mt 5,10."]),
  v("retribuo", "retribuere, retribuī, retribūtum", "odplácím, oplácím", ["Quid retribuam Domino pro omnibus quae retribuit mihi?", "Čím se odplatím Hospodinu za všechno, co mi prokázal?", "Ž 116,12."]),
  n("supplicatio", "supplicātiōnis f.", "prosba, úpěnlivá modlitba", ["Adesto, Domine, supplicationibus nostris.", "Vyslyš, Pane, naše prosby.", "Častý začátek liturgických modliteb."]),
  n("inferi", "īnferōrum m. pl.", "podsvětí, říše mrtvých", ["Descendit ad inferos.", "Sestoupil do pekel.", "Z Apoštolského vyznání víry. Pl. od inferus = dolní."]),
  v("abstineo", "abstinēre, abstinuī, abstentum", "zdržuji se", ["Ab esu carnium abstinere.", "Zdržovat se požívání masa.", "Z církevních přikázání. Srov. abstinence."]),
  a("acerbus", "acerba, acerbum", "trpký, krutý, bolestný", ["Mors Christi acerba fuit.", "Kristova smrt byla krutá.", "Srov. exacerbace."]),
  n("aestus", "aestūs m.", "žár, horko; vlnobití", ["In aestu temperies", "V parnu osvěžení", "Ze sekvence Veni, Sancte Spiritus."]),
  v("ardeo", "ardēre, arsī, arsum", "hořím, planu", ["Nonne cor nostrum ardens erat in nobis?", "Což nám nehořelo srdce?", "Lk 24,32."]),
  v("assequor", "assequī, assecūtus sum", "dosahuji", ["Et quod promittunt assequamur.", "A abychom dosáhli toho, co slibují.", "Z modlitby po růženci. Ad + sequor; deponens."]),
  n("aula", "aulae f.", "síň, dvůr, palác", ["Rex in aula sedet.", "Král sedí v síni.", "Srov. aula."]),
  n("baptista", "baptistae m.", "křtitel", ["Sancte Ioannes Baptista, ora pro nobis.", "Svatý Jene Křtiteli, oroduj za nás.", "Z litanií ke všem svatým. Maskulinum 1. deklinace."]),
  n("benignitas", "benignitātis f.", "dobrotivost, laskavost", ["Benignitas Dei magna est.", "Dobrotivost Boží je veliká.", "Jeden z plodů Ducha Svatého (Gal 5,22)."]),
  a("catholicus", "catholica, catholicum", "obecný, katolický", ["Sanctam Ecclesiam catholicam", "Svatou církev obecnou", "Z Apoštolského vyznání víry. Z řec. katholikos = všeobecný."]),
  n("concilium", "conciliī n.", "shromáždění; koncil", ["Concilium malignantium obsedit me.", "Obklíčila mě rota zlovolníků.", "Ž 22,17. Pozor: consilium = rada."]),
  n("confirmatio", "cōnfirmātiōnis f.", "posílení; biřmování", ["Baptismus, confirmatio et eucharistia", "Křest, biřmování a eucharistie", "Jedna ze sedmi svátostí. Od confirmo = posiluji."]),
  n("conversio", "conversiōnis f.", "obrácení", ["Conversio sancti Pauli", "Obrácení svatého Pavla", "Svátek 25. ledna. Srov. konverze."]),
  n("damnum", "damnī n.", "škoda, ztráta", ["Peccatum magnum damnum animae est.", "Hřích je velkou škodou pro duši.", "Srov. angl. damage."]),
  a("defunctus", "dēfūncta, dēfūnctum", "zemřelý", ["Pro vivis et defunctis orare.", "Modlit se za živé i zemřelé.", "Ze skutků milosrdenství duchovních. Příčestí od defungor."]),
  n("diabolus", "diabolī m.", "ďábel", ["Contra nequitiam et insidias diaboli esto praesidium.", "Proti zlobě a úkladům ďáblovým buď nám ochranou.", "Z modlitby k sv. Michaelu archandělovi. Z řec. diabolos = pomlouvač."]),
  v("extendo", "extendere, extendī, extentum", "vztahuji, rozpínám", ["Palmas suas extendit ad pauperem.", "Dlaně vztahuje k ubohému.", "Př 31,20. Srov. extenze."]),
  o("feliciter", "příslovce", "šťastně", ["Feliciter in patriam pervenimus.", "Šťastně jsme dorazili do vlasti.", "Od felix. Feliciter! = Hodně štěstí!"]),
  n("habitatio", "habitātiōnis f.", "obydlí, příbytek", ["Locum habitationis gloriae tuae", "Místo, kde přebývá tvá sláva", "Ž 26,8. Od habito = bydlím."]),
  n("hospes", "hospitis m.", "host; hostitel; cizinec", ["Hospes eram, et collegistis me.", "Byl jsem na cestách, a ujali jste se mě.", "Mt 25,35. Srov. hospic, hospitalita."]),
  v("impono", "impōnere, imposuī, impositum", "kladu na, ukládám", ["Coronam de spinis imposuerunt capiti eius.", "Korunu z trní mu vložili na hlavu.", "J 19,2. In + pono; s dativem."]),
  n("incrementum", "incrēmentī n.", "růst, vzrůst", ["Sed Deus incrementum dedit.", "Ale Bůh dal vzrůst.", "1 Kor 3,6."]),
  n("index", "indicis m.", "seznam, rejstřík; ukazatel", ["Index generalis", "Obecný rejstřík", "Také ukazováček (digitus index)."]),
  o("infra", "příslovce; předložka + akuz.", "dole, níže; pod", ["Vide infra.", "Viz níže.", "Opak supra."]),
  v("inspicio", "īnspicere, īnspexī, īnspectum", "prohlížím, hledím na", ["Ipsi vero consideraverunt et inspexerunt me.", "Oni na mě hledí a dívají se.", "Ž 22,18. Srov. inspekce."]),
  o("intus", "příslovce", "uvnitř", ["Intus et extra pura", "Uvnitř i navenek čistá", "Opak foris."]),
  v("lacrimo", "lacrimāre, lacrimāvī, lacrimātum", "pláču, slzím", ["Maria iuxta crucem lacrimabat.", "Maria plakala u kříže.", "Od lacrima = slza. Také deponens lacrimor: Et lacrimatus est Iesus (J 11,35)."]),
  n("lectio", "lēctiōnis f.", "čtení", ["Lectio libri Sapientiae", "Čtení z knihy Moudrosti", "Srov. lekce. Lectio divina = duchovní četba."]),
  a("malignus", "maligna, malignum", "zlý, zlovolný", ["Mundus totus in maligno positus est.", "Celý svět je v moci Zlého.", "1 J 5,19."]),
  v("mentior", "mentīrī, mentītus sum", "lžu", ["Dixerint omne malum adversum vos mentientes.", "Budou na vás lživě mluvit všechno zlé.", "Mt 5,11. Deponens."]),
  a("nudus", "nūda, nūdum", "nahý", ["Nudos cooperire.", "Nahé odívat.", "Ze skutků milosrdenství tělesných."]),
  n("odor", "odōris m.", "vůně, pach", ["Hostiam Deo in odorem suavitatis", "Oběť Bohu jako líbeznou vůni", "Ef 5,2. Srov. deodorant."]),
  n("opportunitas", "opportūnitātis f.", "příležitost, vhodná doba", ["Opportunitatem orandi ne amiseris.", "Nepromeškej příležitost k modlitbě.", "Pro opportunitate = podle potřeby. Srov. angl. opportunity."]),
  n("palma", "palmae f.", "dlaň; palma", ["Acceperunt ramos palmarum.", "Vzali palmové ratolesti.", "J 12,13. Dominica in Palmis = Květná neděle."]),
  n("pascha", "paschatis n.", "Velikonoce; velikonoční beránek", ["Pascha nostrum immolatus est Christus.", "Kristus, náš velikonoční beránek, byl obětován.", "1 Kor 5,7. Také pascha, -ae f.; z hebr. pesach."]),
  v("percipio", "percipere, percēpī, perceptum", "přijímám; vnímám", ["Corpus Christi digne percipiamus.", "Kéž důstojně přijímáme Tělo Kristovo.", "Srov. percepce."]),
  n("perfectio", "perfectiōnis f.", "dokonalost", ["Christus est exemplar perfectionis.", "Kristus je vzorem dokonalosti.", "Srov. perfekce."]),
  v("possideo", "possidēre, possēdī, possessum", "vlastním, mám v držení", ["Beati mites, quoniam ipsi possidebunt terram.", "Blahoslavení tiší, neboť oni dostanou zemi za dědictví.", "Mt 5,5."]),
  v("praecedo", "praecēdere, praecessī, praecessum", "jdu napřed, předcházím", ["Crux processionem praecedit.", "Kříž jde v čele průvodu.", "Prae + cedo; srov. precedens."]),
  v("recito", "recitāre, recitāvī, recitātum", "přednáším, odříkávám", ["Rosarium cotidie recito.", "Denně se modlím růženec.", "Srov. recitovat."]),
  n("servitium", "servitiī n.", "služba; otroctví", ["Vita nostra servitium Dei est.", "Náš život je službou Bohu.", "Od servus; srov. servis."]),
  a("spiritalis", "spīritāle", "duchovní", ["Fons vivus, ignis, caritas, et spiritalis unctio.", "Zdroj živý, oheň, láska, duchovní pomazání.", "Z hymnu Veni, Creator Spiritus. Varianta ke spiritualis."]),
  n("sudor", "sūdōris m.", "pot", ["In sudore vultus tui vesceris pane.", "V potu své tváře budeš jíst chléb.", "Gn 3,19."]),
  n("universitas", "ūniversitātis f.", "celek, souhrn; společenství", ["Universitas Carolina Pragae condita est.", "Univerzita Karlova byla založena v Praze.", "Srov. univerzita, universum."]),
  n("vena", "vēnae f.", "žíla; pramen", ["Sanguis per venas fluit.", "Krev proudí žilami.", "Srov. intravenózní."]),
  n("vinculum", "vinculī n.", "pouto, okov", ["Caritatem habete, quod est vinculum perfectionis.", "Mějte lásku, která je poutem dokonalosti.", "Kol 3,14."]),
  v("abundo", "abundāre, abundāvī, abundātum", "oplývám, mám hojnost", ["Ubi autem abundavit delictum, superabundavit gratia.", "Kde se však rozmohl hřích, tam se ještě více rozhojnila milost.", "Řím 5,20. Srov. abundance."]),
  a("adversus", "adversa, adversum", "nepříznivý, protivný; protější", ["In rebus adversis Deo confidimus.", "V nepříznivých věcech důvěřujeme Bohu.", "Adversa n. pl. = protivenství. Adversus též předložka + akuz. „proti“."]),
  n("ardor", "ardōris m.", "žár; horlivost", ["Ardor amoris cor inflammat.", "Žár lásky rozněcuje srdce.", "Od ardeo – hořím."]),
  v("assisto", "assistere, astitī", "stojím u, přistupuji; pomáhám", ["Astitit regina a dextris tuis.", "Po tvé pravici stojí královna.", "Ž 45,10. Srov. asistence."]),
  n("aurora", "aurōrae f.", "svítání, jitřenka", ["Anima mea ad Dominum magis quam custodes auroram.", "Má duše čeká na Pána víc než strážní na svítání.", "Ž 130,6. Srov. aurora borealis – polární záře."]),
  n("beatitudo", "beātitūdinis f.", "blaženost; blahoslavenství", ["Octo sunt beatitudines.", "Blahoslavenství je osm.", "Pl. beatitudines = blahoslavenství (Mt 5,3–12)."]),
  a("concors", "gen. concordis", "svorný, jednomyslný", ["Fratres concordes vivant.", "Ať bratři žijí ve svornosti.", "Con + cor. Srov. concordia – svornost."]),
  v("confugio", "cōnfugere, cōnfūgī", "utíkám se, hledám útočiště", ["Sub tuum praesidium confugimus, sancta Dei Genetrix.", "Pod tvou ochranu se utíkáme, svatá Boží Rodičko.", "Z modlitby Sub tuum praesidium."]),
  v("considero", "cōnsīderāre, cōnsīderāvī, cōnsīderātum", "pozoruji, uvažuji", ["Ipsi vero consideraverunt et inspexerunt me.", "Oni se dívají, upřeně na mě hledí.", "Ž 22,18."]),
  n("convivium", "convīviī n.", "hostina", ["O sacrum convivium, in quo Christus sumitur.", "Ó posvátná hostino, v níž přijímáme Krista.", "Antifona sv. Tomáše Akvinského."]),
  v("declino", "dēclīnāre, dēclīnāvī, dēclīnātum", "uchyluji se, odbočuji; skloňuji", ["Unusquisque in viam suam declinavit.", "Každý se uchýlil na svou cestu.", "Iz 53,6. V gramatice: skloňovat (deklinace)."]),
  v("despicio", "dēspicere, dēspexī, dēspectum", "pohrdám; shlížím", ["Nostras deprecationes ne despicias in necessitatibus.", "Nepohrdej našimi prosbami v našich potřebách.", "Z modlitby Sub tuum praesidium."]),
  n("doctor", "doctōris m.", "učitel", ["Invenerunt illum in templo sedentem in medio doctorum.", "Našli ho v chrámě, jak sedí uprostřed učitelů.", "Lk 2,46. Doctor Ecclesiae = učitel církve."]),
  v("exhibeo", "exhibēre, exhibuī, exhibitum", "ukazuji, prokazuji; předkládám", ["Ut exhibeatis corpora vestra hostiam viventem.", "Abyste přinášeli svá těla jako živou oběť.", "Řím 12,1. Srov. exhibice."]),
  n("festum", "fēstī n.", "svátek, slavnost", ["Hodie festum magnum celebramus.", "Dnes slavíme velký svátek.", "Srov. festival."]),
  v("fungor", "fungī, fūnctus sum", "vykonávám, zastávám (+ abl.)", ["Munere suo fideliter fungitur.", "Věrně vykonává svůj úřad.", "Pojí se s ablativem. Srov. funkce, fungovat."]),
  n("genu", "genūs n.", "koleno", ["Flectamus genua.", "Klekněme.", "Z liturgie Velkého pátku. Pl. genua."]),
  n("ieiunium", "iēiūniī n.", "půst", ["Ab esu carnium abstinere et ieiunium servare.", "Zdržet se masitých pokrmů a zachovávat půst.", "Z církevních přikázání."]),
  v("indigeo", "indigēre, indiguī", "potřebuji, postrádám (+ gen./abl.)", ["Praesertim eas, quae misericordiae tuae maxime indigent.", "Zvláště ty, které tvého milosrdenství nejvíce potřebují.", "Z fatimské modlitby (O mi Iesu). Pojí se s genitivem nebo ablativem."]),
  n("intellectus", "intellēctūs m.", "rozum, chápání", ["Spiritus sapientiae et intellectus.", "Duch moudrosti a rozumu.", "Iz 11,2. Jeden z darů Ducha Svatého. Srov. intelekt."]),
  n("malitia", "malitiae f.", "zloba, zlomyslnost", ["Malitia parvuli estote.", "Ve zlém buďte jako nemluvňata.", "1 Kor 14,20."]),
  n("militia", "mīlitiae f.", "vojsko; vojenská služba", ["Tuque, Princeps militiae caelestis.", "A ty, kníže nebeských zástupů.", "Z modlitby k sv. Michaelovi. Srov. milice."]),
  n("miraculum", "mīrāculī n.", "zázrak", ["Iesus multa miracula fecit.", "Ježíš vykonal mnoho zázraků.", "Od miror – divím se."]),
  o("patienter", "příslovce", "trpělivě", ["Molestos patienter sustinere.", "Trpělivě snášet obtížné lidi.", "Jeden ze skutků duchovního milosrdenství. Od patiens."]),
  v("percutio", "percutere, percussī, percussum", "biji, udeřím", ["Corpus meum dedi percutientibus.", "Své tělo jsem vydal těm, kdo mě bili.", "Iz 50,6. Srov. perkuse."]),
  v("permaneo", "permanēre, permānsī, permānsum", "zůstávám, setrvávám", ["Quae sola inviolata permansisti.", "Jež jediná jsi zůstala neporušená.", "Z hymnu Inviolata. Srov. permanentní."]),
  v("profiteor", "profitērī, professus sum", "vyznávám, veřejně prohlašuji", ["Fidem catholicam profitemur.", "Vyznáváme katolickou víru.", "Srov. profese, profesor."]),
  a("prosperus", "prospera, prosperum", "šťastný, zdárný", ["Tribue nobis iter prosperum tempusque tranquillum.", "Dej nám šťastnou cestu a klidný čas.", "Z modlitby před cestou. Srov. prosperita."]),
  v("revelo", "revēlāre, revēlāvī, revēlātum", "odhaluji, zjevuji", ["Abscondisti haec a sapientibus et prudentibus et revelasti ea parvulis.", "Skryl jsi to před moudrými a chytrými a zjevil jsi to maličkým.", "Mt 11,25. Srov. revelace."]),
  n("servitus", "servitūtis f.", "otroctví, služba", ["Eduxi te de terra Aegypti, de domo servitutis.", "Vyvedl jsem tě z egyptské země, z domu otroctví.", "Ex 20,2. Od servus."]),
  a("simplex", "gen. simplicis", "prostý, jednoduchý; bezelstný", ["Estote prudentes sicut serpentes et simplices sicut columbae.", "Buďte obezřetní jako hadi a bezelstní jako holubice.", "Mt 10,16."]),
  a("sollemnis", "sollemne", "slavnostní", ["Benedictio sollemnis.", "Slavnostní požehnání.", "Srov. solemnita – slavnost."]),
  v("statuo", "statuere, statuī, statūtum", "stanovuji, ustanovuji; stavím", ["Diebus ab Ecclesia statutis ieiunium servare.", "Ve dnech stanovených církví zachovávat půst.", "Z církevních přikázání. Srov. statut."]),
  n("temperantia", "temperantiae f.", "mírnost, střídmost", ["Prudentia, iustitia, fortitudo, temperantia.", "Rozvážnost, spravedlnost, statečnost, mírnost.", "Jedna ze čtyř základních ctností."]),
  n("venia", "veniae f.", "odpuštění, prominutí", ["Veniam peto.", "Prosím o odpuštění."]),
  v("vulnero", "vulnerāre, vulnerāvī, vulnerātum", "zraňuji", ["Ipse autem vulneratus est propter iniquitates nostras.", "On však byl zraněn pro naše nepravosti.", "Iz 53,5."]),
  n("actus", "actūs m.", "čin, skutek, úkon", ["Actus Apostolorum", "Skutky apoštolů", "Česky akt."]),
  v("adhibeo", "adhibēre, adhibuī, adhibitum", "používám, přivolávám, přikládám", ["Medicum adhibere.", "Přivolat lékaře."]),
  n("agmen", "agminis n.", "zástup, šik, vojsko na pochodu", ["Agmen militum procedit.", "Šik vojáků postupuje."]),
  n("altitudo", "altitūdinis f.", "výška; hloubka", ["O altitudo divitiarum sapientiae et scientiae Dei!", "Ó hlubino bohatství, moudrosti a poznání Boží!", "Ř 11,33."]),
  a("arduus", "ardua, arduum", "strmý, obtížný", ["Per ardua ad astra.", "Přes překážky ke hvězdám.", "Heslo britského královského letectva (RAF)."]),
  v("attendo", "attendere, attendī, attentum", "dávám pozor, pozoruji", ["Attendite a falsis prophetis.", "Mějte se na pozoru před falešnými proroky.", "Mt 7,15."]),
  n("carcer", "carceris m.", "vězení", ["In carcere eram, et venistis ad me.", "Byl jsem ve vězení, a přišli jste ke mně.", "Mt 25,36. Česky karcer."]),
  v("comparo", "comparāre, comparāvī, comparātum", "získávám, připravuji; srovnávám", ["Nobis salutis aeternae praemia comparavit.", "Získal nám odměnu věčné spásy.", "Z modlitby po růženci. Česky komparace."]),
  v("congrego", "congregāre, congregāvī, congregātum", "shromažďuji", ["Congregavit nos in unum Christi amor.", "Shromáždila nás v jedno Kristova láska.", "Z hymnu Ubi caritas. Česky kongregace."]),
  v("consolor", "cōnsōlārī, cōnsōlātus sum", "utěšuji", ["Consolamini, consolamini, popule meus.", "Těšte, těšte můj lid.", "Iz 40,1."]),
  n("doctrina", "doctrīnae f.", "učení, nauka", ["Mea doctrina non est mea, sed eius qui misit me.", "Mé učení není mé, ale toho, který mě poslal.", "J 7,16. Česky doktrína."]),
  n("exilium", "exiliī n.", "vyhnanství", ["Nobis post hoc exilium ostende.", "Nám po tomto vyhnanství ukaž.", "Ze Salve Regina. Psáno též exsilium; česky exil."]),
  a("festus", "festa, festum", "sváteční", ["Memento, ut dies festos sanctifices.", "Pamatuj, abys světil dny sváteční.", "Třetí přikázání. Česky festival."]),
  a("fraternus", "fraterna, fraternum", "bratrský", ["Amor fraternus", "Bratrská láska", "Od frāter (bratr)."]),
  n("furtum", "furtī n.", "krádež", ["Non furtum facies.", "Nepokradeš.", "Sedmé přikázání (Ex 20,15)."]),
  v("guberno", "gubernāre, gubernāvī, gubernātum", "řídím, spravuji", ["Illumina, custodi, rege et guberna.", "Osvěcuj, opatruj, řiď a spravuj.", "Z modlitby k andělu strážnému (Angele Dei). Česky guvernér."]),
  v("honoro", "honōrāre, honōrāvī, honōrātum", "ctím", ["Honora patrem tuum et matrem tuam.", "Cti otce svého i matku svou.", "Čtvrté přikázání (Ex 20,12)."]),
  v("inclino", "inclīnāre, inclīnāvī, inclīnātum", "skláním, nakláním", ["Inclina, Domine, aurem tuam.", "Nakloň, Hospodine, své ucho.", "Ž 86,1."]),
  a("indignus", "indigna, indignum", "nehodný", ["Ego indignus famulus tuus offero tibi.", "Já, tvůj nehodný služebník, ti obětuji.", "Z obětování ve mši (Suscipe, sancte Pater). Opak dignus."]),
  n("insidiae", "insidiārum f. pl.", "úklady, léčka", ["Contra nequitiam et insidias diaboli esto praesidium.", "Proti zlobě a úkladům ďáblovým buď naší ochranou.", "Z modlitby ke sv. Michaelovi."]),
  o("iuxta", "předložka + akuz.", "vedle, u; podle", ["Stabat mater dolorosa iuxta crucem lacrimosa.", "Stála Matka bolestná u kříže uplakaná.", "Ze Stabat Mater."]),
  v("levo", "levāre, levāvī, levātum", "zvedám", ["Levavi oculos meos in montes.", "Pozvedám své oči k horám.", "Ž 121,1."]),
  v("lugeo", "lūgēre, lūxī, lūctum", "truchlím, pláču", ["Beati, qui lugent, quoniam ipsi consolabuntur.", "Blahoslavení plačící, neboť oni budou potěšeni.", "Z blahoslavenství (Mt 5)."]),
  a("molestus", "molesta, molestum", "obtížný, nepříjemný", ["Molestos patienter sustinere.", "Obtížné lidi trpělivě snášet.", "Ze skutků duchovního milosrdenství. Česky molestovat."]),
  v("nitor", "nītī, nīsus sum", "snažím se, opírám se", ["Nitimur in vetitum semper cupimusque negata.", "Vždy se ženeme za zakázaným a toužíme po odepřeném.", "Ovidius. Pozor: nitor, nitōris m. = lesk."]),
  n("oboedientia", "oboedientiae f.", "poslušnost", ["Oboedientia et pax", "Poslušnost a pokoj", "Heslo papeže Jana XXIII."]),
  n("operarius", "operāriī m.", "dělník", ["Messis quidem multa, operarii autem pauci.", "Žeň je hojná, ale dělníků málo.", "Mt 9,37."]),
  v("opto", "optāre, optāvī, optātum", "přeji si, volím", ["Opto tibi omnia bona.", "Přeji ti všechno dobré.", "Česky optativ."]),
  n("pentecoste", "Pentēcostēs f.", "Letnice", ["Cum complerentur dies Pentecostes.", "Když nastal den Letnic.", "Sk 2,1. Z řečtiny (padesátý den)."]),
  n("planta", "plantae f.", "rostlina, sazenice", ["Planta in horto crescit.", "Rostlina roste v zahradě.", "Česky plantáž."]),
  v("praevenio", "praevenīre, praevēnī, praeventum", "předcházím", ["Actiones nostras aspirando praeveni.", "Naše skutky svým vnuknutím předcházej.", "Z modlitby Actiones nostras. Česky prevence."]),
  n("protectio", "prōtectiōnis f.", "ochrana", ["Dominus protectio tua.", "Hospodin je tvá ochrana.", "Ž 121,5. Česky protekce."]),
  n("ramus", "rāmī m.", "větev, ratolest", ["Caedebant ramos de arboribus.", "Sekali ratolesti ze stromů.", "Mt 21,8."]),
  a("religiosus", "religiosa, religiosum", "zbožný; řeholní", ["Vitam religiosam ducere.", "Vést řeholní život.", "Česky religiózní."]),
  a("serenus", "serena, serenum", "jasný, klidný", ["Caelum serenum est.", "Nebe je jasné."]),
  o("seu", "spojka", "nebo, čili", ["Pigritia seu acedia.", "Lenost čili duchovní malátnost.", "Z hlavních hříchů."]),
  n("sitis", "sitis f.", "žízeň", ["In siti mea potaverunt me aceto.", "V mé žízni mě napájeli octem.", "Ž 69,22. Akuz. sitim, abl. sitī."]),
  n("sors", "sortis f.", "los, úděl", ["Super vestem meam miserunt sortem.", "O můj oděv metali los.", "Ž 22,19."]),
  v("subeo", "subīre, subiī, subitum", "podstupuji, vcházím pod", ["Non dubitavit crucis subire tormentum.", "Neváhal podstoupit muka kříže.", "Sub + eo."]),
  v("tendo", "tendere, tetendī, tentum", "napínám, směřuji", ["Ut, te duce, quo tendimus, perveniamus.", "Abychom pod tvým vedením dospěli, kam směřujeme.", "Česky tendence."]),
  n("traditio", "trāditiōnis f.", "tradice, předání; zrada", ["Iuxta antiquam traditionem.", "Podle starobylé tradice.", "Od trado (předávám)."]),
  n("vestigium", "vestigiī n.", "stopa, šlépěj", ["Ut sequamini vestigia eius.", "Abyste šli v jeho šlépějích.", "1 Pt 2,21."]),
  n("adoratio", "adōrātiōnis f.", "klanění, adorace", ["Adoratio Sanctissimi Sacramenti.", "Adorace Nejsvětější svátosti.", "Od adoro."]),
  n("advocata", "advocātae f.", "přímluvkyně, obhájkyně", ["Eia ergo, advocata nostra.", "Nuže tedy, orodovnice naše.", "Ze Salve Regina. Mužský tvar advocatus = obhájce, advokát."]),
  n("annuntiatio", "annūntiātiōnis f.", "zvěstování", ["In festo Annuntiationis Domini.", "O slavnosti Zvěstování Páně.", "Od annuntio."]),
  n("audacia", "audāciae f.", "odvaha, smělost; drzost", ["Miles magna audacia pugnavit.", "Voják bojoval s velkou odvahou.", "Od audax = smělý."]),
  n("baptismus", "baptismī m.", "křest", ["Per baptismum filii Dei efficimur.", "Křtem se stáváme Božími dětmi.", "Též baptisma, baptismatis n. Z řečtiny."]),
  o("benigne", "příslovce", "laskavě, dobrotivě", ["Benigne fac, Domine, in bona voluntate tua Sion.", "Prokaž, Pane, ve své dobrotě Siónu dobrodiní.", "Ž 51,20."]),
  a("cardinalis", "cardināle", "hlavní, základní", ["Virtutes cardinales sunt quattuor.", "Hlavní ctnosti jsou čtyři.", "Z cardo = stěžej. Odtud kardinál."]),
  n("conditor", "conditōris m.", "stvořitel, zakladatel", ["Conditor alme siderum.", "Laskavý Stvořiteli hvězd.", "Začátek adventního hymnu. Od condo = zakládám."]),
  n("congregatio", "congregātiōnis f.", "shromáždění, společenství", ["Congregatio fratrum in ecclesia orat.", "Společenství bratří se modlí v kostele.", "Odtud kongregace. Od grex = stádo."]),
  n("conspectus", "cōnspectūs m.", "pohled, zrak; přítomnost", ["Et dolor meus in conspectu meo semper.", "A moje bolest je stále přede mnou.", "Ž 38,18. In conspectu = před očima."]),
  n("conventus", "conventūs m.", "shromáždění; konvent", ["Prior conventum convocat.", "Převor svolává konvent.", "Od convenio = scházím se."]),
  v("devinco", "dēvincere, dēvīcī, dēvictum", "zcela přemáhám", ["Tu, devicto mortis aculeo, aperuisti credentibus regna caelorum.", "Ty jsi přemohl osten smrti a věřícím otevřel nebeské království.", "Z Te Deum."]),
  v("exalto", "exaltāre, exaltāvī, exaltātum", "vyvyšuji, povyšuji", ["Deposuit potentes de sede et exaltavit humiles.", "Mocné svrhl z trůnu a ponížené povýšil.", "Lk 1,52 (Magnificat)."]),
  n("exitus", "exitūs m.", "východ, odchod; konec", ["Dominus custodiat introitum tuum et exitum tuum.", "Hospodin bude střežit tvůj příchod i odchod.", "Ž 121,8. Od exeo."]),
  n("fiducia", "fīdūciae f.", "důvěra", ["Adeamus ergo cum fiducia ad thronum gratiae.", "Přistupujme tedy s důvěrou k trůnu milosti.", "Žd 4,16."]),
  n("frigus", "frīgoris n.", "chlad, zima", ["Benedicite, frigus et aestus, Domino.", "Dobrořečte Pánu, chlad a horko.", "Z kantika Benedicite (Dan 3)."]),
  a("incolumis", "incolume", "neporušený, bez úhony, zdravý", ["Incolumes ad propria redeamus.", "Ať se bez úhony vrátíme domů."]),
  a("insignis", "īnsigne", "význačný, vynikající", ["Vas insigne devotionis.", "Nádobo vznešené pobožnosti.", "Z litanií loretánských. Odtud insignie."]),
  n("invidia", "invidiae f.", "závist", ["Invidia diaboli mors introivit in orbem terrarum.", "Závistí ďáblovou vešla do světa smrt.", "Mdr 2,24. Jeden ze sedmi hlavních hříchů."]),
  n("labium", "labiī n.", "ret", ["Domine, labia mea aperies.", "Pane, otevři mé rty.", "Ž 51,17; úvod ranních chval."]),
  n("lignum", "lignī n.", "dřevo; kříž", ["Ecce lignum crucis, in quo salus mundi pependit.", "Hle, dřevo kříže, na kterém viselo spasení světa.", "Z velkopáteční liturgie."]),
  n("medicina", "medicīnae f.", "lék; lékařství", ["Paenitentia est medicina animae.", "Pokání je lékem duše.", "Odtud medicína."]),
  a("mirus", "mīra, mīrum", "podivuhodný, divný", ["Mira sunt opera Domini.", "Podivuhodná jsou díla Páně.", "Mirum in modum = podivuhodným způsobem."]),
  n("missio", "missiōnis f.", "poslání, vyslání", ["Missio Spiritus Sancti in discipulos.", "Seslání Ducha Svatého na učedníky.", "Od mitto. Odtud mise."]),
  n("norma", "normae f.", "pravidlo, měřítko", ["Evangelium est norma vitae nostrae.", "Evangelium je pravidlem našeho života.", "Odtud norma."]),
  v("obsideo", "obsidēre, obsēdī, obsessum", "obléhám, obkličuji", ["Concilium malignantium obsedit me.", "Obklíčila mě rota zločinců.", "Ž 22,17."]),
  a("pacificus", "pācifica, pācificum", "pokojný, mírumilovný", ["Beati pacifici, quoniam filii Dei vocabuntur.", "Blahoslavení tvůrci pokoje, neboť budou nazváni syny Božími.", "Mt 5,9."]),
  n("parvulus", "parvulī m.", "maličký, dítě", ["Sinite parvulos venire ad me.", "Nechte děti přicházet ke mně.", "Mk 10,14. Zdrobnělina od parvus."]),
  n("peregrinatio", "peregrīnātiōnis f.", "pouť, putování", ["Vita nostra est peregrinatio ad caelum.", "Náš život je poutí do nebe.", "Peregrinus = poutník."]),
  n("pietas", "pietātis f.", "zbožnost; láska, soucit", ["Me, tibi commissum pietate superna, illumina.", "Mne, tobě svěřeného nebeskou dobrotou, osvěcuj.", "Z modlitby Angele Dei. Odtud pieta."]),
  n("pluvia", "pluviae f.", "déšť", ["Post pluviam sol lucet.", "Po dešti svítí slunce."]),
  v("proclamo", "prōclāmāre, prōclāmāvī, prōclāmātum", "volám, hlásám", ["Tibi cherubim et seraphim incessabili voce proclamant.", "Tobě cherubíni a serafíni neustále volají.", "Z Te Deum. Odtud proklamace."]),
  o("prudenter", "příslovce", "moudře, rozvážně", ["Prudenter agere debemus.", "Máme jednat rozvážně.", "Od prudens."]),
  v("requiro", "requīrere, requīsīvī, requīsītum", "hledám, vyhledávám; žádám", ["Et laudabunt Dominum qui requirunt eum.", "A chválit budou Hospodina ti, kdo ho hledají.", "Ž 22,27."]),
  n("salutatio", "salūtātiōnis f.", "pozdrav", ["Salutatio angelica.", "Andělské pozdravení.", "Tak se nazývá Zdrávas Maria."]),
  a("sublimis", "sublīme", "vznešený, vysoký", ["Deus in sublimi habitat.", "Bůh přebývá na výsostech.", "Odtud sublimní."]),
  a("supremus", "suprēma, suprēmum", "nejvyšší; poslední", ["Deus est iudex supremus.", "Bůh je nejvyšší soudce.", "Superlativ od superus."]),
  n("textus", "textūs m.", "text; tkanina", ["Textus Evangelii legitur.", "Čte se text evangelia.", "Od texo = tkám."]),
  a("tranquillus", "tranquilla, tranquillum", "klidný, tichý", ["Mare tranquillum est.", "Moře je klidné."]),
  v("vaco", "vacāre, vacāvī, vacātum", "jsem prázdný, mám volno; věnuji se", ["Vacate et videte quoniam ego sum Deus.", "Ztište se a poznejte, že já jsem Bůh.", "Ž 46,11. Odtud vakance."]),
  n("vehiculum", "vehiculī n.", "vůz, vozidlo", ["Vehiculum per viam vehitur.", "Vůz jede po cestě.", "Od veho = vezu."]),
  n("vestimentum", "vestīmentī n.", "oděv, šat", ["Diviserunt sibi vestimenta mea.", "Rozdělili si mé šaty.", "Ž 22,19."]),
  n("vocatio", "vocātiōnis f.", "povolání", ["Vocatio a Deo venit.", "Povolání pochází od Boha.", "Od voco."]),
  n("libellus", "libellī m.", "knížka, knížečka; spis", ["Libellus precum", "Knížka modliteb", "Zdrobnělina od liber."]),
  n("litania", "litaniae f.", "litanie", ["Post antiphonam cantentur litaniae.", "Po antifoně se zpívají litanie.", "Z řečtiny (litaneia = prosba); většinou v pl. litaniae."]),
  v("obdormio", "obdormīre, obdormīvī, obdormītum", "usínám, spím", ["Exsurge, quare obdormis, Domine?", "Povstaň, proč spíš, Pane?", "Ž 44,24."]),
  a("paenitentialis", "paenitentiāle", "kajícný, kající", ["Septem psalmi paenitentiales.", "Sedm kajících žalmů.", "Od paenitentia – pokání."]),
  v("sublevo", "sublevāre, sublevāvī, sublevātum", "pozvedám, podpírám, ulehčuji", ["Eius patrocinio sublevemur.", "Kéž nás pozvedne jeho přímluva.", "Sub + levo."]),
  n("fauces", "faucium f. pl.", "hrdlo, chřtán", ["Raucae factae sunt fauces meae.", "Ochraptělo mi hrdlo.", "Ž 69,4. Sg. faux je vzácné."]),
  v("recolo", "recolere, recoluī, recultum", "připomínám si, rozjímám", ["Recolitur memoria passionis eius.", "Připomíná se památka jeho utrpení.", "Z antifony O sacrum convivium."]),
  n("coronatio", "corōnātiōnis f.", "korunování", ["Coronatio Beatae Mariae Virginis.", "Korunování Panny Marie.", "Pátý slavný desátek růžence. Srov. corona."]),
  n("ingressus", "ingressūs m.", "vstup, vchod; začátek", ["In itineris ingressu oramus.", "Na začátku cesty se modlíme.", "Od ingredior – vcházím."]),
  n("largitas", "largitātis f.", "štědrost", ["Benedic, Domine, nos et haec tua dona, quae de tua largitate sumus sumpturi.", "Požehnej, Pane, nás i tyto své dary, které z tvé štědrosti budeme požívat.", "Z modlitby před jídlem."]),
  n("prandium", "prandiī n.", "oběd", ["Ante prandium oramus.", "Před obědem se modlíme."]),
  v("termino", "termināre, termināvī, terminātum", "ukončuji, ohraničuji", ["Oratio brevi conclusione terminatur.", "Modlitba se ukončuje krátkým závěrem.", "Srov. termín, terminál."]),
  n("antiphona", "antiphōnae f.", "antifona", ["Cantor incipit antiphonam.", "Kantor začíná antifonu.", "Z řečtiny (střídavý zpěv)."]),
  n("cantor", "cantōris m.", "zpěvák, kantor", ["Cantor prosequitur.", "Kantor pokračuje.", "Od cano (zpívám)."]),
  n("invocatio", "invocātiōnis f.", "vzývání", ["Invocatio Spiritus Sancti", "Vzývání Ducha svatého", "Od invoco (vzývám)."]),
  n("lilium", "liliī n.", "lilie", ["Sicut lilium inter spinas, sic amica mea inter filias.", "Jako lilie mezi trním, tak je má přítelkyně mezi dívkami.", "Pís 2,2."]),
  n("spina", "spīnae f.", "trn", ["Plectentes coronam de spinis posuerunt super caput eius.", "Upletli korunu z trní a vložili mu ji na hlavu.", "Mt 27,29."]),
  o("iugiter", "příslovce", "ustavičně, stále", ["Iugiter oremus.", "Modleme se ustavičně."]),
  n("manna", "mannae f.", "mana", ["Patres vestri manducaverunt in deserto manna.", "Vaši otcové jedli na poušti manu.", "J 6,49. Ve Vulgátě často nesklonné."]),
  n("prosperitas", "prosperitātis f.", "zdar, blahobyt, štěstí", ["In prosperitate Deo gratias agimus.", "Ve štěstí děkujeme Bohu.", "Odtud prosperita."]),
  v("allevo", "allevāre, allevāvī, allevātum", "pozvedám, ulehčuji", ["Deus afflictos allevat.", "Bůh pozvedá zarmoucené.", "Ad + levo."]),
  v("collaudo", "collaudāre, collaudāvī, collaudātum", "velebím, společně chválím", ["Collaudate eum, omnes populi.", "Velebte ho, všechny národy.", "Ž 117,1 (Neovulgata)."]),
  a("coniugalis", "coniugāle", "manželský", ["Vita coniugalis sancta est.", "Manželský život je svatý.", "Od coniunx = manžel, manželka."]),
  a("conspicuus", "cōnspicua, cōnspicuum", "viditelný, nápadný; proslulý", ["Sanctus vir miraculis conspicuus fuit.", "Svatý muž byl proslulý zázraky.", "Od conspicio; srov. angl. conspicuous."]),
  n("desperatio", "dēspērātiōnis f.", "zoufalství", ["Desperatio salutis", "Zoufalství nad spásou", "Z hříchů proti Duchu Svatému. Srov. desperát."]),
  n("dispensatio", "dispēnsātiōnis f.", "rozdělování, správa; dispens", ["Episcopus dispensationem dedit.", "Biskup udělil dispens.", "Srov. dispens, dispenzář."]),
  n("diversitas", "dīversitātis f.", "rozmanitost, různost", ["Gentes in diversitate linguarum Deum laudant.", "Národy v rozmanitosti jazyků chválí Boha.", "Srov. diverzita."]),
  n("doxologia", "doxologiae f.", "doxologie, chvalořečení", ["Doxologia minor est Gloria Patri.", "Malá doxologie je Sláva Otci.", "Z řec. doxa = sláva + logos = slovo."]),
]);
