import { lesson, n, v, a, o } from "./define";

export default lesson("Slovíčka 6", [
  n("excommunicatio", "excommūnicātiōnis f.", "exkomunikace, vyobcování", ["Ego te absolvo a vinculo excommunicationis.", "Rozvazuji tě z pouta exkomunikace.", "Formule rozhřešení od církevního trestu."]),
  o("fiducialiter", "příslovce", "s důvěrou, směle", ["Fiducialiter agam et non timebo.", "Jsem plný důvěry a nebojím se.", "Iz 12,2. Od fiducia = důvěra."]),
  n("flagellatio", "flagellātiōnis f.", "bičování", ["Flagellatio crudelis", "Kruté bičování", "Druhé tajemství bolestného růžence. Od flagellum = bič."]),
  a("fructuosus", "frūctuōsa, frūctuōsum", "plodný, užitečný", ["Nostra oratio sit fructuosa.", "Ať je naše modlitba plodná.", "Od fructus = plod."]),
  n("gena", "genae f.", "tvář, líce", ["Genas meas vellentibus", "A tváře těm, kdo mi rvali vousy", "Iz 50,6. Obvykle v pl. genae."]),
  v("inviso", "invīsere, invīsī, invīsum", "navštěvuji", ["Carcere detentos invisere.", "Navštěvovat vězně.", "Ze skutků milosrdenství tělesných."]),
  n("locutio", "locūtiōnis f.", "řeč, mluvení", ["Locutio eius dulcis est.", "Jeho řeč je sladká.", "Od loquor = mluvím."]),
  n("margarita", "margarītae f.", "perla", ["Neque mittatis margaritas vestras ante porcos.", "Neházejte své perly sviním.", "Mt 7,6. Srov. jméno Markéta."]),
  o("mirabiliter", "příslovce", "podivuhodně, zázračně", ["Dextera Domini te mirabiliter deducat.", "Pravice Páně ať tě podivuhodně vede.", "Od mirabilis = podivuhodný."]),
  n("modestia", "modestiae f.", "skromnost, uměřenost", ["Modestia ornat iuvenes.", "Skromnost zdobí mladé.", "Jeden z plodů Ducha Svatého (Gal 5,23)."]),
  n("naufragium", "naufragiī n.", "ztroskotání", ["Ter naufragium feci.", "Třikrát jsem ztroskotal.", "2 Kor 11,25. Z navis + frango."]),
  n("obsequium", "obsequiī n.", "služba, poslušnost", ["Rationabile obsequium vestrum", "Vaše rozumná bohoslužba", "Ř 12,1. Od obsequor = vyhovuji."]),
  n("pignus", "pignoris n.", "zástava, záruka", ["Et futurae gloriae nobis pignus datur.", "A dává se nám záruka budoucí slávy.", "Z antifony O sacrum convivium."]),
  n("proclamatio", "prōclāmātiōnis f.", "hlásání, vyhlášení", ["Regni Dei proclamatio", "Hlásání Božího království", "Třetí tajemství růžence světla. Srov. proklamace."]),
  o("prospere", "příslovce", "zdárně, šťastně", ["Te duce prospere perveniamus.", "Kéž pod tvým vedením šťastně dojdeme.", "Od prosper = příznivý; srov. prosperita."]),
  v("restauro", "restaurāre, restaurāvī, restaurātum", "obnovuji", ["Christus mundum restauravit.", "Kristus obnovil svět.", "Srov. restaurovat, restaurace."]),
  n("sapor", "sapōris m.", "chuť", ["Hoc pomum dulcem saporem habet.", "Toto jablko má sladkou chuť.", "Od sapio = chutnám."]),
  a("siccus", "sicca, siccum", "suchý", ["Per mare sicco vestigio transierunt.", "Prošli mořem suchou nohou.", "Sicco vestigio = suchou nohou."]),
  v("solor", "sōlārī, sōlātus sum", "těším, utěšuji", ["Afflictos solari.", "Těšit zarmoucené.", "Ze skutků milosrdenství duchovních. Deponens."]),
  a("theologalis", "theologāle", "božský, teologální", ["Virtutes theologales sunt fides, spes, caritas.", "Božské ctnosti jsou víra, naděje a láska.", "Srov. teologie."]),
  n("transfiguratio", "trānsfigūrātiōnis f.", "proměnění", ["Transfiguratio Domini", "Proměnění Páně", "Svátek 6. srpna; čtvrté tajemství růžence světla."]),
  a("voluntarius", "voluntāria, voluntārium", "dobrovolný, úmyslný", ["Homicidium voluntarium", "Úmyslná vražda", "Jeden z hříchů do nebe volajících. Od voluntas = vůle."]),
  o("secreto", "příslovce", "potichu, tajně, v skrytu", ["Pater noster secreto dicitur.", "Otčenáš se říká potichu.", "Od secretus; srov. secretum – tajemství, sekretář."]),
  n("acetum", "acētī n.", "ocet", ["Et in siti mea potaverunt me aceto.", "A v mé žízni mě napájeli octem.", "Ž 69,22."]),
  v("addisco", "addiscere, addidicī", "přiučuji se, doučuji se", ["Cotidie aliquid addisco.", "Každý den se něčemu přiučím.", "Ad + disco."]),
  a("capitalis", "capitāle", "hlavní; smrtelný", ["Septem sunt peccata capitalia.", "Hlavních hříchů je sedm.", "Od caput – hlava. Srov. kapitál."]),
  n("commotio", "commōtiōnis f.", "pohnutí, otřes, vzrušení", ["Non det in commotionem pedem tuum.", "Nedopustí, aby se tvá noha smekla.", "Ž 121,3."]),
  a("delicatus", "dēlicāta, dēlicātum", "jemný, vybraný, rozkošný", ["Cibus delicatus est.", "Jídlo je vybrané.", "Srov. delikátní, delikatesa."]),
  n("dialogus", "dialogī m.", "rozhovor, dialog", ["Dialogum cum omnibus quaerimus.", "Hledáme dialog se všemi."]),
  v("dispenso", "dispēnsāre, dispēnsāvī, dispēnsātum", "rozděluji, uděluji; dispenzuji", ["Oeconomus pecuniam dispensat.", "Správce rozděluje peníze.", "Srov. dispens, dispenzář."]),
  a("finalis", "fīnāle", "konečný, závěrečný", ["Impaenitentia finalis.", "Konečná nekajícnost.", "Jeden z hříchů proti Duchu Svatému. Od finis."]),
  v("fodio", "fodere, fōdī, fossum", "kopu, ryji; probodávám", ["Foderunt manus meas et pedes meos.", "Probodli mi ruce i nohy.", "Ž 22,17. Srov. fosilie."]),
  n("homicidium", "homicīdiī n.", "vražda", ["Homicidium voluntarium.", "Úmyslná vražda.", "Jeden z hříchů do nebe volajících. Homo + caedo."]),
  n("impugnatio", "impugnātiōnis f.", "potírání, napadání", ["Impugnatio agnitae veritatis.", "Potírání poznané pravdy.", "Jeden z hříchů proti Duchu Svatému."]),
  v("increpo", "increpāre, increpuī, increpitum", "kárám, plísním, tupím", ["Faciem meam non averti ab increpantibus.", "Svou tvář jsem neodvrátil od těch, kdo mě tupili.", "Iz 50,6."]),
  n("inopia", "inopiae f.", "nouze, nedostatek, bída", ["Oculi mei languerunt prae inopia.", "Mé oči zeslábly bídou.", "Ž 88,10."]),
  n("inventio", "inventiōnis f.", "nalezení; vynález", ["Inventio pueri Iesu inter doctores.", "Nalezení Ježíše v chrámě mezi učiteli.", "Pátý radostný desátek růžence. Srov. invence."]),
  n("iubilatio", "iūbilātiōnis f.", "jásot, plesání", ["Beatus populus qui scit iubilationem.", "Blažený lid, který umí jásat.", "Ž 89,16. Srov. jubilovat."]),
  v("langueo", "languēre, languī", "chřadnu, slábnu", ["Quia amore langueo.", "Neboť jsem nemocná láskou.", "Pís 2,5."]),
  n("longanimitas", "longanimitātis f.", "shovívavost, velkomyslná trpělivost", ["Longanimitas est fructus Spiritus Sancti.", "Shovívavost je ovocem Ducha Svatého.", "Srov. Gal 5,22. Longus + animus."]),
  n("maxilla", "maxillae f.", "čelist; tvář", ["Si quis te percusserit in dexteram maxillam tuam, praebe illi et alteram.", "Když tě někdo udeří na pravou tvář, nastav mu i druhou.", "Mt 5,39. Srov. maxila (horní čelist)."]),
  v("moechor", "moechārī, moechātus sum", "cizoložím", ["Non moechaberis.", "Nesesmilníš.", "Šesté přikázání (Ex 20,14)."]),
  n("numen", "nūminis n.", "božstvo, božská moc", ["Numen divinum adoramus.", "Klaníme se božské moci.", "Srov. numinózní."]),
  n("observantia", "observantiae f.", "zachovávání, dodržování; kázeň", ["Fratres regularem observantiam servant.", "Bratři zachovávají řeholní kázeň.", "Srov. observance."]),
  n("offensa", "offēnsae f.", "urážka, provinění", ["Offensas remittere.", "Odpouštět urážky.", "Jeden ze skutků duchovního milosrdenství."]),
  n("oppressio", "oppressiōnis f.", "útisk, utlačování", ["Oppressio pauperum.", "Utiskování chudých.", "Jeden z hříchů do nebe volajících. Srov. oprese."]),
  v("pando", "pandere, pandī, passum", "rozprostírám, otvírám", ["Aquila alas pandit.", "Orel rozpíná křídla.", "Příčestí passum i pānsum."]),
  n("pigritia", "pigritiae f.", "lenost", ["Pigritia seu acedia.", "Lenost neboli duchovní netečnost.", "Jeden ze sedmi hlavních hříchů."]),
  n("praesumptio", "praesūmptiōnis f.", "opovážlivost, troufalost; domněnka", ["Praesumptio salutis sine meritis.", "Opovážlivé spoléhání na spásu bez zásluh.", "Jeden z hříchů proti Duchu Svatému. Srov. presumpce."]),
  v("reformo", "refōrmāre, refōrmāvī, refōrmātum", "přetvářím, obnovuji", ["Reformamini in novitate sensus vestri.", "Proměňujte se obnovou své mysli.", "Řím 12,2. Srov. reforma."]),
  v("seduco", "sēdūcere, sēdūxī, sēductum", "svádím, klamu", ["Nemo se seducat.", "Ať nikdo neklame sám sebe.", "1 Kor 3,18."]),
  n("suffragium", "suffrāgiī n.", "pomoc, přímluva; hlas (při volbě)", ["Sanctorum suffragia imploramus.", "Prosíme o přímluvu svatých.", "Srov. sufražetky."]),
  n("tormentum", "tormentī n.", "muka, trýzeň", ["Et non tanget illos tormentum mortis.", "A muka smrti se jich nedotknou.", "Mdr 3,1."]),
  n("tutela", "tūtēlae f.", "ochrana, opatrování", ["Sub tutela Dei vivimus.", "Žijeme pod Boží ochranou.", "Od tueor – chráním."]),
  v("uro", "ūrere, ussī, ustum", "pálím, spaluji", ["Per diem sol non uret te, neque luna per noctem.", "Ve dne tě slunce nespálí ani měsíc v noci.", "Ž 121,6."]),
  o("valide", "příslovce", "silně, mocně", ["Puer valide clamat.", "Chlapec silně křičí.", "Od validus. Srov. validní."]),
  o("viriliter", "příslovce", "mužně, statečně", ["Viriliter agite, et confortetur cor vestrum.", "Jednejte statečně a ať se posilní vaše srdce.", "Ž 31,25. Od vir – muž."]),
  a("acceptabilis", "acceptābile", "příjemný, milý", ["Sacrificium tibi sit acceptabile.", "Ať je ti oběť milá.", "Od accipio (přijímám)."]),
  n("adversitas", "adversitātis f.", "protivenství, nepřízeň", ["In adversitate praesidium.", "V protivenství ochrana."]),
  n("baculus", "baculī m.", "hůl", ["Virga tua et baculus tuus, ipsa me consolata sunt.", "Tvůj prut a tvá hůl jsou mi útěchou.", "Ž 23,4. Též baculum, -ī n."]),
  n("beneplacitum", "beneplacitī n.", "zalíbení, vůle", ["Deus omnia in beneplacito suo disponit.", "Bůh vše řídí podle svého zalíbení.", "Bene + placeo."]),
  n("cenaculum", "cēnāculī n.", "večeřadlo, horní místnost", ["Cum apostolis in cenaculo.", "S apoštoly ve večeřadle.", "Psáno též coenaculum. Od cēna (večeře)."]),
  v("concupisco", "concupīscere, concupīvī, concupītum", "toužím, dychtím (po čem)", ["Non concupisces domum proximi tui.", "Nebudeš dychtit po domě svého bližního.", "Ex 20,17."]),
  n("continentia", "continentiae f.", "zdrženlivost", ["Modestia, continentia, castitas.", "Skromnost, zdrženlivost, čistota.", "Z plodů Ducha svatého (Gal 5,23)."]),
  v("cooperio", "cooperīre, cooperuī, coopertum", "přikrývám, zahaluji", ["Nudos cooperire.", "Nahé odívat.", "Ze skutků tělesného milosrdenství."]),
  n("decor", "decōris m.", "krása, ozdoba, důstojnost", ["Fortitudo et decor indumentum eius.", "Síla a důstojnost jsou jejím oděvem.", "Př 31,25. Česky dekorace."]),
  v("derideo", "dērīdēre, dērīsī, dērīsum", "vysmívám se", ["Omnes videntes me deriserunt me.", "Všichni, kdo mě vidí, se mi posmívají.", "Ž 22,8."]),
  v("destituo", "dēstituere, dēstituī, dēstitūtum", "opouštím, zbavuji", ["Amici eum destituerunt.", "Přátelé ho opustili."]),
  v("enuntio", "ēnūntiāre, ēnūntiāvī, ēnūntiātum", "vyslovuji, oznamuji", ["Ante unamquamque decadem enuntietur mysterium.", "Před každým desátkem se ohlásí tajemství."]),
  n("favilla", "favillae f.", "žhavý popel, jiskra", ["Dies irae, dies illa, solvet saeclum in favilla.", "Den hněvu, ten den obrátí svět v popel.", "Z Dies irae."]),
  a("illaesus", "illaesa, illaesum", "nezraněný, neporušený", ["Domum illaesus rediit.", "Vrátil se domů nezraněn.", "In- + laesus (od laedo = zraňuji)."]),
  v("incurro", "incurrere, incurrī, incursum", "upadám (do čeho), vrážím", ["In periculum incurrit.", "Upadl do nebezpečí."]),
  n("interdictum", "interdictī n.", "zákaz; interdikt (církevní trest)", ["Absolvo te a vinculo interdicti.", "Zprošťuji tě pouta interdiktu."]),
  n("invidentia", "invidentiae f.", "závist", ["Invidentia de bono alterius spirituali.", "Závist bližnímu pro jeho duchovní dobro.", "Jeden z hříchů proti Duchu svatému."]),
  n("languor", "languōris m.", "nemoc, slabost", ["Vere languores nostros ipse tulit.", "Opravdu on nesl naše nemoci.", "Iz 53,4."]),
  n("miserator", "miserātōris m.", "slitovník, kdo se slitovává", ["Misericors et miserator Dominus.", "Milostivý a slitovný je Hospodin.", "Ž 111,4."]),
  n("obstinatio", "obstinātiōnis f.", "zatvrzelost, umíněnost", ["Obstinatio in peccatis.", "Zatvrzelost v hříších.", "Jeden z hříchů proti Duchu svatému."]),
  n("perditio", "perditiōnis f.", "zkáza, zatracení", ["Qui ad perditionem animarum pervagantur in mundo.", "Kteří ke zkáze duší obcházejí světem.", "Z modlitby ke sv. Michaelovi."]),
  a("perpes", "gen. perpetis", "trvalý, ustavičný", ["Virtute firmans perpeti.", "Posiluj stálou silou.", "Z Veni Creator. Srov. perpetuus."]),
  o("postmodum", "příslovce", "potom, později", ["Prior postmodum fratres aspergit aqua benedicta.", "Převor potom pokropí bratry svěcenou vodou."]),
  n("uber", "uberis n.", "prs, ňadro", ["Beatus venter qui te portavit, et ubera quae suxisti.", "Blažený život, který tě nosil, a prsy, které jsi sál.", "Lk 11,27. Též adj. ūber = hojný."]),
  n("varietas", "varietātis f.", "rozmanitost, proměnlivost", ["Inter omnes vitae huius varietates.", "Uprostřed všech proměn tohoto života.", "Česky varieta."]),
  n("visitatio", "visitātiōnis f.", "navštívení", ["Visitatio Beatae Mariae Virginis", "Navštívení Panny Marie", "Od visito (navštěvuji); česky vizitace."]),
  n("acedia", "acēdiae f.", "duchovní lenost, malátnost", ["Pigritia seu acedia.", "Lenost neboli duchovní malátnost.", "Jeden ze sedmi hlavních hříchů. Z řečtiny."]),
  v("adaperio", "adaperīre, adaperuī, adapertum", "otevírám (dokořán)", ["Domine, adaperi oculos nostros.", "Pane, otevři naše oči."]),
  n("agonia", "agōniae f.", "smrtelný zápas, úzkost", ["Oratio et agonia Christi in horto.", "Modlitba a smrtelný zápas Krista v zahradě.", "Z řečtiny (agónia = zápas)."]),
  v("aspiro", "aspīrāre, aspīrāvī, aspīrātum", "vdechuji, vnukám; toužím", ["Actiones nostras, quaesumus, Domine, aspirando praeveni.", "Naše skutky, prosíme, Pane, svým vnuknutím předcházej.", "Odtud aspirace."]),
  n("crucifixio", "crucifīxiōnis f.", "ukřižování", ["Crucifixio et mors in ligno crucis.", "Ukřižování a smrt na kříži.", "Z bolestných tajemství růžence."]),
  v("decurro", "dēcurrere, dēcurrī, dēcursum", "sbíhám, stékám", ["Sicut guttae sanguinis decurrentis in terram.", "Jako krůpěje krve kanoucí na zem.", "Lk 22,44. Perfektum též dēcucurrī."]),
  v("dinumero", "dīnumerāre, dīnumerāvī, dīnumerātum", "sčítám, počítám", ["Dinumeraverunt omnia ossa mea.", "Sečetli všechny mé kosti.", "Ž 22,18."]),
  a("dolorosus", "dolōrōsa, dolōrōsum", "bolestný", ["Stabat Mater dolorosa.", "Stála Matka bolestná.", "Začátek sekvence Stabat Mater."]),
  n("fel", "fellis n.", "žluč", ["Et dederunt in escam meam fel.", "Do jídla mi dali žluč.", "Ž 69,22."]),
  n("flagellum", "flagellī n.", "bič; rána", ["Milites Iesum flagellis ceciderunt.", "Vojáci zbili Ježíše biči.", "Odtud flagelace (bičování)."]),
  n("gula", "gulae f.", "obžerství; hrdlo", ["Gula est unum ex septem peccatis capitalibus.", "Obžerství je jeden ze sedmi hlavních hříchů."]),
  v("honorifico", "honōrificāre, honōrificāvī, honōrificātum", "ctím, oslavuji", ["Filius matrem suam honorificat.", "Syn ctí svou matku.", "Z honor + facio."]),
  n("impoenitentia", "impoenitentiae f.", "nekajícnost, zatvrzelost", ["Impoenitentia finalis.", "Konečná nekajícnost.", "Jeden z hříchů proti Duchu Svatému. Psáno též impaenitentia."]),
  n("indumentum", "indūmentī n.", "oděv, šat", ["Fortitudo et decor indumentum eius.", "Síla a důstojnost jsou jejím oděvem.", "Př 31,25."]),
  n("lassitudo", "lassitūdinis f.", "únava, vyčerpanost", ["Post laborem lassitudo venit.", "Po práci přichází únava."]),
  a("luminosus", "lūminōsa, lūminōsum", "světelný, zářivý", ["Mysteria luminosa.", "Tajemství světla.", "Části růžence. Od lumen = světlo."]),
  n("mansuetudo", "mānsuētūdinis f.", "mírnost, tichost", ["Mansuetudo irae opponitur.", "Mírnost je opakem hněvu."]),
  n("operatio", "operātiōnis f.", "činnost, působení", ["Cuncta nostra operatio a te incipiat.", "Ať všechna naše činnost začíná v tobě.", "Odtud operace."]),
  v("perago", "peragere, perēgī, perāctum", "vykonávám, dokončuji", ["Opere peracto fratres quiescunt.", "Po vykonané práci bratři odpočívají."]),
  v("poto", "pōtāre, pōtāvī, pōtātum", "piji; napájím", ["In siti mea potaverunt me aceto.", "V žízni mě napojili octem.", "Ž 69,22. Supinum též pōtum."]),
  n("propitiatio", "propitiātiōnis f.", "smíření, slitování", ["Quia apud te propitiatio est.", "Neboť u tebe je odpuštění.", "Ž 130,4."]),
  a("servilis", "servīle", "otrocký, služebný", ["Ab operibus servilibus vacare.", "Zdržet se služebných prací.", "Z církevních přikázání. Od servus."]),
  n("schisma", "schismatis n.", "rozkol, schizma", ["Ut non sint in vobis schismata.", "Aby mezi vámi nebyly roztržky.", "1 Kor 1,10. Z řečtiny."]),
  v("socio", "sociāre, sociāvī, sociātum", "spojuji, přidružuji", ["Deus nos sanctis suis sociat.", "Bůh nás připojuje ke svým svatým.", "Od socius = druh."]),
  a("speciosus", "speciōsa, speciōsum", "krásný, sličný", ["Speciosus forma prae filiis hominum.", "Jsi nejkrásnější ze synů lidských.", "Ž 45,3."]),
]);
